### ISSUE TITLE
Key UP and DOWN and VIM Issues

### ISSUE THREAD

**Issue by aress31** [PowerShell/Win32-OpenSSH#262] opened 2016-07-07 10:19 UTC
Hi,
Using ssh and sftp I have noticed that it is not possible to use the up and down key to navigate thourgh the terminal history. Moreover there are issues using vim or terminal text editor making text edition impossible.
Best,
Alexandre

**Comment by dragon788** [comment] 2016-07-13 18:14
This is a duplicate of #122 . There are some workarounds in that issue as well.

**Closed as completed** 2016-07-19 22:01 UTC
