### ISSUE TITLE
Windows sshd clears screen when connecting with a terminal (-t option)

### ISSUE THREAD

**Issue by skissane** [PowerShell/Win32-OpenSSH#1738] opened 2021-02-20 01:09 UTC
**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

8.1.0.0 (v8.1.0.0p1-Beta to be precise)
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

"Windows 10 Pro" (2004 to be exact)

**Client OperatingSystem**

macOS 10.14.6

**What is failing**

When I ssh from my mac to a Linux or macOS host, with a terminal allocated (`-t`), it displays the output of the command without clearing the screen first. By contrast, when I connect to a Windows host, it clears the screen first. This seems an unnecessary and annoying inconsistency between Windows and other platforms. (I will clear the screen if and when I want to do it...)

Try this:
```
ssh -t mylinuxbox echo test
ssh -t mymac echo test
ssh -t mywindowsbox echo test
```

I found an existing issue which sounds similar #108, but appears to actually be about the Windows ssh client, as opposed to the Windows sshd server. Also, it says it is fixed, but I am having this issue with latest public 8.1.0.0 build (v8.1.0.0p1-Beta). (I also saw some mention that this might be some limitation due to lack of pseudo-terminal support in Windows – given that has now been remedied by the CreatePseudoConsole API, that shouldn't be a factor any more.)

Note this only happens with `-t` option to allocate a terminal – if you run the same command without the `-t`, the screen is not cleared. But `-t` doesn't trigger screen clearing with Linux or macOS servers, so I don't think it should do it with Windows servers either.

**Expected output**
All three of Linux, macOS and Windows print "test" without clearing the screen first.

**Actual output**
Windows clears the screen first, before printing "test", unlike macOS and Windows.

**Comment by bagajjal** [comment] 2021-02-20 01:50
@skissane  - Please share the ssh client logs (ssh -vvv user@ip) and sshd logs.
By default, ssh server logging is ETW based. To change it to file based follow the below instructions,
1.	Add below config to c:\programdata\ssh\sshd_config file
SyslogFacility LOCAL0
LogLevel DEBUG3
2.	net stop sshd
3.	net start sshd
4.	ssh -vvv user@ip

**Comment by skissane** [comment] 2021-02-20 04:53
@bagajjal Logs you requested are below, thank you:

* [client-ssh.log](https://github.com/PowerShell/Win32-OpenSSH/files/6014141/client-ssh.log)
* [windows-sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/6014143/windows-sshd.log)

**Comment by bagajjal** [comment] 2021-03-03 00:59
@skissane - The screen is moved up but the contents of the screen are not cleared.

**Comment by skissane** [comment] 2021-03-03 05:07
@bagajjal Just to be clear about this, if you look in `client-ssh.log`, you will see the Windows server sends `\e[2J\e[m\e[H` to the client. If we break down what those three sequences do:
1. `\e[2J` is `CSI 2 J` which is `Erase in Display` (`ED`), and when the numeric parameter is `2` it clears the entire screen.
2. `\e[m` is `CSI m` which is `Select Graphic Rendition` (`SGR`). Invoking it without any parameters is equivalent to the numeric parameter `0`, which resets the terminal attributes (foreground and background colour, bold, italic, underline, etc) to their default values
3. `\e[H` is `CSI H` which is `Cursor Position` (`CUP`). Invoking it without any parameters is equivalent to `\e[1;1H` which sends the cursor to the home position.

If you'd like to confirm the above, you can consult any reference on ANSI escape sequences (ECMA-48 / ISO 6429 / etc), such as [the Wikipedia article](https://en.wikipedia.org/wiki/ANSI_escape_code) on that topic.

Now coming to my point, OpenSSH for Windows is indeed sending the ANSI escape sequence to clear the screen, `\e[2J`. You comment that "The screen is moved up but the contents of the screen are not cleared". That is simply an artefact of how the terminal you are using implements the ANSI "clear screen" function. At the level of ANSI escape sequences, the screen is indeed being cleared by the server.

And this is the crux of the issue. OpenSSH on other platforms (such as Linux or macOS) doesn't send this initial `\e[2J\e[m\e[H` sequence to the client when `-t` is being passed. OpenSSH on Windows does. That is an inconsistency, it can interfere with the UI of scripts which operate across multiple machines, and I don't see why it is necessary. If the user's script wants to clear (or "move up") the screen, it can send `\e[2J` itself.

**Comment by bagajjal** [comment] 2021-03-03 18:14
OpenSSH server uses pty support from windows console team. I'm looping in console team to respond.

@DHowett - Could you please take a look at this.

**Comment by DHowett** [comment] 2021-03-16 03:49
This is, unfortunately, by design. OpenSSH is using the "ConPTY" API to host console applications. My team and I own that API.

Here's what's happening.

Due to a historical mistake, we gave Win32 applications full read/write access to any rectangular region in the entire scrollback buffer--including the viewport. To offer maximum compatibility for those applications² the hosting APIs clear the screen by default, unless the application requests cursor position inheritance¹. It's the only way to provide them with consistent results should they attempt to read back (or overwrite!) a portion of the buffer above where they were started.

<details>
<summary>If we don't do that, this sort of stuff happens:</summary>

![image](https://user-images.githubusercontent.com/189190/111252955-802ba300-85cf-11eb-843d-27a7cd984bb8.png)


That's supposed to look like this:

![image](https://user-images.githubusercontent.com/189190/111252989-8faaec00-85cf-11eb-9fc3-c2e912649fbe.png)

There's a bit more info on this specific case in https://github.com/microsoft/terminal/issues/3678#issuecomment-557837893.

</details>

¹ This works by sending `DSR-CPR` and awaiting `CPR`. It won't work without a compliant terminal emulator.

² You'd be surprised how many Windows applications do things like this. PowerShell is a common one: it draws a progress bar over the top quarter of the screen by saving its contents, slapping down a bunch of characters, and then restoring the prior saved contents.

**Comment by skissane** [comment] 2021-03-16 22:40
@DHowett I understand what you are saying. ConPTY needs to start by clearing the screen otherwise apps which use legacy Win32 console API (as opposed to VT sequences) may corrupt the screen.

Can't ConPTY offer a way of opting out of that though? If you know the app you are running is only going to use VT sequences this is unnecessary. Some flag to pass to CreatePseudoConsole API , a command line option to conhost.exe, whatever, to turn this off? You could default to it being on. And OpenSSH could have a config setting corresponding to that flag/option. It would default to the current behaviour. People who desire to disable this clear-screening could set the option appropriately. They'd be choosing to accept the risk that apps using the legacy Windows console APIs may produce corrupt output. (I presume that running "CLS" or equivalent first will resolve that.)

You mention sending DSR-CPR and awaiting CPR as a way of opting out. That seems a far more difficult way of opting out of this than just an API flag.

**Comment by bagajjal** [comment] 2021-03-16 22:55
@skissane -  We can't introduce any config in the OpenSSH protocol.
sshd.exe (server process) requests for conpty.
sshd.exe can't get this information from the ssh.exe as the SSH protocol doesn't allow this.

**Comment by skissane** [comment] 2021-03-16 23:46
@bagajjal I'm not talking about introducing any extension into the OpenSSH protocol.

I am simply talking about adding a config option to the OpenSSH server configuration file.

**Comment by bagajjal** [comment] 2021-03-17 00:06
@DHowett  - Do we have any such flag that I can pass along with conpty.exe / CreatePseudoConsole() ? If yes then we can have it by default.

**Comment by bagajjal** [comment] 2021-04-12 19:17
Closing this issue as it's by design.

**Closed as completed by bagajjal** 2021-04-12 19:17 UTC
Labels: Resolution - By Design, Resolution - External

**Comment by dacodas** [comment] 2022-12-10 06:15
My apologies, can it be made more clear whether conpty.exe / CreatePseudoConsole() provides the ability to disable this behavior?

I'd like to read [this blog series](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/) the whole way through to understand the context here.

From what I see in the [CreatePseudoConsole API page](https://learn.microsoft.com/en-us/windows/console/createpseudoconsole), there doesn't seem to be much in the way of configuring this. Could a feature request be made for that API to support additional configuration through bit-fields on that `dwFlags` parameter?

It would be nice to be able to disable this behavior for clients that don't need the compatibility with Win32 applications.

**Comment by rayjanoka** [comment] 2024-05-27 05:44
I was able to avoid the terminal erase by looking for the control sequence from `stdout` and not printing that line to my console.

```go
bytes: [27 91 63 50 53 108 27 91 50 74 27 91 109 27 91 72]
hex: 1b5b3f32356c1b5b324a1b5b6d1b5b48
text: \e[?25l\e[2J\e[m\e[H
```

```go
scanner := bufio.NewScanner(stdout)
for scanner.Scan() {
	if strings.Contains(scanner.Text(), "\x1b\x5b\x32") {
		// skip screen reset on connect coming from a Win32-OpenSSH ConPTY issue
		// https://github.com/PowerShell/Win32-OpenSSH/issues/1738#issuecomment-789434169
	}
}
```

**Comment by CamRatliff** [comment] 2024-09-06 18:23
> I was able to avoid the terminal erase by looking for the control sequence from `stdout` and not printing that line to my console.
> 
> ```go
> bytes: [27 91 63 50 53 108 27 91 50 74 27 91 109 27 91 72]
> hex: 1b5b3f32356c1b5b324a1b5b6d1b5b48
> text: \e[?25l\e[2J\e[m\e[H
> ```
> 
> ```go
> scanner := bufio.NewScanner(stdout)
> for scanner.Scan() {
> 	if strings.Contains(scanner.Text(), "\x1b\x5b\x32") {
> 		// skip screen reset on connect coming from a Win32-OpenSSH ConPTY issue
> 		// https://github.com/PowerShell/Win32-OpenSSH/issues/1738#issuecomment-789434169
> 	}
> }
> ```

@rayjanoka Where do you put this function?
