### ISSUE TITLE
Pubkey auth does not work when authorized_keys are UTF-16 LE encoded

### ISSUE THREAD

**Issue by Grz3hu** [PowerShell/Win32-OpenSSH#2070] opened 2023-05-18 21:27 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Create `C:\ProgramData\ssh\administrators_authorized_keys` with UTF-16 LE encoding (this is the default formatting powershell uses, simly echo the key.pub into administrators_authorized_keys) and the pubkey auth wont work.
![image](https://github.com/PowerShell/Win32-OpenSSH/assets/53978280/550e921e-c547-4363-aa88-0d3290d8199c)

However, if file is **created** with notepad (eg `notepad.exe .\administrators_authorized_keys`) the encoding is set to utf-8 and key authentication works.
![image](https://github.com/PowerShell/Win32-OpenSSH/assets/53978280/0833abfd-8eb2-4004-a7b9-04f3c04613b4)

### Expected behavior

```console
Public key authorization works
```

### Actual behavior

```console
ssh asks for users password, ssh ran by `sshd -d` does not complain about anything, just says `Failed publickey for...`
```

### Error details

```console
No error information (!)
```

### Environment data

```PowerShell
Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : Installed
```

### Version

0.0.1.0

**Comment by PaulHigin** [comment] 2023-05-22 16:10
@Grz3hu   What version of PowerShell are you using?  AFAIK UTF8 is the expected file encoding by design.

**Comment by PaulHigin** [comment] 2023-05-22 16:17
It looks like WindowsPowerShell default encoding is UTF-16 so this is where the problem may lie.  According to PowerShell documentation:

`In general, Windows PowerShell uses the Unicode [UTF-16LE](https://wikipedia.org/wiki/UTF-16) encoding by default. However, the default encoding used by cmdlets in Windows PowerShell is not consistent.`

I believe this encoding inconsistency has been fixed in PowerShell v7+.  

Note that you can set file encoding when using WindowsPowerShell `Out-File` cmdlet using the `-Encoding` parameter.

**Comment by Grz3hu** [comment] 2023-05-22 16:23
```
PS C:\Users\grek2> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\grek2> Write-Output foo > test
PS C:\Users\grek2> file .\test
.\test: Unicode text, UTF-16, little-endian text, with CRLF line terminators
```
I think that you are right.
Btw the encoding thing isnt mentioned anywhere on the [wiki](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration?source=recommendations) so maybe it should be added since debugging it may take some time.

**Closed as completed** 2023-06-05 14:07 UTC
Labels: Resolution - Answered, Resolution - External
