### ISSUE TITLE
tab completion in powershell is broken (prints a tab character instead)

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/Win32-OpenSSH#63] opened 2016-01-02 01:02 UTC
Using iTerm with $TERM=xterm.

**Comment by manojampalam** [comment] 2016-02-01 20:46
By design for now. Will be fixed as part of making PowrShell the default ssh shell on Windows.

**Comment by manojampalam** [comment] 2016-02-01 20:49
Closing as dup of #90

**Closed by manojampalam** 2016-02-01 20:49 UTC
Labels: feature request
