### ISSUE TITLE
Regarding "error in libcrypto"

### ISSUE THREAD

**Issue by nightwish47** [PowerShell/Win32-OpenSSH#522] opened 2017-02-08 04:30 UTC
Dear experts,
I have a landscape as below:
SFTP server with OpenSSH, a client PC to connect to it using public key. After connection is made, it will execute some scripts for business purposes.

The connection is, to be honest, usually smooth. But in some random days, it gives me the message:
fatal: ssh_dispatch_run_fatal: Connection to [client IP address]: error in libcrypto

I have been searching all over the web but no solution so far. I used version 5_30_2016 which I found (maybe) relating to issue #106 and #169. Then upgraded to 0.0.8.0 waiting for some magic but no luck.
Both client and server are running Windows Server. I also checked with network provider, uptime is 99.9% so I think it's not the reason.

Thank you.

**Comment by bagajjal** [comment] 2017-02-08 18:37
can you please share the verbose logs at client side and debug3 of sshd.log (this can be set in the ssh_config)

**Comment by nightwish47** [comment] 2017-02-09 05:53
Hi, thanks for your reply.
Due to security policies, I don't have permission to collect debug3 log.
I'm running debug2. But the error still haven't occured for several days, nothing to collect. I'll keep monitor and will update debug2 log.
Please don't close this post.

**Comment by bagajjal** [comment] 2017-02-09 19:27
Ok.. I am marking it as issue-discussion till we get the issue reproduced.

**Comment by nightwish47** [comment] 2017-02-10 08:40
@bagajjal 
Please see sshd.log file, the error occured yesterday.
[sshd.log.txt](https://github.com/PowerShell/Win32-OpenSSH/files/766084/sshd.log.txt)

Network team is monitoring and tell me that Diffie-Hellman Key Exchange Reply packet is missing during connection establishment. We have Diffie-Hellman Key Exchange Init but no Reply.
Hope it can help. Thanks

**Comment by nightwish47** [comment] 2017-02-10 08:57
sorry but beside that, I also encounter some disconnections 3 minutes after connection is successfully established.
In sshd_config, I set these parameters:
```
ClientAliveInterval 60
ClientAliveCountMax 3
```
So I wonder if these are the reason.
Everything is so random so I can't make sure, just guess

**Comment by bagajjal** [comment] 2017-02-10 18:30
The clientAlive configuration makes the connection to disconnect if there is no data exchanged with in 3 min (3 * 60 sec)..

ClientAliveInterval 60
ClientAliveCountMax 3

**Comment by nightwish47** [comment] 2017-02-14 09:00
@bagajjal 
can you share somethings, some clues or kind like that. Since I want to follow the issue.

**Comment by nightwish47** [comment] 2017-02-16 07:56
@bagajjal 
>ClientAliveInterval 60
ClientAliveCountMax 3

Will the connection be terminated if there's a transmitting? Because in my system, it seems so. In the middle of session, while data is transferring, connection is cut.
I just want to make sure so I can erase it from my checklist for further investigation

And for the `error in libcrypto` and the missing of `Diffie-Hellman Key Exchange Reply`. Any clues?

Sorry for being harsh and for my English.

**Comment by manojampalam** [comment] 2017-02-17 22:08
@nightwish47 
We need you help to take the "error in libcrypto" issue further. We were not able to repro it on our side. 
As a first step, we need to get hold of the stack that is throwing this error - SSH_ERR_LIBCRYPTO_ERROR. 

For this, we need your help to do the following:
- Download sources and compile them locally. Steps are [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Building-using-VS-2015)
- We need to intercept when SSH_ERR_LIBCRYPTO_ERROR is getting returned from anywhere in the code. Here a trick that we could use:

In ssherr.h, replace this
#define SSH_ERR_LIBCRYPTO_ERROR			-22
with
#define SSH_ERR_LIBCRYPTO_ERROR_RETURN_CODE			-22

and add the following definition
int ssh_err_libcrypto_error_func();
#define  SSH_ERR_LIBCRYPTO_ERROR  ssh_err_libcrypto_error_func()

Add the following implementation to any of the c files
int ssh_err_libcrypto_error_func() {
     DebugBreak();
     return SSH_ERR_LIBCRYPTO_ERROR_RETURN_CODE;
}

If you have a postmortem debugger enabled on your machine (windbg.exe -I), any logic hitting ssh_err_libcrypto_error_func() would automatically attach to a debugger and we can get the crash stack.

**Comment by nightwish47** [comment] 2017-02-21 01:26
@manojampalam 
Sorry, this "error in libcrypto" doesn't occur in development and test environment, it only occurs in production environment so I can't handle the risk.
I know the software isn't ready for production but this kind of problem has never happened before.
Anyway, I will try your suggestion on dev/test system. Thanks.

I also attach another log file from another client. Hope it can help.
[sshd.log.20170220.txt](https://github.com/PowerShell/Win32-OpenSSH/files/788847/sshd.log.20170220.txt)

**Comment by nightwish47** [comment] 2017-02-22 02:15
Also, my system contains multiple clients. Their SSH client software are different, but the error seems to happen in some specified clients than some others.
For example:
2 clients use OpenSSH 4.3, the error only happens in 1 client.
Other 2, 1 uses WinSCP, another uses Maverick Legacy, error happens in Maverick Legacy client only.

**Comment by bagajjal** [comment] 2017-02-23 00:44
As mentioned earlier, its hard to guess what is happening without reproducing the problem because the logs doesn't provide much information...

Since you are trying use multiple SSH clients.. to nail down the problem please use only the openssh SSH client (latest 0.0.9.0) and openssh SSH server... so no third party SSH clients/servers.. 
If the error is seen in this setup then it is openssh SSH client/server issue.. 
If not then next time use only one of the third party SSH client (WinSCP / Maverick Legacy)...

This will clarify that the issue is with the openssh client/software code.. 
If we get to know that the issue is because of the third party software (WINSCP / Maverick Legacy) then you can followup with them...

**Comment by bagajjal** [comment] 2017-02-27 21:40
Can this be closed? Might be related to configuration issue mentioned in #536.

**Comment by nightwish47** [comment] 2017-03-02 04:21
@bagajjal : I think #522 is not related to #536. So please keep this issue open.

In addition, there are 2 points that we need your confirm.

1. We've received another suggestion about this error as following:
> Win32-OpenSSH version is pretty outdated, you should download a new one here:
> https://github.com/PowerShell/Win32-OpenSSH/releases. Any bugs with libeay32.lib and ssleay32.lib 
> should also be addressed there by opening a ticket.

For more details, please refer the link: http://serverfault.com/questions/835088/win32-openssh-random-error-message-error-in-libcrypto
→So I wonder that there is a high possibility this #522 is related to version issue as mentioned from serverfault.com. Could you check?
(Using version of Win32-OpenSSH is 5_30_2016)

2. Regarding to latest version of Win32-OpenSSH (v0.0.9.0).
Could you provide us the version information of OpenSSL libs that using for Win32-OpenSSH (v0.0.9.0)?
Is it newest version of OpenSSL libs?

**Comment by nightwish47** [comment] 2017-03-06 09:22
@bagajjal : Could you check following point?

> @bagajjal : I think #522 is not related to #536. So please keep this issue open.
> 
> In addition, there are 2 points that we need your confirm.
> 
> We've received another suggestion about this error as following:
> Win32-OpenSSH version is pretty outdated, you should download a new one here:
> https://github.com/PowerShell/Win32-OpenSSH/releases. Any bugs with libeay32.lib and ssleay32.lib
> should also be addressed there by opening a ticket.
> For more details, please refer the link: http://serverfault.com/questions/835088/win32-openssh-random-error-message-error-in-libcrypto
> →So I wonder that there is a high possibility this #522 is related to version issue as mentioned from serverfault.com. Could you check?
> (Using version of Win32-OpenSSH is 5_30_2016)
> 
> Regarding to latest version of Win32-OpenSSH (v0.0.9.0).
> Could you provide us the version information of OpenSSL libs that using for Win32-OpenSSH (v0.0.9.0)?
> Is it newest version of OpenSSL libs?

**Comment by nightwish47** [comment] 2017-03-20 04:22
@bagajjal :Any update for following point?

> @bagajjal : I think #522 is not related to #536. So please keep this issue open.
> 
> In addition, there are 2 points that we need your confirm.
> 
> We've received another suggestion about this error as following:
> Win32-OpenSSH version is pretty outdated, you should download a new one here:
> https://github.com/PowerShell/Win32-OpenSSH/releases. Any bugs with libeay32.lib and ssleay32.lib
> should also be addressed there by opening a ticket.
> For more details, please refer the link: http://serverfault.com/questions/835088/win32-openssh-random-error-message-error-in-libcrypto
> →So I wonder that there is a high possibility this #522 is related to version issue as mentioned from serverfault.com. Could you check?
> (Using version of Win32-OpenSSH is 5_30_2016)
> 
> Regarding to latest version of Win32-OpenSSH (v0.0.9.0).
> Could you provide us the version information of OpenSSL libs that using for Win32-OpenSSH (v0.0.9.0)?
> Is it newest version of OpenSSL libs?

**Comment by bagajjal** [comment] 2017-03-20 18:19
@nightwish47 : As mentioned earlier, we need your help in reproducing the problem. @manojampalam  has already provided the steps.
Since you have multiple SSH clients (WinSCP / Maverick Legacy / OpenSSH client), I would recommend you to try only using the openSSH (remove other third party SSH clients). This will atleast give us clear picture which ssh client is giving this issue. If it is not releated to openSSH client then you need to followup with the respective ssh client owners.

Regarding your question,
 We us V1.0.2 OpenSSL libs. There is a open issue (https://github.com/openssh/openssh-portable/pull/48) on the openSSH community to upgrade to the latest version of the OpenSSL library (V 1.1.0e).

This issue shouldn't be related to the version of the openssl as the openssh (Linux version) is using the same version of the openssl from many years. As you might already know openssh (Linux version) is very popular and > 80% of the people across the world uses it.

**Comment by nightwish47** [comment] 2017-03-28 01:38
@bagajjal : Thanks for your confirmation.

> Regarding your question,
> We us V1.0.2 OpenSSL libs. There is a open issue (openssh/openssh-portable#48) on the openSSH community to upgrade to the latest version of the OpenSSL library (V 1.1.0e).

→That's mean your team is fixing this issue on latest version?

**Comment by bagajjal** [comment] 2017-03-28 01:54
@nightwish47 Its not an error/issue but rather up gradation to the new version of the openssl library.

We are porting the openssh unix code to windows operating system.
The issue (openssh/openssh-portable#48) is with the unix openssh code but not with us.

BTW, did you make any progress by using single openssh client? Is the issue still reproducible?

**Comment by nightwish47** [comment] 2017-03-28 06:07
@bagajjal 

> BTW, did you make any progress by using single openssh client? Is the issue still reproducible?

→We tried testing openssh client with latest version on test environment. There are no any 'error in libcrypto' found until now. 
However it is very hard to upgrade the latest version of openssh on production environment right now.
So could you share us some change of settings or parameters of latest version instead of version up?

**Comment by bagajjal** [comment] 2017-03-29 01:16
I am not sure whether we have any issue with the openssh client /server because no one has reported this kind of issue.

My guess is this issue is either related to your config (or) third party ssh clients like WINSCP / Maverick Legacy.

If you use only openssh client and openssh server and if you are able to reproduce then it is our (openssh team) issue.

**Comment by nightwish47** [comment] 2017-03-30 02:16
I've got your point.
We are going try to reproduce this.

However we cannot found this issue after version up,
so we think that there is high possibility that authentication logic from openssh7.1 to openssh7.4 has changed something.

Could you help to check there are any change on Ssh_config parameter?

**Comment by bagajjal** [comment] 2017-03-30 02:21
There are no specific big changes from our side (Windows porting team)... I am not sure about the big changes from the openssh unix community..

**Comment by nightwish47** [comment] 2017-03-30 04:40
If there are any change from your side, kindly provide us in details.
Because based on your information, we can test and investigate the root cause of this issue.

**Comment by bagajjal** [comment] 2017-04-22 00:29
@nightwish47 - Are you running into this issue again when you are using only the openssh client? If not, can this be closed?

**Comment by bagajjal** [comment] 2017-04-25 20:33
If the issue still persist then please provide the steps for repro.

**Closed as completed by bagajjal** 2017-04-25 20:33 UTC
Labels: Issue-Discussion-Deprecated/use GitHub discussions
