### ISSUE TITLE
Scrolling issue when at end of screen

### ISSUE THREAD

**Issue by philiprbrenan** [PowerShell/Win32-OpenSSH#1723] opened 2021-01-15 23:27 UTC
I have installed openSSH on Windows Server 2012:

`
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2`

I connect from KUbuntu 18 via ssh:

`OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017`

I arrive in Powershell after a passwordless logon.

I type `dir `several times.  Once the screen is full it will not scroll any more and I have to issue `cls` to clear and restart it.

The `vi` editor does not work from `ssh` either.

Please tell me how to configure the terminal on windows to enable such terminal programs as `vi` and `dir` to work as they do when using `ssh `to reach a `linux` server?

**Comment by mgkuhn** [comment] 2021-01-20 18:46
Get a more recent (post-2018) Windows release. Earlier Windows version were never designed to run anything like sshd, and you merely see artifacts caused by the horrendous `cmd.exe` screen-scraping hacks that were needed before [ConPTY](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/) came along. See also #1556.

**Comment by mgkuhn** [comment] 2021-01-28 12:07
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

**Comment by bagajjal** [comment] 2021-03-04 02:59
@philiprbrenan - I'm closing this. Please try the private binary provided in #1556 .
As @mgkuhn, download level OS (windows 10 below) has limited support. commands like vi, top may not work as expected. 

Windows 10 has full fledge xterm support. We leverage major features provided by windows console.

**Closed as completed by bagajjal** 2021-03-04 02:59 UTC
