### ISSUE TITLE
ssh-keygen.exe hangs for end user

### ISSUE THREAD

**Issue by hdatma** [PowerShell/Win32-OpenSSH#836] opened 2017-08-03 10:18 UTC
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

latest
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Windows 10 Pro

**Client OperatingSystem**

Windows 10 Pro

**What is failing**

ssh-keygen.exe -t ed25519 -o -a 100 -f ${HOME}/.ssh/id_ed25519

**Expected output**

success

**Actual output**

The command does not terminate. 
No output produced at all.

**Comment by hdatma** [comment] 2017-08-03 16:53
Problem solved. 

Since nobody chimed in, I guess you already know the solution, so I will not share it.

**Comment by manojampalam** [comment] 2017-08-03 18:12
We haven't seen this problem yet. It helps the rest of us if you can share how you solved it.

**Comment by hdatma** [comment] 2017-08-04 07:08
The command "ssh-keygen.exe -t ed25519 -o -a 100 -f ${HOME}/.ssh/id_ed25519" should interact with the user, asking for a password to protect the private key soon to be generated. In the case of Win32-OpenSSH, however, the interaction fails: the command does not terminate, and you must interrupt it manually. The trick to bypass the interaction is to provide the password directly in the command, as in "ssh-keygen.exe -t ed25519 -o -a 100 -f ${HOME}/.ssh/id_ed25519 -P your-password-here".

**Comment by bagajjal** [comment] 2017-08-04 18:15
Not sure why the ssh-keygen hangs for you but it works on my machine (windows 10),

PS E:\> .\ssh-keygen.exe -t ed25519 -o -a 100 -f e:\id_ed25519
Generating public/private ed25519 key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in e:\id_ed25519.
Your public key has been saved in e:\id_ed25519.pub.
The key fingerprint is:
SHA256:Yr1hE36COC63SYnB2l83N8hHOQ5yrSUC1moHmR46TRs user@ip
The key's randomart image is:
+--[ED25519 256]--+
|                 |
|     +           |
|    E . .        |
| . * O + o .     |
|  = O B S B      |
| o * = B # .     |
|. + = . B =      |
|   = + . + .     |
|    +            |
+----[SHA256]-----+

**Comment by bagajjal** [comment] 2017-08-08 21:09
Closing this thread as we couldn't reproduce on multiple machines..

**Closed as completed by bagajjal** 2017-08-08 21:09 UTC

**Comment by RobVaughn** [comment] 2019-03-28 18:10
This should be reopened, or please direct me at a more recent open ticket?

I'm having this same issue when a file path/name is not specified, with Win 10 v1809 build 17134.

It works just fine if the -f argument with a path/filename is used, but when it's left to prompt that information, it hangs and can only be killed via the Task Manager.

The person who closed this thread did not try to replicate the actual issue above. He used the '-f' which works fine. Remove it, and when prompted it hangs.

**Comment by borisbartlog** [comment] 2019-12-06 00:11
Having just encountered this issue myself (and resolved it), I believe the problem results when you try to run ssh-keygen in cygwin. It runs normally through cmd.exe, but hangs as described when run in the cygwin shell.

**Comment by derrenbarken** [comment] 2020-03-11 05:54
Also hangs in powershell.
Windows 10 Pro version 1909 build 18363.657.  
Running ssh-keygen with no parameters
Works under cmd, freezes under powershell, at the "Enter file" prompt.

**Comment by Andrew-Archon** [comment] 2020-05-01 21:11
I'm having this issue as well and for me it's specifically occurring when creating a new key by running ssh-keygen within a PowerShell script file using the PowerShell ISE without passing a passphrase parameter into the call.

Repro:
Open PowerShell ISE and enter the following command into the editor: `ssh-keygen -t rsa -C "test" -f rsa_id_TEST`

Results in the script hanging with no output in the integrated PowerShell window.

**Comment by 1ycx** [comment] 2020-07-15 15:22
I'm using powershell 7.2 and can confirm this. It hangs on `ssh-keygen -t rsa`.

Edit: Closed powershell and tried on CMD. It works fine. Then tried on Powershell again. It worked. WHAT ?

**Comment by edyoung** [comment] 2021-11-21 20:02
Just a quick note since I hit a related problem and found this issue. 

ssh-keygen can prompt for input in several situations. As noted above you can hit this when it wants a password. In my case I hit a problem when the output file specified to -f already existed. In this case it prompts to check if you want to overwrite the file. This can cause a script to hang if there's no input for ssh-keygen to read. Because in the test environment sometimes the file was already there and sometimes it wasn't, this was a bit mystifying to debug.

**Comment by grahamas** [comment] 2022-02-04 23:12
I just ran into the same problem in git bash. Same solution of pre-specifying both password and file name.

**Comment by lukescharf** [comment] 2022-02-28 13:47
I just experienced this bug this morning with Windows 11 Pro.

ssh-keygen froze at the input-filename prompt under PowerShell (my default shell on Windows).

ssh-keygen succeeded under cmd.exe (not my default shell).

**Comment by ForNeVeR** [comment] 2022-07-03 11:00
May it also depend on terminal? In my case, it always gets stuck in Windows Terminal, but works fine in the default `conhost`.

**Comment by malauhoff** [comment] 2022-08-31 14:38
For me it stuck in Windows Terminal, but only if I added the -G parameter. I ended up in using the default filename and renaming later.

**Comment by bshoshany** [comment] 2022-10-12 15:17
This happens to me too, on Windows 11 v10.0.22000.1098 with PowerShell 7.2.6. `ssh-keygen` works fine in Command Prompt, but gets stuck in PowerShell.

**Comment by Ctucker9233** [comment] 2022-12-16 03:07
Same issue windows 10 powershell
