### ISSUE TITLE
Fix-FilePermissionInternal Errors on User 'APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES'

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#750] opened 2017-06-04 14:07 UTC
This problem is cropping up again with OpenSSHUtils.psm1, only now since I am not writing the code I can't skip over "APPLICATION PACKAGE AUTHORITY".  (previously mentioned in #719)

![image](https://cloud.githubusercontent.com/assets/11597190/26762289/9ba1784c-490d-11e7-9168-23ccc5e2d3fb.png)

I do not believe I have any third party elements on my Windows 10 machine that would add virtual accounts with these names - so I am hoping you can find out something internally in Microsoft as to what these virtual accounts are?

I have applied creators update to this machine (1703)- however - I originally reported this while still on 1607.

The believe line of code doing this is here:
https://github.com/PowerShell/Win32-OpenSSH/blob/2c3a1a95d0b36697be3da814a7fc08bdfb7db0cb/contrib/win32/openssh/OpenSSHUtils.psm1#L306

**Comment by DarwinJS** [comment] 2017-06-04 14:26
I can submit a PR for this request if that is acceptable.

**Comment by manojampalam** [comment] 2017-06-04 15:34
Yes please.

**Comment by bingbing8** [comment] 2017-06-05 21:05
@DarwinJS, I found the cause of the problem. The line you pointed above has no problem since it just remove the inheritance. The real problem is here:
'APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES'- can't translate fully qualified name. it is a win32 API bug. To workaround, we need to use the shortValue of the IdentityReference
'ALL APPLICATION PACKAGES' exists only on Win2k12 and Win2k16 and 'ALL RESTRICTED APPLICATION PACKAGES' exists only in Win2k16
I submitted a PR for the fix 
https://github.com/PowerShell/openssh-portable/pull/158

Please let me know if you want this fix in v0.0.15.0 package, or it is okay to have the fix in your chocolatey package. Thanks!

**Comment by bingbing8** [comment] 2017-06-06 22:08
@DarwinJS  i checked in the fix for this. I also exposed Fix-FilePermissions per your request from issue #744

**Comment by DarwinJS** [comment] 2017-06-07 02:19
Ahh yes - I realize that the comment I put on #756 was for this issue - I had found the code on the pull request and tested it.  Thanks!

**Closed as completed** 2017-06-07 18:25 UTC
Labels: Issue-Bug
