### ISSUE TITLE
SSH does not work through Gitlab Runner

### ISSUE THREAD

**Issue by rjpackito** [PowerShell/Win32-OpenSSH#992] opened 2017-12-15 08:19 UTC
Please answer the following

**"OpenSSH for Windows" version**
0.0.24.0
 
**Server OperatingSystem**
Windows Server 2012 R2

**Client OperatingSystem**
Windows Server 2012 R2

**What is failing**
ssh -n user@server xcopy

**Expected output**
no Error

**Actual output**
GetConsoleMode on STD_INPUT_HANDLE failed with 6

I run the csh with the -n flag, but the error repeats. Nothing helps. It is necessary for me to work with Gitlab Runner to work with the directory on the remote server. You are welcome. Help is needed.

**Comment by rjpackito** [comment] 2017-12-17 08:35
Please. Need your help.

**Comment by manojampalam** [comment] 2018-01-30 06:21
If its not too late, did you try it with -T option?

**Comment by rjpackito** [comment] 2018-01-30 06:24
@manojampalam Yes, i tried

**Comment by manojampalam** [comment] 2018-01-30 07:19
Can you share your client side logs? (use -E option to write traces to a file)

**Comment by rjpackito** [comment] 2018-01-30 07:26
@manojampalam Sorry, but I will not find those logs. I started using plink.exe and my task was solved. I can not experiment with a productive machine

**Comment by rcl4444** [comment] 2018-07-12 01:13
I also use  the Gitlab Runner
command
`ssh -n -T -E f:/1.log raochenglong@192.168.1.225 ./restartSP.sh`
1.log's content
> GetConsoleMode on STD_INPUT_HANDLE failed with 6
> 
> SetConsoleMode on STD_INPUT_HANDLE failed with 6

**Comment by kainwei** [comment] 2019-05-07 22:37
Hi All,
  I met the same problem. And I have downloaded OpenSSH 8 (https://www.mls-software.com/opensshd.html). The problem has been fixed. Never see GetConsoleMode on STD_INPUT_HANDLE failed with 6 again. Thanks for you all.

**Comment by AndreeaItu** [comment] 2019-09-18 14:52
@kainwei 
I am encountering the same issue and I am trying to install the OpenSHH version you were pointing out(https://www.mls-software.com/opensshd.html ) but for me the installation is failing for Windows.
Could you please indicate how did you manage to have this version installed ,

Thank you in advance,

Andreea

**Comment by maertendMSFT** [comment] 2020-04-07 21:38
This is a duplicate of this issue: https://github.com/PowerShell/Win32-OpenSSH/issues/856

**Closed as completed by maertendMSFT** 2020-04-07 21:38 UTC
Labels: Resolution - Duplicate, Issue-Question
