### ISSUE TITLE
Authentication - Access denied always

### ISSUE THREAD

**Issue by archiker** [PowerShell/Win32-OpenSSH#1142] opened 2018-04-24 10:23 UTC
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
PS C:\Program Files\OpenSSH-Win64> .\sshd -
unknown option -- v
OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
>> above command run failure "Get-Item : Cannot bind argument to parameter 'Path' because it is null."

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows Server 2012 Standard

**Client OperatingSystem**
Win 7

**What is failing**
I fully followed instructions https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH to install OpenSSH from scratch (no migration needed). All commands there were executed successfully. And i can see sshd and ssh-agent are running well as service.
Only thing is the binaries are in **C:\Program Files\OpenSSH-Win64** (instead of **OpenSSH**)

But there are two issues:

1. Just found **sshd_config** was not effective at all. I changed: 
- Port (to a new port#)
- PasswordAuthentication (from yes to no) 
- ChrootDirectory (to a new directory)
None of above took effective.
(the default config file name is sshd_config_default. I changed both this file and copied to a new file sshd_config)

2. Login (with WinSCP client) always failed with "Authentication with pre-entered password. Access denied" and prompts for re-enter of password. I am perfectly sure the password was correct.
Changing anything in #1 didn't make any difference.

**Expected output**
Login successfully, with configuration effectively.

**Actual output**
Login failed. sshd_config not effective at all.

**Comment by manojampalam** [comment] 2018-04-24 17:02
That sounds scary. Are you changing sshd_config under %programdata%\ssh\ ? That's the default location where its picked up from.

**Comment by bagajjal** [comment] 2018-04-24 17:34
Try https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Comment by archiker** [comment] 2018-04-25 09:15
Ah my wrong - i put the sshd_config in c:\program files\OpenSSH-Win64. Sorry.
And thanks @manojampalam .

The server is in domain. I used user name (m1234) without domain ("mgmt"), mgmt\m1234, mgmt/m1234 to login, m1234@mgmt - all failed.

I also modified sshd service to check "allow service to interact with desktop" according to https://github.com/PowerShell/Win32-OpenSSH/issues/964. Still same error.

Following @bagajjal 's advice to start sshd in debug mode, i still got same login failure as above.
The log from sshd server is below:

> C:\Windows\system32>sshd.exe -ddd
> debug2: load_server_config: filename __PROGRAMDATA__\\ssh/sshd_config
> debug2: load_server_config: done config len = 230
> debug2: parse_server_config: config __PROGRAMDATA__\\ssh/sshd_config len 230
> debug3: __PROGRAMDATA__\\ssh/sshd_config:38 setting AuthorizedKeysFile .ssh/authorized_keys
> debug3: __PROGRAMDATA__\\ssh/sshd_config:51 setting PasswordAuthentication yes
> debug3: __PROGRAMDATA__\\ssh/sshd_config:52 setting PermitEmptyPasswords no
> debug3: __PROGRAMDATA__\\ssh/sshd_config:70 setting ChrootDirectory d:\\SFTPRoot\\
> debug3: __PROGRAMDATA__\\ssh/sshd_config:77 setting Subsystem sftp      sftp-server.exe
> debug1: sshd version OpenSSH_for_Windows_7.6, LibreSSL 2.6.4
> debug3: ReadFileEx() ERROR:38, io:000000AF36360D10
> debug3: read - no more data, io:000000AF36360D10
> debug3: ReadFileEx() ERROR:38, io:000000AF36360D10
> debug3: read - no more data, io:000000AF36360D10
> debug1: private host key #0: ssh-rsa SHA256:1+EZr0QHzBEDQ8V4Bu7uKypbUC8sNKkI8xMhA60Ne2E
> debug3: ReadFileEx() ERROR:38, io:000000AF36360D10
> debug3: read - no more data, io:000000AF36360D10
> debug3: ReadFileEx() ERROR:38, io:000000AF36360D10
> debug3: read - no more data, io:000000AF36360D10
> debug1: private host key #1: ssh-dss SHA256:9O6H4PDHSi9VE+z/KGx7aFIq80ei2QYn0cp4+TYa2w0
> debug3: ReadFileEx() ERROR:38, io:000000AF36360D10
> debug3: read - no more data, io:000000AF36360D10
> debug3: ReadFileEx() ERROR:38, io:000000AF36360D10
> debug3: read - no more data, io:000000AF36360D10
> debug1: private host key #2: ecdsa-sha2-nistp256 SHA256:9mR8a2iWP/EXc9cBq5W0jCLX8SOk2/uoHaSqYJqnB5Y
> debug3: ReadFileEx() ERROR:38, io:000000AF36360D10
> debug3: read - no more data, io:000000AF36360D10
> debug3: ReadFileEx() ERROR:38, io:000000AF36360D10
> debug3: read - no more data, io:000000AF36360D10
> debug1: private host key #3: ssh-ed25519 SHA256:8Tn6cuS8crkwj4rdS1KxOZ7eGjNz++H5pilZ1nsAaWY
> debug1: rexec_argv[0]='sshd.exe'
> debug1: rexec_argv[1]='-ddd'
> debug2: fd 3 setting O_NONBLOCK
> debug3: sock_set_v6only: set socket 3 IPV6_V6ONLY
> debug1: Bind to port 22 on ::.
> Server listening on :: port 22.
> debug2: fd 4 setting O_NONBLOCK
> debug1: Bind to port 22 on 0.0.0.0.
> Server listening on 0.0.0.0 port 22.
> 
sshd started. now initiate connection from WinSCP: m1234 with password
> 
> debug3: fd 5 is not O_NONBLOCK
> debug1: Server will not fork when running in debugging mode.
> debug3: send_rexec_state: entering fd = 8 config len 230
> debug3: ssh_msg_send: type 0
> debug3: send_rexec_state: done
> Connection from 159.42.20.118 port 61090 on 10.54.171.9 port 22
> debug1: Client protocol version 2.0; client software version WinSCP_release_5.13
> debug1: no match: WinSCP_release_5.13
> debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.6
> debug2: fd 5 setting O_NONBLOCK
> debug3: LogonUserExExW failed with 1385
> 
> debug3: unable to generate sshd virtual token, falling back to s4u
> debug3: LsaLogonUser succeeded
> debug3: spawning "C:\\Program Files\\OpenSSH-Win64\\sshd.exe" "-ddd" "-y"
> debug2: Network child is on pid 2600
> debug3: send_rexec_state: entering fd = 4 config len 230
> debug3: ssh_msg_send: type 0
> debug3: send_rexec_state: done
> debug3: ssh_msg_send: type 0
> debug3: ssh_msg_send: type 0
> debug3: preauth child monitor started
> debug3: recv_rexec_state: entering fd = 3
> debug3: ssh_msg_recv entering
> debug3: recv_rexec_state: done
> debug2: parse_server_config: config __PROGRAMDATA__\\ssh/sshd_config len 230
> debug3: __PROGRAMDATA__\\ssh/sshd_config:38 setting AuthorizedKeysFile .ssh/authorized_keys
> debug3: __PROGRAMDATA__\\ssh/sshd_config:51 setting PasswordAuthentication yes
> debug3: __PROGRAMDATA__\\ssh/sshd_config:52 setting PermitEmptyPasswords no
> debug3: __PROGRAMDATA__\\ssh/sshd_config:70 setting ChrootDirectory d:\\SFTPRoot\\
> debug3: __PROGRAMDATA__\\ssh/sshd_config:77 setting Subsystem sftp      sftp-server.exe
> debug1: sshd version OpenSSH_for_Windows_7.6, LibreSSL 2.6.4
> debug3: ssh_msg_recv entering
> debug3: ssh_msg_recv entering
> debug2: fd 5 setting O_NONBLOCK
> debug3: privsep user:group 1:0 [preauth]
> debug3: list_hostkey_types: ssh-dss key not permitted by HostkeyAlgorithms [preauth]
> debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
> debug3: send packet: type 20 [preauth]
> debug1: SSH2_MSG_KEXINIT sent [preauth]
> debug3: receive packet: type 20 [preauth]
> debug1: SSH2_MSG_KEXINIT received [preauth]
> debug2: local server KEXINIT proposal [preauth]
> debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-n
> istp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-
> group14-sha256,diffie-hellman-group14-sha1 [preauth]
> debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
> debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr [preauth]
> debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr [preauth]
> debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@open
> ssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preaut
> h]
> debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@open
> ssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preaut
> h]
> debug2: compression ctos: none [preauth]
> debug2: compression stoc: none [preauth]
> debug2: languages ctos:  [preauth]
> debug2: languages stoc:  [preauth]
> debug2: first_kex_follows 0  [preauth]
> debug2: reserved 0  [preauth]
> debug2: peer client KEXINIT proposal [preauth]
> debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hel
> lman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,rsa2048-sha256,rsa1024-sha1,di
> ffie-hellman-group1-sha1 [preauth]
> debug2: host key algorithms: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss [pr
> eauth]
> debug2: ciphers ctos: aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-ctr,aes192-cbc,aes128-ctr,aes128-cbc,chac
> ha20-poly1305@openssh.com,blowfish-ctr,blowfish-cbc,3des-ctr,3des-cbc,arcfour256,arcfour128 [preauth]
> debug2: ciphers stoc: aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-ctr,aes192-cbc,aes128-ctr,aes128-cbc,chac
> ha20-poly1305@openssh.com,blowfish-ctr,blowfish-cbc,3des-ctr,3des-cbc,arcfour256,arcfour128 [preauth]
> debug2: MACs ctos: hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com
> ,hmac-sha1-96-etm@openssh.com,hmac-md5-etm@openssh.com [preauth]
> debug2: MACs stoc: hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com
> ,hmac-sha1-96-etm@openssh.com,hmac-md5-etm@openssh.com [preauth]
> debug2: compression ctos: none,zlib [preauth]
> debug2: compression stoc: none,zlib [preauth]
> debug2: languages ctos:  [preauth]
> debug2: languages stoc:  [preauth]
> debug2: first_kex_follows 0  [preauth]
> debug2: reserved 0  [preauth]
> debug1: kex: algorithm: curve25519-sha256@libssh.org [preauth]
> debug1: kex: host key algorithm: ssh-ed25519 [preauth]
> debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none [preauth]
> debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none [preauth]
> debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
> debug3: receive packet: type 30 [preauth]
> debug3: mm_key_sign entering [preauth]
> debug3: mm_request_send entering: type 6 [preauth]
> debug3: mm_key_sign: waiting for MONITOR_ANS_SIGN [preauth]
> debug3: mm_request_receive_expect entering: type 7 [preauth]
> debug3: mm_request_receive entering [preauth]
> debug3: mm_request_receive entering
> debug3: monitor_read: checking request 6
> debug3: mm_answer_sign
> debug3: mm_answer_sign: hostkey proof signature 000000AF3632FBA0(83)
> debug3: mm_request_send entering: type 7
> debug2: monitor_read: 6 used once, disabling now
> debug3: send packet: type 31 [preauth]
> debug3: send packet: type 21 [preauth]
> debug2: set_newkeys: mode 1 [preauth]
> debug1: rekey after 4294967296 blocks [preauth]
> debug1: SSH2_MSG_NEWKEYS sent [preauth]
> debug1: expecting SSH2_MSG_NEWKEYS [preauth]
> debug3: receive packet: type 21 [preauth]
> debug1: SSH2_MSG_NEWKEYS received [preauth]
> debug2: set_newkeys: mode 0 [preauth]
> debug1: rekey after 4294967296 blocks [preauth]
> debug1: KEX done [preauth]
> debug3: receive packet: type 5 [preauth]
> debug3: send packet: type 6 [preauth]
> debug3: receive packet: type 50 [preauth]
> debug1: userauth-request for user m1234 service ssh-connection method none [preauth]
> debug1: attempt 0 failures 0 [preauth]
> debug3: mm_getpwnamallow entering [preauth]
> debug3: mm_request_send entering: type 8 [preauth]
> debug3: mm_getpwnamallow: waiting for MONITOR_ANS_PWNAM [preauth]
> debug3: mm_request_receive_expect entering: type 9 [preauth]
> debug3: mm_request_receive entering [preauth]
> debug3: mm_request_receive entering
> debug3: monitor_read: checking request 8
> debug3: mm_answer_pwnamallow
> debug2: parse_server_config: config reprocess config len 230
> debug3: **NetUserGetInfo() failed with error: 2221 for user: m1234 and domain: (null)**
> 
> debug3: **NetUserGetInfo() with domainController: \\\\DC001.int.ecompany.com failed with error: 2221**
> 
Failure here bold above.
> Invalid user m1234 from 159.42.20.118 port 61090
> debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 0
> debug3: mm_request_send entering: type 9
> debug2: monitor_read: 8 used once, disabling now
> debug3: mm_inform_authserv entering [preauth]
> debug3: mm_request_send entering: type 4 [preauth]
> debug2: input_userauth_request: try method none [preauth]
> debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
> debug3: send packet: type 51 [preauth]
> debug3: mm_request_receive entering
> debug3: monitor_read: checking request 4
> debug3: mm_answer_authserv: service=ssh-connection, style=
> debug2: monitor_read: 4 used once, disabling now
> debug3: receive packet: type 50 [preauth]
> debug1: userauth-request for user m1234 service ssh-connection method keyboard-interactive [preauth]
> debug1: attempt 1 failures 0 [preauth]
> debug2: input_userauth_request: try method keyboard-interactive [preauth]
> debug1: keyboard-interactive devs  [preauth]
> debug1: auth2_challenge: user=m1234 devs= [preauth]
> debug1: kbdint_alloc: devices '' [preauth]
> debug2: auth2_challenge_start: devices  [preauth]
> debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
> debug3: send packet: type 51 [preauth]
> debug3: receive packet: type 50 [preauth]
> debug1: userauth-request for user m1234 service ssh-connection method password [preauth]
> debug1: attempt 2 failures 1 [preauth]
> debug2: input_userauth_request: try method password [preauth]
> debug3: mm_auth_password entering [preauth]
> debug3: mm_request_send entering: type 12 [preauth]
> debug3: mm_auth_password: waiting for MONITOR_ANS_AUTHPASSWORD [preauth]
> debug3: mm_request_receive_expect entering: type 13 [preauth]
> debug3: mm_request_receive entering [preauth]
> debug3: mm_request_receive entering
> debug3: monitor_read: checking request 12
> debug1: Windows authentication failed for user: NOUSER domain: (null) error:1326
> debug3: mm_answer_authpassword: sending result 0
> debug3: mm_request_send entering: type 13
> Failed password for invalid user m1234 from 159.42.20.118 port 61090 ssh2
> debug3: mm_auth_password: user not authenticated [preauth]
> debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
> debug3: send packet: type 51 [preauth]
> debug3: receive packet: type 2 [preauth]
> debug3: Received SSH2_MSG_IGNORE [preauth]
> Connection closed by invalid user m1234 159.42.20.118 port 61090 [preauth]
> debug1: do_cleanup [preauth]
> debug1: monitor_read_log: child log fd closed
> debug3: mm_request_receive entering
> debug1: do_cleanup
> debug1: Killing privsep child 2600
> C:\Windows\system32>
> C:\Windows\system32>
> C:\Windows\system32>
> C:\Windows\system32>
>

**Comment by bagajjal** [comment] 2018-04-25 17:25
@archiker - As per logs, you didn't provide domainname so it's expected.
debug3: NetUserGetInfo() failed with error: 2221 for user: m1234 and domain: (null)

You also mentioned, ssh "user@domain@ip" also didn't work? Please share sshd log for "ssh user@domain@ip". Please make sure you are running as system (execute "whoami" command) while you run sshd in debug mode (sshd.exe -ddd).
![image](https://user-images.githubusercontent.com/23668037/39262001-039ec4e4-4873-11e8-866b-b68451d36bb0.png)

**Comment by archiker** [comment] 2018-05-08 08:07
Thanks @bagajjal looking into this issue. I used different combinations but still always failed:
- user@domain@<hostname (FQDN)>
- user@domain@<host IP>

Yes i did started the sshd as "system" (used "pexec -s cmd" to start shell with system). 

Pls see attached log, including sshd log and WinSCP client log.

[m1234@domain@hostip.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1982872/m1234.domain.hostip.txt)

**Comment by archiker** [comment] 2018-05-08 11:43
Retried using Linux client "ssh m1234@<domain>@<host IP>" - same error (recursively prompt for password):

> debug3: monitor_read: checking request 8
> debug3: mm_answer_pwnamallow
> debug2: parse_server_config: config reprocess config len 230
> debug3: NetUserGetInfo() failed with error: 1722 for user: m1234 and domain: mgmt
> 
> debug3: NetUserGetInfo() with domainController: \\\\C111ZAQ failed with error: 5

**Comment by bagajjal** [comment] 2018-05-08 17:10
As per logs [Error 1212](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681383(v=vs.85).aspx) is ERROR_INVALID_DOMAINNAME.

debug3: NetUserGetInfo() failed with error: 1722 for user: m1234 and domain: mgmt@10.54.171.9
DsGetDcNameW() failed with error: 1212
Invalid user m1234@mgmt@10.54.171.9 from 159.42.20.166 port 51996
debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 0

Next steps -
It might be related to https://github.com/PowerShell/Win32-OpenSSH/issues/1098. Please use the [latest release binaries](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.6.1.0p1-Beta).

**Comment by archiker** [comment] 2018-05-09 10:47
Hi @bagajjal 
Yes i already used the latest binary of v7.6.1.0p1-Beta.
The domain name and user was correct. 

Btw, I also tried key auth per https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples. Same error:
> debug2: parse_server_config: config reprocess config len 230
> debug3: NetUserGetInfo() failed with error: 1722 for user: m1234 and domain: mgmt@10.54.171.9
> 
> DsGetDcNameW() failed with error: 1212
> 
> Invalid user m1234@mgmt@10.54.171.9 from 10.54.132.9 port 56513
> debug3: mm_answer_pwnamallow: sending MONITOR_ANS_PWNAM: 0
> debug3: mm_request_send entering: type 9

**Comment by bagajjal** [comment] 2018-05-09 17:09
Can try the full domain name (ssh user@mgmt.<xyz>.com@ip)..

**Comment by archiker** [comment] 2018-05-10 04:27
Tried multiple combinations and all failed. Different failure reasons attached
[m1234_failures.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1990361/m1234_failures.txt)


Just curious:
1) https://stackoverflow.com/questions/3663571/netusergetinfo-netlocalgroupgetinfo-returning-error-1722 indicates a Unicode string param. Is this the case?
2) for sshd service, by default its property has "Log on as" as "Local System account". Is this proper? See https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc755249(v=ws.11)

**Comment by manojampalam** [comment] 2018-05-11 20:40
@archiker, logic around user account resolution was modified significantly (in the right direction) by @nomorefood. Your issue should be fixed too as part of these changes. Recommend waiting for the next release that'll be out the coming week.

**Comment by archiker** [comment] 2018-05-14 01:34
Much appreciate @manojampalam. Looking forward to the next release.

**Comment by archiker** [comment] 2018-05-21 09:32
Hi @manojampalam and @nomorefood - any chance to know when the next release will be available? Happy to test EAP if i can have. :)

**Comment by NoMoreFood** [comment] 2018-05-21 13:08
@manojampalam You alright with me providing @archiker a private build to valid his issues are addressed?

**Comment by manojampalam** [comment] 2018-05-21 13:37
Sure

**Comment by archiker** [comment] 2018-05-29 01:59
@manojampalam - sorry i didn't see notification on new release nor test release. May you send me via email archiker@hotmail.com if feasible? Thanks

**Comment by NoMoreFood** [comment] 2018-05-29 02:14
@archiker It was me who was actually going to send you the intermediate build.  However, I'm waiting for one outstanding pull request by @manojampalam to get merged so we don't encounter a different issue.

**Comment by NoMoreFood** [comment] 2018-05-30 01:16
@archiker Please try these. Extract and overwrite your binaries. 
[ssh-testbinaries.zip](https://github.com/PowerShell/Win32-OpenSSH/files/2051976/ssh-testbinaries.zip)

**Comment by archiker** [comment] 2018-06-04 03:52
Thanks a lot @NoMoreFood !
Tried with new version (extracted zip and overwrote to installed bin director C:\Program Files\OpenSSH-Win64). 

1) only user@domain, without hostname/IP behind
It progressed with authentication and failed differently. WinSCP prompted "Cannot initialize SFTP protocol. Is the host running an SFTP server?"
The debug output at server side is attached. [new-m1234@domain.txt](https://github.com/PowerShell/Win32-OpenSSH/files/2066765/new-m1234.domain.txt)

2) While using user@domain@hostip, the authentication failed even earlier. So i guess that's not proper use now.

Any more i can try?

**Comment by NoMoreFood** [comment] 2018-06-04 23:36
@archiker Standby for the moment.  There's a unrelated problem with SFTP that is being addressed.

**Comment by manojampalam** [comment] 2018-06-05 17:47
@archiker can you try v7.7.1.0 ?

**Comment by archiker** [comment] 2018-06-12 02:30
I only found v7.7.0.0 here: https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.0.0p1-Beta
Where to get v7.7.1.0?

**Comment by manojampalam** [comment] 2018-06-12 05:10
https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.1.0p1-Beta

**Comment by archiker** [comment] 2018-06-12 08:12
Thanks @manojampalam.

I extracted the binaries and overwrite existing ones, and re-tested with user@domain as "m1234@mgmt". Same error "Server refused our key".

From debug log (attached - [sshd-debug-no-VPN.txt](https://github.com/PowerShell/Win32-OpenSSH/files/2093116/sshd-debug-no-VPN.txt));

> 
> debug1: trying public key file C:\\Users\\m1234\\.ssh/authorized_keys
> debug3: Failed to open file:C:\\Users\\m1234\\.ssh/authorized_keys error:13
> debug1: Could not open authorized keys 'C:\\Users\\m1234\\.ssh/authorized_keys': Permission denied
> debug3: mm_answer_keyallowed: publickey authentication test: RSA key is not allowed
> Failed publickey for m1234@MGMT from 10.54.132.8 port 62243 ssh2: RSA SHA256:dg995r7KeNHmDKYuj/wdkopvI+mIyAjZVdQFzSw+
> jYA
> debug3: mm_request_send entering: type 23
> debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa [preauth]
> debug3: userauth_finish: failure partial=0 next methods="publickey,password,keyboard-interactive" [preauth]
> 

It looks sshd was trying to open / create file "authorized_keys" in <HOME>/.ssh/ directory, and failed.
However i didn't find any such file in that folder. I didn't ran "sshd -ddd" from an administrative powershell.

What was the error code "13" mean? Maybe something wrong there?

**Comment by NoMoreFood** [comment] 2018-06-12 09:02
@archiker Can you please try running as a service? It looks like the account you are running the server under doesn't have read access to AD so it cannot lookup the UPN for the user.   Also, if you want publickey authentication to work, you must create authorized_keys with the thumbprint of your key file otherwise the SSH server does not known what keypair is associated with your account.

**Comment by archiker** [comment] 2018-06-14 13:12
Thanks a lot @nomorefood! I tried on a site and it worked!  But 2nd site failed as before. I will check them and try to find something.

**Comment by NoMoreFood** [comment] 2018-06-17 17:46
@archiker Interesting.  Can you try to reproduce that behavior (i.e. first time succeeds, second time fails?) after restarting the service? And if so, provide the log with both attempts.

**Closed as completed** 2020-04-14 21:42 UTC
Labels: Issue-Question, Resolution - No Repro
