### ISSUE TITLE
Running bash gives Error: 0x80070005

### ISSUE THREAD

**Issue by LongJohnCoder** [PowerShell/Win32-OpenSSH#289] opened 2016-08-10 00:05 UTC
Can't run bash under ssh. Attempting to start gives Error: 0x80070005.  Even bash --version!

**Comment by adamel** [comment] 2016-08-29 11:57
I have the same behavior on my domain connected work computer. On my home machine on the other hand starting bash works well. Odd thing is that on the work computer I can start powershell in an ssh session, but if I try that on my home machine I just get back to the cmd prompt without anything happening.

**Comment by J-Siu** [comment] 2016-08-30 15:25
I encounter the same error.

I am connecting from OS X to Windows 10 Pro. Windows 10 Pro is standalone, not in any domain.

**Comment by peva3** [comment] 2016-08-31 20:02
Running into the same issue

**Comment by ghost** [comment] 2017-06-17 12:10
Getting this too after updating sshd version. 

OpenSSH_7.5p1, LibreSSL 2.5.3
Microsoft Windows [Version 10.0.15063]

bash.exe is launching correctly, but something is stopping it launching a session

![image](https://user-images.githubusercontent.com/159567/27252802-62012090-53aa-11e7-9237-15c6d7d7a468.png)

**Comment by bagajjal** [comment] 2017-06-19 18:11
bash.exe is not allowed for the network logons.. Its the limitation from the bash.exe..

**Comment by darkverbito** [comment] 2017-07-12 20:00
I had to set Local Launch and Activation permissions for my user by taking control of the registry keys:

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AppID{F72671A9-012C-4725-9D2F-2A4D32D65169}
HKEY_CLASSES_ROOT\CLSID{4f476546-b412-4579-b64c-123df331e3d6}

Then adjusting the permissions in DCOM component services for AppId F72671A9-012C-4725-9D2F-2A4D32D65169. Before doing that I was getting an error 0x80070005 any time I would try to invoke bash over OpenSSH-Win64. Once I adjust these I was able to launch bash.

**Comment by gravcat** [comment] 2017-07-12 20:10
https://github.com/PowerShell/Win32-OpenSSH/issues/289#issuecomment-314880143

> I had to set Local Launch and Activation permissions for my user by taking control of the registry keys:
>
>HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AppID{F72671A9-012C-4725-9D2F-2A4D32D65169}
>HKEY_CLASSES_ROOT\CLSID{4f476546-b412-4579-b64c-123df331e3d6}
>
>Then adjusting the permissions in DCOM component services for AppId F72671A9-012C-4725-9D2F-2A4D32D65169. Before doing that I was getting an error 0x80070005 any time I would try to invoke bash over OpenSSH-Win64. Once I adjust these I was able to launch bash.

I was also able to successfully SSH into my machine and then execute bash by following this suggestion.

**Comment by miller-time** [comment] 2017-11-14 03:47
@darkverbito / @gravcat : I tried to follow those instructions and I'm still getting 0x80070005 every time I launch bash from an SSH connection. 

I've never really messed with DCOM settings before, so here's a rundown of what I did... After changing the owner on those two registry keys, I went into `dcomcnfg` and found {F72671A9-012C-4725-9D2F-2A4D32D65169} under Component Services > Computers > My Computer > DCOM Config. I wasn't sure which user to grant which permissions to, so I just gave "Everyone" full access (local and remote launch/activation, local and remote access, full control).

Did I miss a step? Any ideas?

Thanks

**Comment by nucleusprod** [comment] 2017-11-14 04:34
@miller-time I wrote a blog post about this: https://adrift.io/2017/10/11/windows-subsystem-for-linux-error-0x80070005-access-denied/

Hope that is more directly helpful!

**Comment by gravcat** [comment] 2017-11-14 04:35
@miller-time I wrote a blog post about this: https://adrift.io/2017/10/11/windows-subsystem-for-linux-error-0x80070005-access-denied/

Hope that is more directly helpful!

**Comment by miller-time** [comment] 2017-11-14 06:41
@gravcat Thanks but I actually went a different route. Running ssh server from bash was much easier... lol

**edit**: weird the GUID's look like they are different than your comment above. I'm curious, how you do figure out what the DCOM id is for an application?

**Comment by manojampalam** [comment] 2018-01-25 01:08
Closing this as the issue is with bash permissions.

**Closed as completed by manojampalam** 2018-01-25 01:08 UTC
Labels: Issue-Bug, Area-Terminal

**Comment by hgghyxo** [comment] 2018-03-11 13:51
This snippet helped me: https://gist.github.com/gravcat/4ceb977916c5f551cae44375296ab72a
