### ISSUE TITLE
ssh-agents fails to authenticate while ssh succeeds with the same key for a certain host

### ISSUE THREAD

**Issue by MihaMarkic** [PowerShell/Win32-OpenSSH#1621] opened 2020-06-05 15:45 UTC
**"OpenSSH for Windows" version**
 `7.7.2.3`
 
**Server OperatingSystem**
 `Raspberry OS`

**Client OperatingSystem**
Windows 10

**What is failing**
ssh-agent won't authenticate while ssh, given I type password for private key, succeeds with the same key. Currently it happens only against Raspberry OS while it works against various Ubuntu distributions, github and gitlab.
Also authenticating from MacOS works as expected.

**Expected output**
ssh-agent authenticates

**Actual output**
Excerpt from ssh -vvvv when ssh-agent fails
```
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:XXX [PATH]/.ssh/id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: pkalg rsa-sha2-512 blen 277
debug2: input_userauth_pk_ok: fp SHA256:XXX
debug3: sign_and_send_pubkey: RSA SHA256:XXX
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: [PATH]/.ssh/id_rsa
debug3: failed to open file:C:/dev/tty error:3
debug1: read_passphrase: can't open /dev/tty: No such file or directory
... I type password and it succeeds ...
```

And this is an excerpt against Ubuntu where agent succeeds
```
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:XXX [PATH]/.ssh/id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: pkalg rsa-sha2-512 blen 277
debug2: input_userauth_pk_ok: fp SHA256:XXX
debug3: sign_and_send_pubkey: RSA SHA256:XXX
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
```

**Comment by bagajjal** [comment] 2020-06-05 17:15
Duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1263

**Closed as completed by bagajjal** 2020-06-05 17:15 UTC
