### ISSUE TITLE
ssh-keygen -G modulus candidate generation failed

### ISSUE THREAD

**Issue by itsupport-iattc** [PowerShell/Win32-OpenSSH#899] opened 2017-10-03 17:47 UTC
Please answer the following:

This is an ssh-keygen issue
 
**Server Operating System**  Windows Server 2012 R2

**Client Operating System** n/a

**What is failing**  Cannot generate primes file.

**Expected output** "Candidate primes" file necessary to generate moduli file. 
Note: I'm not an expert. Following  instructions at https://entropux.net/article/openssh-moduli/

**Actual output**
c:\OpenSSH-Win64>ssh-keygen -G ./4096.1 -b 4096
Tue Oct  3 10:19:31 2017 Sieve next 268304384 plus 4095-bit
Tue Oct  3 10:30:32 2017 Sieved with 203277289 small primes in 661 seconds
Tue Oct  3 10:30:33 2017 Found 0 candidates
modulus candidate generation failed
c:\OpenSSH-Win64>

**Comment by itsupport-iattc** [comment] 2017-10-03 17:52
I'm doing this because a client that I have no control over is connecting and causing the following to appear in sshd.log. The Filezilla client connects without warnings or errors.

6100 15:25:26:500 Server listening on :: port 22.
6100 15:25:26:500 Server listening on 0.0.0.0 port 22.
5852 15:25:46:818 WARNING: could not open ./moduli (No such file or directory), using fixed modulus
5852 15:26:03:712 Accepted password for ftpuser1 from (IP address) port 1792 ssh2
5852 15:26:06:618 Received disconnect from (IP address) port 1792:11: Connection terminated by the client.

**Comment by itsupport-iattc** [comment] 2017-10-10 21:49
ssh-keygen -G moduli-2048.candidates -b 2048 fails in the same way on Windows Server 2012 R2, Windows 7 and Windows 10, "Found 0 candidates, modulus candidate generation failed"

Any ideas?

**Comment by itsupport-iattc** [comment] 2017-10-12 17:06
Hello?

**Comment by bingbing8** [comment] 2018-01-03 21:02
@itsupport-iattc, I tried build [v0.0.24.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/0.0.24.0) on windows 2012 R2 and windows 10, it works for me:
```
PS C:\Program Files\OpenSSH> .\ssh-keygen.exe -G 4096.1 -b 4096
Wed Jan  3 17:58:54 2018 Sieve next 268304384 plus 4095-bit
Wed Jan  3 18:04:27 2018 Sieved with 203277289 small primes in 333 seconds
Wed Jan  3 18:05:04 2018 Found 221392 candidates
```
it does not work win7. The issue is in the libcrypto code. The issue will gone after update to latest release of libssl, I will update the libcrypto.dll

**Comment by itsupport-iattc** [comment] 2018-01-04 01:10
@bingbing8 I installed v0.0.24.0 and tried again on Windows Server 2012 R2. Same result.

PS C:\Program Files\OpenSSH> .\ssh-keygen -G .\4096.1 -b 4096
Wed Jan  3 16:44:16 2018 Sieve next 268304384 plus 4095-bit
Wed Jan  3 16:56:24 2018 Sieved with 203277289 small primes in 728 seconds
Wed Jan  3 16:56:24 2018 Found 0 candidates
modulus candidate generation failed
PS C:\Program Files\OpenSSH>

**Comment by bingbing8** [comment] 2018-01-04 01:19
@itsupport-iattc, can you replace the libcrypto.dll with the attached files? it works for me on win7, win2k12 R2 and win10. 
[libcrypto.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1602177/libcrypto.zip)

The failed case I saw on win7 was when writing big number to a file. If you still repro after replace libcryto.dll, can you please install openssh to a different folder instead of under $env:ProgramFiles and try to see if it is related with the permission of directory.

**Comment by audpa33** [comment] 2018-01-06 10:17
Hello,

I have the same issue on Windows 10 Pro (FR) using version 0.0.24 with shipped libcrypto.dll and libcrypto.dll included in ZIP file provided in previous message by @bingbing8 .

Example of output with 2048 bits:
```
Sat Jan  6 11:10:20 2018 Sieve next 67043328 plus 2047-bit
Sat Jan  6 11:13:49 2018 Sieved with 203277289 small primes in 209 seconds
Sat Jan  6 11:13:49 2018 Found 0 candidates
modulus candidate generation failed
```

I will be pleased to test others DLL or version it it helps to solve this issue.

Regards

**Comment by itsupport-iattc** [comment] 2018-01-31 00:05
@bingbing8 - There is a file called libcrypto-41.dll in the OpenSSH folder. When I extract the dll in your zip file, what name should I give it? Also, I assume I should restart the services for the new dll to be used. Is this correct?

**Comment by JW0914** [comment] 2018-01-31 13:50
This is still an issue on v1.0.0.0-Beta:

```
PS C:\ProgramData\Scripts\Sign> ssh-keygen -G moduli.2048 -b 2048
Tue Jan 30 19:46:03 2018 Sieve next 67043328 plus 2047-bit
Tue Jan 30 19:48:52 2018 Sieved with 203277289 small primes in 169 seconds
Tue Jan 30 19:48:52 2018 Found 0 candidates
modulus candidate generation failed
```

**Comment by bingbing8** [comment] 2018-02-28 01:41
@itsupport-iattc , which release do you use? Starting [v0.0.23.0](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.23.0), we only ship libcrypto.dll in the package.

**Comment by audpa33** [comment] 2018-08-24 07:10
I tested with version v7.7.2.0p1-Beta and it works fine now.

```
ssh-keygen -G ./4096.1 -b 4096
Fri Aug 24 07:57:14 2018 Sieve next 268304384 plus 4095-bit
Fri Aug 24 08:03:47 2018 Sieved with 203277289 small primes in 393 seconds
Fri Aug 24 08:04:01 2018 Found 221393 candidates

```
Thanks

Regards

**Comment by bingbing8** [comment] 2018-08-24 20:43
I will close this issue for now. Please reopen if you see it again.

**Closed as completed by bingbing8** 2018-08-24 20:43 UTC
Labels: Issue-Bug
