### ISSUE TITLE
Bash failure after ssh into sshd host

### ISSUE THREAD

**Issue by Jocala** [PowerShell/Win32-OpenSSH#1077] opened 2018-02-17 21:43 UTC
I  get the Error: 0x80070005 when I ssh into Windows 10 and run bash.

OpenSSH 7.6p1
v1.0.0.0-Beta
OpenSSH-Win64.zip

Surface Pro 3
winver 1709:16299.248

From a different thread: I did restart into safe mode and nuke the lxss\temp directory, no difference.

Occurs with all clients.

**Comment by bagajjal** [comment] 2018-02-20 19:14
Duplicate of #289
Closing this as its a bash issue.

**Closed as completed by bagajjal** 2018-02-20 19:14 UTC

**Comment by Jocala** [comment] 2018-02-20 19:39
Thanks, the link to #289 was very helpful.
