### ISSUE TITLE
OpenSSH Server and Putty to localhost limited display of output rows

### ISSUE THREAD

**Issue by redboyhun** [PowerShell/Win32-OpenSSH#1690] opened 2020-10-19 09:49 UTC
ProductName       : OpenSSH for Windows
FileName          : C:\Program Files\OpenSSH\sshd.exe
FileVersion       : 8.1.0.0
ProductVersion    : OpenSSH_8.1p1 for Windows
Language          : English (United States)
FileVersionRaw    : 8.1.0.0
ProductVersionRaw : 8.1.0.0
 
**Server OperatingSystem**
Windows Server 2016 Standard Evaluation
BuildNumber     : 14393
Version         : 10.0.14393

**Client OperatingSystem**
Windows Server 2016 Standard Evaluation
BuildNumber     : 14393
Version         : 10.0.14393
LOCALHOST

**What is failing**
Putty row is limited, independently from initial settings (row number).
See Picture: Rows after Line 41 are not visible.
![opensshwin-putty](https://user-images.githubusercontent.com/34648596/96429121-de12b500-1200-11eb-9c8c-95e093929290.png)

**Expected output**
100 rows

**Actual output**
45-50 rows only, any more output is not visible

[sshd_debug.zip](https://github.com/PowerShell/Win32-OpenSSH/files/5400839/sshd_debug.zip)

**Comment by mgkuhn** [comment] 2020-12-05 17:34
Possibly a duplicate of #1556? If so, try @bagajjal 's private `ssh-shellhost.exe` binary from there and report back. Or upgrade to a newer operating system with ConPTY support.

**Comment by mgkuhn** [comment] 2021-05-14 11:17
Does this problem still exist on Windows 10/Server 1903 or newer with KB5003173 installed (which upgraded the OpenSSH version in Windows Features to 8.1 this week)? If not, can you close this ticket?

**Comment by bagajjal** [comment] 2021-05-14 16:42
Thanks @mgkuhn . Duplicate of #1556. The fix will be part of next release, Openssh V8.6

**Closed as completed by bagajjal** 2021-05-14 16:42 UTC
Labels: Resolution - Fixed
