### ISSUE TITLE
Host not communicating more than 15 seconds still waiting

### ISSUE THREAD

**Issue by sunil77-i** [PowerShell/Win32-OpenSSH#1779] opened 2021-04-21 15:31 UTC
Hi All,

I am trying to login to OpenSSH using Winscp but i am facing below issue, But after restarting the service it fixed the issue. But why it causes the issue. I verified OpenSSH server is in running state and Ports 22 in firewall is enabled. Please help me to solve this issue.

![image](https://user-images.githubusercontent.com/79965477/115580001-52c7c880-a2e4-11eb-8f1d-16a5b36a3727.png)

Thanks,
Sunil

**Comment by bagajjal** [comment] 2021-04-21 17:17
@sunil77-i - It's hard to say just looking at this information. 
Please follow instructions [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps) to debug.

**Comment by sunil77-i** [comment] 2021-04-21 17:40
@bagajjal Thanks for your reply, But what is the main reason for this issue either the issue is from Server side or from Firewall or port?

**Comment by bagajjal** [comment] 2021-04-21 17:44
As I said it's hard to say just looking at the error. 
You can look at the sshd.log to check any errors.

Please close the issue if your issue is solved.

**Comment by sunil77-i** [comment] 2021-04-22 03:45
@bagajjal I have tried the steps mentioned here,  I found the below logs please have look into it.

![image](https://user-images.githubusercontent.com/79965477/115652458-ed5af280-a34a-11eb-9062-9653d0e631b4.png)

Thanks,
Sunil

**Comment by sunil77-i** [comment] 2021-04-22 14:25
@bagajjal May I get any update on this please.

Thanks,
Sunil

**Comment by bagajjal** [comment] 2021-04-22 17:02
The problem is with the host keys. 

If you are not worried about using new host keys then delete all existing host keys ($env:programdata\ssh\ssh_host*) and restart the sshd service (net stop sshd; net start sshd).

Else try to debug what's wrong with the host keys. These are possible reasons.
Make sure host keys are accessible only to "local administrators group", "system account".  Check Get-Acl <host_file_name> | fl *
host keys encoding format should be UTF-8.

**Comment by sunil77-i** [comment] 2021-04-23 05:52
@bagajjal Hi,

I have checked the accessibility for all host keys those are accessible only to the "local administrators group", "system account".
please let me know if I have missed anything.

![image](https://user-images.githubusercontent.com/79965477/115824606-d3421280-a425-11eb-88ee-6d34fb19b21c.png)
![image](https://user-images.githubusercontent.com/79965477/115824673-e9e86980-a425-11eb-8099-12775b1c4c54.png)
![image](https://user-images.githubusercontent.com/79965477/115824734-05ec0b00-a426-11eb-94ab-9c772f758d8d.png)
![image](https://user-images.githubusercontent.com/79965477/115824792-23b97000-a426-11eb-80c9-3f1a9525217d.png)

Thanks,
Sunil

**Comment by sunil77-i** [comment] 2021-04-23 16:46
Hi @bagajjal,

May I get any update please.

Thanks,
Sunil

**Comment by bagajjal** [comment] 2021-04-23 17:14
@sunil77-i - As per the [screenshot you shared in the other issue](https://github.com/PowerShell/Win32-OpenSSH/issues/1778#issuecomment-825402810)  this issue is no longer happening.

fyi, sshd.exe -ddd should always be ran in an elevated powershell /cmd window.

Please followup on one issue as the issue seems to be same.

**Comment by bagajjal** [comment] 2021-04-30 01:42
@sunil77-i - Are you still facing this issue?

**Comment by bagajjal** [comment] 2021-05-04 21:24
If you are still facing this issue, please reopen with the requested information.

**Closed as completed by bagajjal** 2021-05-04 21:24 UTC
Labels: Waiting on Author
