### ISSUE TITLE
No return to client when executing slow remote commands and sending EOF before child execution concludes

### ISSUE THREAD

**Issue by imayobrown** [PowerShell/Win32-OpenSSH#563] opened 2017-03-06 17:40 UTC
Hi all,

When executing slow remote commands on the server and sending an EOF from the client before the execution of the spawned child process (ssh-shellhost.exe on the server) has completed results in nothing being returned to the client.

It seems once a ```MESSAGE_CHAN_EOF``` has been received by sshd on a channel it sets the ```ostate ``` of the channel to ```CHAN_OUTPUT_WAIT_DRAIN```. If the output buffer of the channel has not yet been populated (due to slow comand) by the child process, sshd closes the channel and none of the output from the child process is sent to the client. 

Here are partial DEBUG2 logs that result from this behavior:

~~~
2232 12:30:38 471 Starting session: command for [user] from [ipaddress] port [port] id 0
2232 12:30:38 471 debug1: pipe - r-h:432,io:00F78C38,fd:7  w-h:444,io:00F78CB8,fd:8
2232 12:30:38 471 debug1: pipe - r-h:452,io:00F78320,fd:9  w-h:456,io:00F783A0,fd:10
2232 12:30:38 471 debug1: pipe - r-h:460,io:00F78420,fd:11  w-h:464,io:00F784A0,fd:12
2232 12:30:38 471 debug2: fd 7 setting O_NONBLOCK
2232 12:30:38 471 debug2: fd 8 setting O_NONBLOCK
2232 12:30:38 471 debug2: fd 9 setting O_NONBLOCK
2232 12:30:38 471 debug2: fd 10 setting O_NONBLOCK
2232 12:30:38 471 debug2: fd 11 setting O_NONBLOCK
2232 12:30:38 471 debug2: fd 12 setting O_NONBLOCK2232 12:30:38 471 debug1: Executing command: C:\\openssh\\OpenSSH-Win32\\ssh-shellhost.exe -nopty amF2YSAtdmVyc2lvbg==
2232 12:30:38 471 debug1: Register child 000001EC pid 1524, 0 zombies of 0
2232 12:30:38 471 debug2: fd 3 setting TCP_NODELAY
2232 12:30:38 471 debug1: close - io:00F78C38, type:2, fd:7, table_index:7
2232 12:30:38 471 debug2: fileclose - pio:00F78C38
2232 12:30:38 471 debug1: close - io:00F783A0, type:2, fd:10, table_index:10
2232 12:30:38 471 debug2: fileclose - pio:00F783A0
2232 12:30:38 471 debug1: close - io:00F784A0, type:2, fd:12, table_index:12
2232 12:30:38 471 debug2: fileclose - pio:00F784A0
2232 12:30:38 471 debug2: on_select - io:00F7BC38 type:1 rd:1
2232 12:30:38 471 debug2: WSARecv - reported IO pending
2232 12:30:38 471 debug2: on_select - io:00F7BC38 type:1 rd:0
2232 12:30:38 471 debug2: ReadFileEx io:00F78320
2232 12:30:38 471 debug2: ReadFileEx io:00F78420
2232 12:30:38 471 debug2: send - io:00F7BC38
2232 12:30:38 471 debug2: send - WSASend() returned 0, APC scheduled io:00F7BC38
2232 12:30:38 471 debug2: WSASendCB - io:00F7BC38, pending_state:1, error:0, sent:88 of remaining:88
2232 12:30:38 471 debug2: on_select - io:00F7BC38 type:1 rd:1
2232 12:30:38 486 debug2: WSARecvCompletionCB - io:00F7BC38, pending_state:1, flags:0, error:0, received:36
2232 12:30:38 486 debug2: recv - returning 36 bytes from prior completed IO, remaining:0, io:00F7BC38
2232 12:30:38 486 debug2: channel 0: rcvd eof
2232 12:30:38 486 debug2: channel 0: output open -> drain
2232 12:30:38 486 debug2: channel 0: obuf empty
2232 12:30:38 486 debug2: channel 0: close_write
2232 12:30:38 486 debug1: close - io:00F78CB8, type:2, fd:8, table_index:8
2232 12:30:38 486 debug2: fileclose - pio:00F78CB8
2232 12:30:38 486 debug2: channel 0: output drain -> closed
2232 12:30:38 486 debug2: on_select - io:00F7BC38 type:1 rd:1
2232 12:30:38 486 debug2: WSARecv - reported IO pending
2232 12:30:38 486 debug2: ReadCB pio:00F78320, pending_state:1, error:109, received:0
2232 12:30:38 486 debug2: read - (2) no more data, io:00F78320
2232 12:30:38 486 debug2: channel 0: read<=0 rfd 9 len 0
2232 12:30:38 486 debug2: channel 0: read failed
2232 12:30:38 486 debug2: channel 0: close_read
2232 12:30:38 486 debug1: close - io:00F78320, type:2, fd:9, table_index:9
2232 12:30:38 486 debug2: fileclose - pio:00F78320
2232 12:30:38 486 debug2: channel 0: input open -> drain
2232 12:30:38 486 debug2: channel 0: ibuf_empty delayed efd 11/(0)
2232 12:30:38 486 debug2: on_select - io:00F7BC38 type:1 rd:1
2232 12:30:38 486 debug2: ReadCB pio:00F78420, pending_state:1, error:109, received:0
2232 12:30:38 486 debug2: read - (2) no more data, io:00F78420
2232 12:30:38 486 debug2: channel 0: read 0 from efd 11
2232 12:30:38 486 debug2: channel 0: closing read-efd 11
2232 12:30:38 486 debug1: close - io:00F78420, type:2, fd:11, table_index:11
2232 12:30:38 486 debug2: fileclose - pio:00F78420
2232 12:30:38 486 debug2: channel 0: ibuf empty
2232 12:30:38 486 debug2: channel 0: send eof
2232 12:30:38 486 debug2: channel 0: input drain -> closed
2232 12:30:38 486 debug2: on_select - io:00F7BC38 type:1 rd:1
2232 12:30:38 486 debug2: on_select - io:00F7BC38 type:1 rd:0
2232 12:30:38 486 debug1: zombie'ing child at index 0, 0 zombies of 1
2232 12:30:38 486 debug1: raise sig:3
2232 12:30:38 486 debug2: signal() sig:3, handler:00AC0890
2232 12:30:38 486 debug2: write - io:00F5CF00
2232 12:30:38 486 debug2: ReadCB pio:00F7BCB8, pending_state:1, error:0, received:1
2232 12:30:38 486 debug2: WriteCB - pio:00F5CF00, pending_state:1, error:0, transferred:1 of remaining: 1
2232 12:30:38 486 debug2: write - reporting 1 bytes written, io:00F5CF00
2232 12:30:38 486 debug1: process_queued_signals: WARNING - A signal has interrupted and was processed
2232 12:30:38 486 debug1: Received SIGCHLD.
2232 12:30:38 486 debug1: Unregister child at index 0, 1 zombies of 1
2232 12:30:38 486 debug1: session_by_pid: pid 1524
2232 12:30:38 486 debug1: session_exit_message: session 0 channel 0 pid 1524
2232 12:30:38 486 debug2: channel 0: request exit-status confirm 0
2232 12:30:38 486 debug1: session_exit_message: release channel 0
2232 12:30:38 486 debug2: channel 0: send close
2232 12:30:38 486 debug2: on_select - io:00F7BC38 type:1 rd:1
2232 12:30:38 486 debug2: on_select - io:00F7BC38 type:1 rd:0
2232 12:30:38 486 debug2: read - io:00F7BCB8 read: 1 remaining: 0
2232 12:30:38 486 debug2: notify_done: reading
2232 12:30:38 486 debug2: ReadFileEx io:00F7BCB8
2232 12:30:38 486 debug2: read - IO is pending, io:00F7BCB8
2232 12:30:38 486 debug2: send - io:00F7BC38
2232 12:30:38 486 debug2: send - WSASend() returned 0, APC scheduled io:00F7BC38
2232 12:30:38 486 debug2: WSASendCB - io:00F7BC38, pending_state:1, error:0, sent:140 of remaining:140
2232 12:30:38 486 debug2: on_select - io:00F7BC38 type:1 rd:1
2232 12:30:38 502 debug2: WSARecvCompletionCB - io:00F7BC38, pending_state:1, flags:0, error:0, received:36
2232 12:30:38 502 debug2: recv - returning 36 bytes from prior completed IO, remaining:0, io:00F7BC38
2232 12:30:38 502 debug2: channel 0: rcvd close
2232 12:30:38 502 debug2: channel 0: is dead
2232 12:30:38 502 debug2: channel 0: gc: notify user
2232 12:30:38 502 debug1: session_by_channel: session 0 channel 0
2232 12:30:38 502 debug1: session_close_by_channel: channel 0 child 0
2232 12:30:38 502 Close session: user [user] from [ipaddress] port [port] id 0
2232 12:30:38 502 debug2: channel 0: gc: user detached
2232 12:30:38 502 debug2: channel 0: is dead
2232 12:30:38 502 debug2: channel 0: garbage collecting
2232 12:30:38 502 debug1: channel 0: free: server-session, nchannels 1
2232 12:30:38 502 debug2: on_select - io:00F7BC38 type:1 rd:1
2232 12:30:38 502 debug2: WSARecv - reported IO pending
2232 12:30:38 517 debug2: WSARecvCompletionCB - io:00F7BC38, pending_state:1, flags:0, error:0, received:84
2232 12:30:38 517 debug2: recv - returning 84 bytes from prior completed IO, remaining:0, io:00F7BC38
2232 12:30:38 517 Received disconnect from [ipaddress] port [port]: Closed due to user request.
2232 12:30:38 517 Disconnected from user [user] [ipaddress] port [port]
~~~

The error seems to be originating from here: https://github.com/PowerShell/Win32-OpenSSH/blob/L1-Prod/channels.c#L2835.

**Comment by manojampalam** [comment] 2017-03-22 21:05
Can you provide a practical user example? It seems that this is an issue within OpenSSH core source itself as the Windows fork doesn't have any special handling around channel message processing

**Comment by imayobrown** [comment] 2017-03-23 01:07
We ran into this issue in conjunction with the [trilead-ssh2](https://github.com/jenkinsci/trilead-ssh2) library used by Jenkins. We were trying to facilitate master -> Windows slave connections through ssh. The specific client code from the library that generates this error is here: https://github.com/jenkinsci/trilead-ssh2/blob/master/src/com/trilead/ssh2/Connection.java#L1550.

It seems that the cause is not the way the channel messages are processed but rather the way the child exec processes are spawned (which seems to have slightly different logic between the forks). The channel doesn't seem to notice that child process spawned by one of its dispatchers is still executing and has not returned anything into the output buffer yet. https://github.com/PowerShell/Win32-OpenSSH/blob/L1-Prod/session.c#L455

I will try to see if I can provide a lighter weight example for reproduction.

**Comment by maertendMSFT** [comment] 2020-03-31 21:06
Closing as we cannot reproduce.

Feel free to reopen if this occurs in the latest release.

**Closed as completed by maertendMSFT** 2020-03-31 21:06 UTC
Labels: Resolution - No Repro
