### ISSUE TITLE
Mouse Events Support for Win32 console applications

### ISSUE THREAD

**Issue by nkrepo** [PowerShell/Win32-OpenSSH#1863] opened 2021-11-25 17:43 UTC
**"OpenSSH for Windows" version**
8.6.0.0
 
**Server OperatingSystem**
OS Name	Microsoft Windows 11 Pro
Version	10.0.22000 Build 22000

**Client OperatingSystem**
OS Name	Microsoft Windows 11 Pro
Version	10.0.22000 Build 22000

**What is failing**
Mouse events in native Win32 console applications
(far manager, micro, e.t.c)

**Expected output**
Mouse events send over ssh to the Win32 console application

**Actual output**
No mouse events pass-through

That is a different issue from #1158  
*The conhost.exe version is 10.0.22000.348

**Comment by tgauth** [comment] 2022-01-07 22:23
@nkrepo, the root cause of this issue is ConPTY. It currently does not support converting VT mouse events into Windows mouse events. The good news is that the console team recently worked on this, and it will be in the next full update version of Windows.

For additional context, please see this GitHub issue: [https://github.com/microsoft/terminal/issues/376](https://github.com/microsoft/terminal/issues/376)

To validate, I reproduced your issue with an OpenSSH server OS version: Windows 11 (with conhost.exe version 10.0.22000.194) then verified that the Windows 11 preview I have currently (with conhost.exe version 10.0.22523.1000) does fix it.

**Comment by bagajjal** [comment] 2022-01-10 23:14
@tgauth - please follow up.

**Comment by tgauth** [comment] 2022-02-04 17:40
@nkrepo - can this be closed? Looks like your conhost.exe version, 10.0.22000.348, is similar to the one I repro'd the issue with.
If the issue persists with a newer version, at least 10.0.22523.1000, then it can be re-opened.

**Comment by nkrepo** [comment] 2022-02-04 18:19
> @nkrepo - can this be closed? Looks like your conhost.exe version, 10.0.22000.348, is similar to the one I repro'd the issue with. If the issue persists with a newer version, at least 10.0.22523.1000, then it can be re-opened.

it is OK to close.

**Closed as completed** 2022-02-04 20:07 UTC
