### ISSUE TITLE
Error ssh-copy-id

### ISSUE THREAD

**Issue by uPagge** [PowerShell/Win32-OpenSSH#1731] opened 2021-01-27 11:19 UTC
Hello

I can log in with a password, but when I try to copy the shh key, the following error occurs.

Your project is the latest version of Windows Server 2012 (64 bit)

![photo_2021-01-27_14-17-18](https://user-images.githubusercontent.com/40397740/105984021-9c6c9280-60aa-11eb-9f04-529642b32432.jpg)

**Comment by bagajjal** [comment] 2021-01-27 17:58
@uPagge - Win32-OpenSSH doesn't support the ssh-copy-id.
ssh-copy-id in contrib folder is from linux openssh repo. It's bash script and it doesn't understand the semantics of win32-openssh.

Duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1467

**Closed as completed by bagajjal** 2021-01-27 17:58 UTC

**Comment by uPagge** [comment] 2021-01-27 18:15
@bagajjal And then how can you do ssh authorization? manually adding to .ssh / authorized_keys doesn't help either.

**Comment by bagajjal** [comment] 2021-01-27 18:28
@uPagge - Please refer to https://github.com/PowerShell/Win32-OpenSSH/wiki/Setup-public-key-based-authentication-for-windows

**Comment by uPagge** [comment] 2021-01-28 05:44
Thanks a lot, it seems to work :)
