### ISSUE TITLE
Bash(WLS) from cmd.exe or as default shell fails with 0x80070005

### ISSUE THREAD

**Issue by lejeczek** [PowerShell/Win32-OpenSSH#1069] opened 2018-02-09 16:20 UTC
**"OpenSSH for Windows" version**
 v0.0.24.0
**Server OperatingSystem**
 v0.0.24.0
**Client OperatingSystem**
Centos 7
**What is failing**

Being sshed into cmd.exe when I try to run bash/wsl:

>bash                                                                      
Error: 0x80070005                                                                                    
Press any key to continue... 

**Expected output**
Would be nice, great actually to have bash work and/or as the default shell.

**Actual output**

**Comment by bagajjal** [comment] 2018-02-09 18:29
Duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/289

Closing this as its a bash issue.

**Closed as completed by bagajjal** 2018-02-09 18:29 UTC
