### ISSUE TITLE
When using PublicKeyAuthentication the user seems to be not really AD authenticated

### ISSUE THREAD

**Issue by khx71** [PowerShell/Win32-OpenSSH#1049] opened 2018-01-31 14:08 UTC
**"OpenSSH for Windows" version**
1.0.0.0
 
**Server OperatingSystem**
Windows Server 2012 R2 Standard

**Client OperatingSystem**
Linux RHEL 6 ( Patchlevel 7 )

On LINUX I am compiling a batch script that I scp over to Windows and execute there using ssh in the next setp. In the beginning I do link in network drives such as shown in the code fragment below

touch $WIN_CMD_FILE

echo "c:" >> $WIN_CMD_FILE
echo "net use B: \\\\SERVER\\vol001\$" >> $WIN_CMD_FILE
echo "net use Y: \\\\SERVER\\vol003\$" >> $WIN_CMD_FILE
echo "call B:\env.bat" >> $WIN_CMD_FILE
echo "mkdir %TEMP%\\$WIN_TMP_DIR" >> $WIN_CMD_FILE
...
scp $WIN_CMD_FILE $WINDOWS_SERVICE_USER@$WINDOWS_SERVER_IP:AppData/Local/Temp/win_$TIMESTAMP.bat
ssh $WINDOWS_SERVICE_USER@$WINDOWS_SERVER_IP cd AppData/Local/Temp \& call win_$TIMESTAMP.bat
...

This works perfectly as long as I interactively provide the script with the password of the $WINDOWS_SERVICE_USER during runtime. My plan is not to do this 24/7 but to schedule this task in crontab and so my next step was to enable PublicKeyAuthentication. However as soon as placed the pub file in the right place and restarted sshd it started failing connecting the network drive with the following two lines:

The password is invalid for \\SERVER\vol001$.
Enter the user name for 'SERVER': System error 1223 has occurred.

The user is exactly the same, it had permissions to connect the drive before. When I use the $WINDOWS_SERVICE_USER and log into the SERVER I can link the network drive. Same positive result if I execute the batch file created on the SERVER interactively.

So I wonder if the session is any different when conncted with PublicKeyAuthentication from when connected interactively. Can this be configured somewhere in sshd_config? Is that something that needs to be set in the user setup? In fact I am not giving a password during login to the sesssion ... but shouldn't the user still have permissions to do the same things once it has a valid session?

Any hint is very welcome. Cheers.

**Comment by manojampalam** [comment] 2018-01-31 16:57
Check if this helps https://github.com/PowerShell/Win32-OpenSSH/issues/518

**Comment by khx71** [comment] 2018-02-01 07:46
Hi there

thank you for the quote. It doesn't help (as you stated this is a security feature of Windows) but explains ;). I meanwhile worked around the issue disabling PKA and specifying the Password in every call using 

sshpass -f <(printf '%s\n' $WINDOWS_PASSWORD) ssh $WINDOWS_SERVICE_USER@$WINDOWS_SERVER_IP

Regards

**Comment by manojampalam** [comment] 2018-02-01 17:28
Thanks. Just learnt about sshpass. We would need a Windows version of this in the near future to automate non-interactive password based logons.

**Comment by maertendMSFT** [comment] 2020-04-14 21:08
Dupe of https://github.com/PowerShell/Win32-OpenSSH/issues/1047

**Closed as completed by maertendMSFT** 2020-04-14 21:08 UTC
Labels: Resolution - Duplicate, Issue-Question
