### ISSUE TITLE
Getting “System error 1067” when trying to start OpenSSH service

### ISSUE THREAD

**Issue by ParatrooperJoe** [PowerShell/Win32-OpenSSH#1271] opened 2018-10-12 20:37 UTC
**Server OperatingSystem**
Windows Server 2012 R2 Standard

**What is failing**
Open SSH Service will not load

**Expected output**
Open SSh Service starts succesfully

**Actual output**

Windows Could not start the OpenSSH SSH Server service on Local Computer.

Error 1067: The process terminated unexpectedly.

I am logged in as a Domain Admin, just FYI...

**Comment by highpointacademy** [comment] 2018-10-13 01:00
So that only confuses me even more.

I do not understand why this is so hard to get going?

Guess i am ging to just have to find a 3rd party tool to accomplish this.... SFTP setup should not cause this much trouble

**Comment by bagajjal** [comment] 2018-10-15 17:51
closing this as it's a duplicate of #1272

**Closed as completed by bagajjal** 2018-10-15 17:51 UTC
