### ISSUE TITLE
"Permission denied (publickey,password,keyboard-interactive)."

### ISSUE THREAD

**Issue by yooakim** [PowerShell/Win32-OpenSSH#1358] opened 2019-03-28 17:08 UTC
**"OpenSSH for Windows" version**
 `7.7.2.1`
 
**Server OperatingSystem**
 `Windows Server 2019 Datacenter`

**Client OperatingSystem**
`Windows 10 Pro`

**What is failing**

I can connect to the Windows Server 2019 (domain joined) 

- [ ] from Windows 10 client via Internet `ssh  -v username@ip`  DOES NOT WORK
- [x] from Windows 10 using WinSCP.exe WORKS 
- [x] from Ubuntu WSL `ssh jsw@fqdn` WORKS
- [x] locally in the server `ssh username@localhost` WORKS 
- [x] from Ubuntu `ssh jsw@fqdn` WORKS

**Expected output**
Successful login

**Actual output**
`username@ip: Permission denied (publickey,password,keyboard-interactive).`

The only client that fails is the ssh.exe from Windows 10. Can anyone help me find out why? Here's the ssh log:

```
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\yooak/.ssh/config
debug1: C:\\Users\\yooak/.ssh/config line 1: Applying options for *
debug1: Connecting to 40.118.103.34 [40.118.103.34] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\yooak/.ssh/id_rsa type 0
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\yooak/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\yooak/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\yooak/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\yooak/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\yooak/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\yooak/.ssh/id_ed25519 type 3
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\yooak/.ssh/id_ed25519-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\yooak/.ssh/id_xmss type -1
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\yooak/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.7
debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 40.118.103.34:22 as 'june'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:yPNwoYDrXFsygNKZjuFjbOcpiV6UkXkq6KFeNCyJ7lg
debug1: Host '40.118.103.34' is known and matches the ECDSA host key.
debug1: Found key in C:\\Users\\yooak/.ssh/known_hosts:38
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:S3gDtopWHfXlLhUNWCc89/x4eXOXIZVsNd3rgtyLHk4 C:\\Users\\yooak/.ssh/id_rsa
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Offering public key: ED25519 SHA256:ZyLjH5uIMN14F/QkeOA2yFMM3J9CY87ytOybLQ2YbLw C:\\Users\\yooak/.ssh/id_ed25519
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Trying private key: C:\\Users\\yooak/.ssh/id_dsa
debug1: Trying private key: C:\\Users\\yooak/.ssh/id_ecdsa
debug1: Trying private key: C:\\Users\\yooak/.ssh/id_xmss
debug1: No more authentication methods to try.
june@40.118.103.34: Permission denied (publickey,password,keyboard-interactive).
```

**Comment by manojampalam** [comment] 2019-03-28 18:00
Please share server side logs. See https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

Did you expect one of the public keys to work ? If you have give too many invalid key identities for the client to try (ex. you have a bunch of keys registered with ssh-agent that aren't valid for the target you are connecting to), you'll see that the server will reject the connection after 3 failed authentication attempts. This is by design

**Comment by yooakim** [comment] 2019-03-28 18:21
> 
> 
> Please share server side logs. See https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps
> 
> Did you expect one of the public keys to work ? If you have give too many invalid key identities for the client to try (ex. you have a bunch of keys registered with ssh-agent that aren't valid for the target you are connecting to), you'll see that the server will reject the connection after 3 failed authentication attempts. This is by design

I have two keys so the number of keys is likely not the issue. The strange thing, I think, is that it works fine from other SSH clients (WinSCP, ssh in WSL etc) but not the Windows ssh client.

**Comment by agrawalsmart7** [comment] 2019-04-18 09:31
Same here! see this issue that I have been created. https://github.com/PowerShell/Win32-OpenSSH/issues/1369

**Comment by Liuly-liuly** [comment] 2019-05-29 06:58
i have the same question: who can solve this porblem?
    the log ### 

Permission denied (publickey,keyboard-interactive).

fowllowing my config  : the pc is Windows server 2012 
   
# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

Port 22
#AddressFamily any
ListenAddress 10.151.1.84
#ListenAddress ::

#HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

PubkeyAuthentication yes
RSAAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile  __PROGRAMDATA__/ssh/authorized_keys

#AuthorizedPrincipalsFile none

# For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication no
#PermitEmptyPasswords no

# GSSAPI options
#GSSAPIAuthentication no

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# override default of no subsystems
Subsystem	sftp	sftp-server.exe

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server

# Match Group administrators
#       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys

**Comment by Liuly-liuly** [comment] 2019-05-29 07:27
I have a solution ：
   the sshd_config : 
          
#LoginGraceTime 2m
#PermitRootLogin prohibit-password
StrictModes no
#MaxAuthTries 6
#MaxSessions 10

the StrictModes set the value no and uncoment the # 
finally you can ssh the windows server

**Comment by allmazz** [comment] 2020-05-23 21:39
> I have a solution ：
> the sshd_config :
> 
> #LoginGraceTime 2m
> #PermitRootLogin prohibit-password
> StrictModes no
> #MaxAuthTries 6
> #MaxSessions 10
> 
> the StrictModes set the value no and uncoment the #
> finally you can ssh the windows server

It's work for me. Thanks!

**Comment by maertendMSFT** [comment] 2020-05-26 21:19
Can you please share your client and server side logs? See manojampalam's comment above.

**Comment by margish-mpc** [comment] 2020-05-28 14:16
> I have a solution ：
> the sshd_config :
> 
> #LoginGraceTime 2m
> #PermitRootLogin prohibit-password
> StrictModes no
> #MaxAuthTries 6
> #MaxSessions 10
> 
> the StrictModes set the value no and uncoment the #
> finally you can ssh the windows server

how i can edit this ?

**Comment by KiruyaMomochi** [comment] 2020-06-07 19:55
From https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH#administrators_authorized_keys:
```powershell
PS C:\>icacls administrators_authorized_keys /inheritance:r
PS C:\>icacls administrators_authorized_keys /grant SYSTEM:`(F`)
PS C:\>icacls administrators_authorized_keys /grant BUILTIN\Administrators:`(F`)
```

**Comment by bagajjal** [comment] 2020-06-08 17:25
Closing this issue as it's expected for admin users to store the public keys in $env:programdata\ss\administrators_authorized_keys file. This file should have right permissions.

**Closed as completed by bagajjal** 2020-06-08 17:25 UTC
Labels: Issue-Discussion-Deprecated/use GitHub discussions

**Comment by emhacker** [comment] 2020-12-27 14:18
What are the right permissions for this file?

**Comment by arebee** [comment] 2020-12-28 20:33
> What are the right permissions for this file?

https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH#administrators_authorized_keys

and https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement on using the Powershell utility to achieve the same.

**Comment by bladetin** [comment] 2021-12-26 12:31
> I have a solution ： the sshd_config :
> 
> #LoginGraceTime 2m #PermitRootLogin prohibit-password StrictModes no #MaxAuthTries 6 #MaxSessions 10
> 
> the StrictModes set the value no and uncoment the # finally you can ssh the windows server

大佬！！！牛逼！！！

**Comment by Liuly-liuly** [comment] 2021-12-26 12:32
时间过期不接受。

**Comment by orihomie** [comment] 2022-02-09 06:03
Still facing same issue, none of the guides helped me.

**Comment by bagajjal** [comment] 2022-02-09 17:51
@orihomie - Please create a new issue. You get permission denied in so many ways. 
Don't forget to attach the ssh client logs (ssh -vvv user@ip) and the [ssh server logs](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities)

**Comment by sntgchns** [comment] 2022-08-20 18:11
> I have a solution ： the sshd_config :
> 
> #LoginGraceTime 2m #PermitRootLogin prohibit-password StrictModes no #MaxAuthTries 6 #MaxSessions 10
> 
> the StrictModes set the value no and uncoment the # finally you can ssh the windows server

Thankyou! I love you ❤️😁

**Comment by Liuly-liuly** [comment] 2022-08-20 18:11
时间过期不接受。

**Comment by ankushbhagatofficial** [comment] 2023-08-03 14:18
> **"OpenSSH for Windows" version** `7.7.2.1`
> 
> **Server OperatingSystem** `Windows Server 2019 Datacenter`
> 
> **Client OperatingSystem** `Windows 10 Pro`
> 
> **What is failing**
> 
> I can connect to the Windows Server 2019 (domain joined)
> 
> * [ ]  from Windows 10 client via Internet `ssh  -v username@ip`  DOES NOT WORK
> * [x]  from Windows 10 using WinSCP.exe WORKS
> * [x]  from Ubuntu WSL `ssh jsw@fqdn` WORKS
> * [x]  locally in the server `ssh username@localhost` WORKS
> * [x]  from Ubuntu `ssh jsw@fqdn` WORKS
> 
> **Expected output** Successful login
> 
> **Actual output** `username@ip: Permission denied (publickey,password,keyboard-interactive).`
> 
> The only client that fails is the ssh.exe from Windows 10. Can anyone help me find out why? Here's the ssh log:
> 
> ```
> OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
> debug1: Reading configuration data C:\\Users\\yooak/.ssh/config
> debug1: C:\\Users\\yooak/.ssh/config line 1: Applying options for *
> debug1: Connecting to 40.118.103.34 [40.118.103.34] port 22.
> debug1: Connection established.
> debug1: identity file C:\\Users\\yooak/.ssh/id_rsa type 0
> debug1: key_load_public: No such file or directory
> debug1: identity file C:\\Users\\yooak/.ssh/id_rsa-cert type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file C:\\Users\\yooak/.ssh/id_dsa type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file C:\\Users\\yooak/.ssh/id_dsa-cert type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file C:\\Users\\yooak/.ssh/id_ecdsa type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file C:\\Users\\yooak/.ssh/id_ecdsa-cert type -1
> debug1: identity file C:\\Users\\yooak/.ssh/id_ed25519 type 3
> debug1: key_load_public: No such file or directory
> debug1: identity file C:\\Users\\yooak/.ssh/id_ed25519-cert type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file C:\\Users\\yooak/.ssh/id_xmss type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file C:\\Users\\yooak/.ssh/id_xmss-cert type -1
> debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
> debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.7
> debug1: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
> debug1: Authenticating to 40.118.103.34:22 as 'june'
> debug1: SSH2_MSG_KEXINIT sent
> debug1: SSH2_MSG_KEXINIT received
> debug1: kex: algorithm: curve25519-sha256
> debug1: kex: host key algorithm: ecdsa-sha2-nistp256
> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:yPNwoYDrXFsygNKZjuFjbOcpiV6UkXkq6KFeNCyJ7lg
> debug1: Host '40.118.103.34' is known and matches the ECDSA host key.
> debug1: Found key in C:\\Users\\yooak/.ssh/known_hosts:38
> debug1: rekey after 134217728 blocks
> debug1: SSH2_MSG_NEWKEYS sent
> debug1: expecting SSH2_MSG_NEWKEYS
> debug1: SSH2_MSG_NEWKEYS received
> debug1: rekey after 134217728 blocks
> debug1: SSH2_MSG_EXT_INFO received
> debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
> debug1: SSH2_MSG_SERVICE_ACCEPT received
> debug1: Authentications that can continue: publickey,password,keyboard-interactive
> debug1: Next authentication method: publickey
> debug1: Offering public key: RSA SHA256:S3gDtopWHfXlLhUNWCc89/x4eXOXIZVsNd3rgtyLHk4 C:\\Users\\yooak/.ssh/id_rsa
> debug1: Authentications that can continue: publickey,password,keyboard-interactive
> debug1: Offering public key: ED25519 SHA256:ZyLjH5uIMN14F/QkeOA2yFMM3J9CY87ytOybLQ2YbLw C:\\Users\\yooak/.ssh/id_ed25519
> debug1: Authentications that can continue: publickey,password,keyboard-interactive
> debug1: Trying private key: C:\\Users\\yooak/.ssh/id_dsa
> debug1: Trying private key: C:\\Users\\yooak/.ssh/id_ecdsa
> debug1: Trying private key: C:\\Users\\yooak/.ssh/id_xmss
> debug1: No more authentication methods to try.
> june@40.118.103.34: Permission denied (publickey,password,keyboard-interactive).
> ```

Just comment these two lines, thank me later

> file source: C:\ProgramData\ssh\sshd_config

```
#Match Group administrators
# AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

**Comment by Liuly-liuly** [comment] 2023-08-03 14:18
时间过期不接受。

**Comment by ekramyelnaggar** [comment] 2023-09-11 14:40
Solved, I did the following : 
1- Edited the sshd_config file as follows:  PasswordAuthentication yes
2- Restarted the "OpenSSH SSH Server" Service

and it worked fine

**Comment by Liuly-liuly** [comment] 2023-09-11 14:40
时间过期不接受。

**Comment by zeroepix** [comment] 2024-04-16 07:15
> > file source: C:\ProgramData\ssh\sshd_config
> 
> ```
> #Match Group administrators
> # AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
> ```

If this works, it's because windows is looking for you in that file but your public key isn't in there. I assume because it recognized your first key as an administrator but I haven't tested it with a non-administrator account.

The other solution, is to copy your pubkeys to C:\ProgramData\ssh\administrators_authorized_keys, and that should work too.

**Comment by Liuly-liuly** [comment] 2024-04-16 07:16
时间过期不接受。
