### ISSUE TITLE
ssh is unable to bind to a specific local IPv6 address with BindAddress

### ISSUE THREAD

**Issue by anthonyvdotbe** [PowerShell/Win32-OpenSSH#1514] opened 2019-12-06 12:39 UTC
**"OpenSSH for Windows" version**
7.7.2.2

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
In ~/.ssh/config, I specified an IPv6 address as the argument to the `BindAddress` option, so something like:
````
Host foo.bar.com
    BindAddress <a-specific-local-ipv6-address>
````

**Expected output**
I'd expect ssh to be able to bind to the local IPv6 address

**Actual output**
````
PS> ssh foo.bar.com
debug2: resolving "foo.bar.com" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to foo.bar.com [<remote-ipv6-address>] port 22.
debug1: ssh_create_socket: bound to <local-ipv6-address-as-specified-in-config>
debug3: connectex - ERROR: bind failed :10022, io:00000235083EFFF0
debug1: connect to address <remote-ipv6-address> port 22: Invalid argument
ssh: connect to host foo.bar.com port 22: Invalid argument
````

**Comment by metaltank** [comment] 2020-03-19 20:41
Were you able to resolve this? I'm encountering the exact same issue. Best I can tell it is an issue with the WSAEINVAL error of the bind function:

"An invalid argument was supplied.This error is returned of the socket s is already bound to an address."

https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-bind

**Comment by anthonyvdotbe** [comment] 2020-03-20 06:22
@metaltank no I wasn't

**Comment by smokeintheshell** [comment] 2020-06-11 16:22
@manojampalam can you or your team provide an update on this issue? issue still persists

**Comment by maertendMSFT** [comment] 2020-07-17 17:12
This is an duplicate of: https://github.com/PowerShell/Win32-OpenSSH/issues/1442
This is in our backlog.

**Closed as completed by maertendMSFT** 2020-07-17 17:12 UTC
Labels: Resolution - Duplicate

**Comment by gurpreetshanky** [comment] 2020-10-26 16:24
@maertendMSFT Any news regarding this?
