### ISSUE TITLE
sftp put and get commands differs from Unix variant

### ISSUE THREAD

**Issue by eperede** [PowerShell/Win32-OpenSSH#396] opened 2016-11-03 16:09 UTC
Hello developers,

we have noticed a difference between the sftp.exe's "put" and "get" commands in the Win32/Win64 OpenSSH and Unix/Linux OpenSSH.
So the reproduction of the issue.
1. Logging in to a remote host with "sftp.exe".
2.    a. get source_filename target_filename
      b. put source_filename target_filename.
In the target_fiename parameters we always only have a filename, never including a directory path.
But it seems that Win32/Win64 OpenSSH does not handle specifying a new name for the target file, and always handles the target_filename as a folder in which is trying to create the file with the same name as the source file.
Example of error message:

sftp> put -P E6A0F6BB91A7EFF180E700155D0BF17D 201611011757209790000_SE1K999998.temp
remote open("/home/spftp01/201611011757209790000_SE1K999998.temp/E6A0F6BB91A7EFF180E700155D0BF17D "): No such file or directory#
Authorized uses only. All activity may be monitored and reported.

In Linux/AIX OpenSSH the put and get command works as expected and renames the file at the target_filename. We think that it's a "bug".
Could you please check it and fix?

Thank you in advance!

**Comment by bagajjal** [comment] 2016-12-03 00:12
Thanks for reporting this issue. We have identified the root cause. It will be fixed in the next release

**Comment by bagajjal** [comment] 2016-12-19 18:42
Fixed in milestone release

**Closed as completed by bagajjal** 2016-12-19 18:42 UTC
Labels: Issue-Bug, Area-SFTP
