### ISSUE TITLE
msi package does not install a service to verify

### ISSUE THREAD

**Issue by userdocs** [PowerShell/Win32-OpenSSH#1913] opened 2022-03-18 20:14 UTC
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`

```
PS C:\> ((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)
8.9.0.0
```
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

Windows 10 Pro

**Client OperatingSystem**

Windows 11 Pro

**What is failing**

When using the wiki to install via the msi package the step to check the service status only returns a result if i have install openssh 8.1 via the windows app features.

```
PS C:\> Get-Service -Name ssh*
PS C:\>
```

https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI#3-verify-openssh-install

**Expected output**

The msi install to create the service. I assume this is what I am looking to verify.

If the apps and features / option openssh server is removed the check will not verify anything as there is no servive

**Actual output**

The mis install and linked wiki page do not seem to provide the desired result

Am i missing something? I have installed the msi as admin and it is in my path and working but there is no service. The only thing that seems to make sense is that a step is missing?

I assumed i was not meant to be checking the service of the other installation?

**Comment by bagajjal** [comment] 2022-03-18 22:01
@userdocs - I couldn't reproduce. Please look at the video recording

https://user-images.githubusercontent.com/23668037/159090480-fb40882f-bf52-4dd7-a6b2-f3536128ab82.mp4

.

**Comment by userdocs** [comment] 2022-03-18 22:06
Thanks for the reply but i'm a little confused.

The msi installs the client and the server to 

![image](https://user-images.githubusercontent.com/16525024/159090836-03da24a0-46de-4424-be21-08df914c95bd.png)

If i use just the msi installer there is no service and i am following the instructions in the wiki

So is it a prerequisite that i must have the client installed to system32 via the add features?

**Comment by bagajjal** [comment] 2022-03-18 22:10
You don't need the client installed. My intention was to show win32-openssh server is not installed prior to MSI installation.

Can you look under "Services"
![image](https://user-images.githubusercontent.com/23668037/159091271-f5824638-78e0-4276-864c-61996ccbef1a.png)

**Comment by userdocs** [comment] 2022-03-18 22:18
It's not there. I have installed the msi in various ways,

powershell/cmd with and without admin

`msiexec /i C:\OpenSSH-x64-v8.9.msi`

And  by double clicking.

I can use the binaries in the command line but there is some weird issue with the services.

IS there a way to debug the install?

**Comment by bagajjal** [comment] 2022-03-18 22:39
See if this helps,
 msiexec.exe /i C:\OpenSSH-x64-v8.9.msi /L*V "C:\opensshmsi.log"

**Comment by userdocs** [comment] 2022-03-18 22:40
OK, i tried on 3 devices.

Desktop windows 11 pro + WSL2 + windows virtual machine platform.

Laptop windows 10 pro + WSL2 + windows virtual machine platform.

Laptop windows 11 pro no special features.

It's working normally on the last machine but misbehaving on the two with WSL.

It prompted to elevate the installer in the third machine but it does not do that on the other two.

I'll try that log thing.

**Comment by bagajjal** [comment] 2022-03-18 23:13
@userdocs I'm not sure. I uinstall the openssh. Install the WSL and then install the openssh again. I see the services listed.

@heaths - Do you have any pointers on how to debug the issue?

**Comment by userdocs** [comment] 2022-03-19 00:05
Is the installer supposed to prompt for elevated perms to install the services?

**Comment by bagajjal** [comment] 2022-03-19 00:07
@heaths implemented the MSI. In my case, as you see in the video, it didn't prompt for the elevated perms.
@heaths please help.

**Comment by userdocs** [comment] 2022-03-19 01:40
No matter how many times in installed it it would not do the service but I saw the repair option and that seems to have worked.

![dunno](https://user-images.githubusercontent.com/16525024/159101807-c0434eac-d982-470b-a717-ce20f7acbf09.png)

**Comment by userdocs** [comment] 2022-03-19 13:18
So the repair option worked on both devices.

I think that would be a good enough solution for the wiki should that step not verify a service was installed, for whatever possible reason.

Right click the msi and use the repair option.

The reason for the failure to install the services is not known but repeatedly installing does not fix it only maybe removal (did not try) and repairing.

So maybe we can leave this here incase it happens to others but i'd think having the method to repair/remove the msi via the right click context menu would be a helpful self help step in the wiki.

I'll let you decide whether to leave it open or not.

**Comment by bagajjal** [comment] 2022-03-21 17:05
@userdocs - That's interesting. Thanks for trying all the options and providing a workaround for community. Yes, we can have the issue open. We tried on 4 machines (windows 10 x64, windows 10 x86, windows server 2019) but couldn't reproduce. 
Any idea what could have caused this issue.

**Comment by userdocs** [comment] 2022-03-21 17:42
I think I understand what happens and how to reproduce it.

If you are starting from a clean setup this should reproduce it.

1: Install openssh client and server via Window apps and features. (8.1) and services will be added

2: Install msi and add path

3: Remove openssh via apps and features leaving the msi installed

4: check the services `Get-Service -Name ssh` they will be removed and not present

5: install msi again and there will be no UAC prompt. It will just quickly complete the installation.

7: check the services `Get-Service -Name ssh` they will be removed and not present

There will be no UAC  prompt nor a service installed until you repair or remove the MSI.

So it appears a bug related to already having openssh installed via Windows apps and features. When I first installed I had the server installed.

**Comment by heaths** [comment] 2022-03-21 18:36
> Is the installer supposed to prompt for elevated perms to install the services?

@userdocs yes, elevation is required to install services, copy files to non-user directories, etc. This is true of any installer. If you're installing from an already-elevated prompt then there's no need to prompt to elevate again because the client (msiexec.exe) was already started elevated and doesn't need to elevate again when passing off control to the service (msiexec.exe /v).

The MSI uses built-in functionality to install services. Why having WSL installed makes a difference I honestly don't know. I have WSL2 enabled (and did when I wrote and tested this) and the service installed fine.

It would help if you produced a diagnostics log to review:

```bash
msiexec /i <msi> /L*vx install.log
```

Apart from your computer name, user name, and domain name (if AD-joined, not AAD-joined or not even in a domain) there should be no PII, but you're welcome to review it before uploading in a comment on this issue (please do not copy and paste as these logs can be huge).

**Comment by userdocs** [comment] 2022-03-21 19:06
@heaths if you focus on my last comment the issue was due to me having the features installed and removing them after the msi installation which removes the services and they can't be replaced by installing again but repairing.

Not sure if that is a bug per say or a qwerk of how an msi works but that is a the reproducible problem I encountered. It not WSL related.

**Comment by heaths** [comment] 2022-03-21 19:57
Ah, yes, the operating system packages (CBS) take precedent over MSI, so if you remove the features afterward those protected packages and their files will be removed regardless of what MSI thinks. Repairing the MSIs (`msiexec /fvomus {msi}`) should restore them.

**Comment by bagajjal** [comment] 2022-03-21 20:06
@heaths, I'm curious why the operating system doesn't allow registering the services in this flow.

1) openssh server installed through the optional features.
2) MSI is installed.
3) openssh optional feature is removed. Service is unregistered here. This is expected.
4) MSI is uninstalled.
5) MSI is installed again. At this point, we should see the service registered again? But OS doesn't register service.. Only MSI repair  does.

**Comment by heaths** [comment] 2022-03-21 20:11
I would need to see a logs of the uninstall and re-install attempt, but I suspect it's because MSI thinks the component is already installed. Repairing - with the right options like "omus" at the very least - ignore some of the ref-counting "magic" and reinstall files anyway. "pecmsu" is generally safer repair options and the default for MSIs if not defined otherwise, but slower for large products like Visual Studio (which uses very few MSIs these days).

Note: by default, MSI's component-based ref-counting is based on information it stores in the registry and not what files or registry values are installed, hence why simply re-installing the MSI won't re-copy the service registration that CBS removed when you disable the Windows feature.

A potential fix would be to register a separate service, though I don't know how the CBS- and MSI-installed daemons would coexist. That would have to be solved at the service implementation level such as listening to a different port by default or something.

**Comment by userdocs** [comment] 2022-03-21 20:22
Now I understand what happened and the steps above should reproduce the same result anywhere I guess a note in the wiki would work well enough to explain the solution to repair if you removed the feature after installation.

Instead of being like me and just trying to install it various ways, not realising how the problem was created by the order I did things.

**Comment by bagajjal** [comment] 2022-03-21 22:36
@userdocs - I'm closing this issue as there is nothing to fix.

**Closed as completed by bagajjal** 2022-03-21 22:36 UTC
