### ISSUE TITLE
NO sshd service shown in Windows Service

### ISSUE THREAD

**Issue by yuessir** [PowerShell/Win32-OpenSSH#1340] opened 2019-02-13 08:58 UTC
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps
>.\install-sshd.ps1
successfully installed
>..\ssh-keygen.exe 

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
v7.9.0.0p1-Beta
 
**Server OperatingSystem**
Hyper-V　Win server 2012R2

**Client OperatingSystem**
Win 10
**What is failing**

**Expected output**
sshd service shown in Windows Service
**Actual output**
NO sshd service shown in Windows Service

**Comment by j4munoz** [comment] 2019-02-16 15:52
It appears as "OpenSSH SSH Server":

![image](https://user-images.githubusercontent.com/19351560/52902029-424ecb80-320b-11e9-960a-1c120bf53496.png)

**Comment by NoMoreFood** [comment] 2019-02-16 22:28
@j4munoz is certainly correct. The short name for the service is actually 'sshd' so you can use that in some scenarios:

![image](https://user-images.githubusercontent.com/12881023/52905945-3b768780-3210-11e9-86a1-c990c9184a37.png)

Please close this issue if these answers satisfy your question.

**Comment by manojampalam** [comment] 2019-02-17 01:23
Please reopen if you feel necessary.

**Closed as completed by manojampalam** 2019-02-17 01:23 UTC

**Comment by SarKaa** [comment] 2020-07-14 16:28
I think this is a bit late, over a year :), but I can't find the service either. Its not in services.msc or powershell

**Comment by bagajjal** [comment] 2020-07-14 17:22
@SarKaa - Did you install openssh through windows optional feature or through github release? 
Please follow https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH for github releases.

Please open a new issue as the root cause can be different.

**Comment by yuessir** [comment] 2020-07-15 04:34
@SarKaa Try it again,to install the service to your remote server.
![圖片](https://user-images.githubusercontent.com/8326310/87503730-8875bc00-c697-11ea-98b6-625e2ac0e9d0.png)

**Comment by Haiahemmohamed** [comment] 2021-03-04 17:38
Where is the prob?

![image](https://user-images.githubusercontent.com/50952857/110005417-bee07400-7d18-11eb-961f-5075dfe6c5c0.png)

**Comment by bagajjal** [comment] 2021-03-04 21:57
Error 1067 means "The process terminated unexpectedly.".
It's hard to say why just by looking at the error log.

Are you running in an elevated powershell window? Do you have any changes to $env:programdata\ssh\sshd_config? 
What happens when you try ".\sshd.exe -ddd"?

**Comment by bagajjal** [comment] 2021-03-04 21:58
Please open a new issue as yours is a different issue.

**Comment by izharsaeed1** [comment] 2023-11-20 05:49
Please try rebooting OS after installing/enabling openssh server on the windows. For me it is working on one VM after reboot.
![image](https://github.com/PowerShell/Win32-OpenSSH/assets/151497981/1c06439e-0071-449d-898c-c0feddbf5b0f)
![image](https://github.com/PowerShell/Win32-OpenSSH/assets/151497981/84989db5-33e7-48ea-a617-06cdec4fa37e)

**Comment by izharsaeed1** [comment] 2023-11-20 06:02
OK got it working on the other Windows also. Just disabled the openssh authentication agent if it is running and then uninstall and reinstall the openssh SSH server followed by reboot. This should show the openssh SSH server on windows services.
![image](https://github.com/PowerShell/Win32-OpenSSH/assets/151497981/d72a5b05-53f7-4b5f-aac6-6f85161cbff0)
