### ISSUE TITLE
SSH HomeDirectory, CHROOT on Windows

### ISSUE THREAD

**Issue by derhoeppi** [PowerShell/Win32-OpenSSH#292] opened 2016-08-17 12:36 UTC
Is it possible to change the home directory of a user? 

I have some devices they could not use a full path, so i have to use the home directory.

**Comment by manojampalam** [comment] 2016-09-12 19:44
Please clarify. An example helps.

**Comment by EchBTI** [comment] 2016-09-19 12:27
I've done something similar where I wanted a user to login and put files in a specific directory, I followed MS article to change user profile directory via Regedit, you have to have at least logged in with the user once to create the required reg key, then you can change it. 

All has worked quite well. The only thing I haven't yet figured out is how to lock down the ability to then navigate out of that directory. 

EE

**Comment by EchBTI** [comment] 2016-09-19 12:28
FYI - http://www.nextofwindows.com/how-to-change-user-profile-default-location-in-windows-7

**Comment by manojampalam** [comment] 2016-09-19 18:08
_The only thing I haven't yet figured out is how to lock down the ability to then navigate out of that directory._ 
That would be chroot on Windows. Since this is not supported by OS itself, I guess it cannot be accurately implemented in Windows.

**Comment by Janareddy** [comment] 2016-12-26 13:36
Hi, Is there a way to implement directory lock (chroot) in windows?

**Comment by Bob-O-Rama** [comment] 2017-05-26 17:14
"That would be chroot on Windows. Since this is not supported by OS itself, I guess it cannot be accurately implemented in Windows."   

To be honest, I normally do not complain about FOSS functionality, because, after all, its a community project and as one of the bottom feeders benefiting from their good graces, I have little to complain about.   However with SFTP, which is to improve the security of file transfers, even calling this SFTP is criminal.   Being able to jail the user to a given folder or home folder is not a roadmap feature, it absence is a blocker to release.    This is an incredibly reckless hobbling of security features available in SFTP implementations on other platforms.

**Comment by SallyJohnson** [comment] 2017-10-24 11:07
I don't know how this software can get any sort of MS "sign off" https://blogs.msdn.microsoft.com/powershell/2015/10/19/openssh-for-windows-update/
It would appear that chroot is something that is not being aimed for in the first release, if at all (info gained from this and other forums). Without a chroot, its like a system admin sharing the C: drive with full share permissions on a windows file server, and saying "its okay, users can only WRITE to their home directories" .  I'm less sure about the terminal side of this, but it all seems very niche and a lot of effort for something that can be easily achieved by other mechanisms. But then again perhaps I am not appreciating why "openssh" is something of particular importance.

**Comment by whereisaaron** [comment] 2018-01-29 22:14
Third-party Windows ssh/sftp server implementations do provide chroot-equivalent functionality for sftp folder access. They basically validate the sftp commands to prevent access outside the 'chroot' folder. MS would need to implement or agree to something similar for OpenSSH, or add process jail support to Windows.

I investigated using Windows/NTFS file permissions to achieve a similar result, but the problem is that Windows gives very broad permissions to 'Authenticated Users' to the whole file system by default, impacting even system accounts. You can change those, but who know what will break throughout Windows if you do. And it is doubtful MS or vendors ever test their software with other than this permissive default 😞

**Comment by NoMoreFood** [comment] 2018-02-28 12:31
@whereisaaron Do you know which third party implementations provide this?  The think the tough part of this is handling the Linux-equivalent behavior where chroot() that affects child processes.  Even if this project did something to override/detour NtOpenFile/NtCreateFile, an uploaded executable from the user could be used to break free of the jail by overriding-the-override.  You could get even more extreme by filtering at the kernel by checking at ZwCreateFile/ZwOpenFile level but I believe that would require driver injection.  Unless the third party process implements something like this, I'm skeptical that it could be implemented securely.

Now I think an SFTP server without shell access could probably jail the user since there are no child processes to worry about and a limited set of functions that access the file system.  I could look into doing this, but I think I'd want the maintainer to tell me there's a chance in hell of it getting merged before I went down that road.

**Comment by whereisaaron** [comment] 2018-02-28 16:40
@NoMoreFood I was thinking of two products in particular. The [Microsoft FTP Server](https://docs.microsoft.com/en-us/iis/publish/using-the-ftp-service/configuring-ftp-user-isolation-in-iis-7), which provide chroot-like behaviour for FTP access. And the [Bitvise SSH/SFTP server](https://www.bitvise.com/securing-ssh-server) which also provides chroot-like behaviour, definitely for sftp (which is what I've used it for), and for 'ssh' it is supported if you use the 'BvShell', which is a restricted access/ability shell.

I agree it is hard to see how to handle this for ssh sessions and child processes in general, unless ssh sessions are jailed in a kernel-level wrapper, like e.g. a Windows container. Which is no trivial addition to the OpenSSH code base! :smile:

While filesystem jails are nice-to-have for ssh shells, that are IMHO an essential feature for sftp. In fact we evaluated Win32 OpenSSH for sftp and decided against it purely over this missing capability.

Bitvise chroot-like support:
> Limiting directory access
> By default, Bitvise SSH Server permits each user to access any and all parts of the filesystem that Windows filesystem permissions allow them access to. Frequently, you want to limit users to be able to access only a particular directory. Note, however, that it is only secure to impose such restrictions if you have also followed instructions above and disabled access to port forwarding and shell access (except BvShell).
> 
> Filesystem access is controlled:
> 
> In Easy settings, under the Virtual filesystem layout section of each account settings entry.
> In Advanced settings, under the File transfer section of each group and account settings entry.
> If you are using Easy settings, make sure the Virtual filesystem layout settings are configured securely for each user.
> 
> If you are using Advanced settings:
> 
> Open File transfer > Mount points for the Everyone group, edit the default mount point ("/"), and set the Real root path to point to an innocuous, empty directory. Or, if all your users should have access to the same folder, you can configure this to point to that directory.
> 
> In per-account settings, you can configure a different set of mount points for each user. Under Virtual filesystem layout settings for the user, disable the Use default layout checkbox. Then configure the Real root path for the default mount point ("/") to specify the directory which you want this user to access.
> 
> You can configure multiple mount points in this way, permitting the user to access a selected number of server directories. You can also use mount point permission settings to allow the user to only read, but not write to, files in a particular directory.

**Comment by manojampalam** [comment] 2018-03-08 19:03
@NoMoreFood 

About
`Now I think an SFTP server without shell access could probably jail the user since there are no child processes to worry about and a limited set of functions that access the file system. I could look into doing this, but I think I'd want the maintainer to tell me there's a chance in hell of it getting merged before I went down that road.`

Can you elaborate? What does "SFTP server without shell access" mean on Windows? We dont spawn any children from sftp-server.exe.

**Comment by whereisaaron** [comment] 2018-03-09 03:59
@manojampalam @NoMoreFood means that when you connect you are only able to access sftp and not `bash` or another general shell (with which the user could create child processes). You can use `ForceCommand` for this, or you can change the user's shell to `sftp-server`.

```
Subsystem sftp internal-sftp

Match Group users
    AllowTCPForwarding no
    X11Forwarding no
    ForceCommand internal-sftp
    ChrootDirectory /var/sftp/incoming
```

If the sftp server enforces the `ChrootDirectory` on its commands (or has that limitation externally enforced on the process) then this is functionally the same as a Linux chroot-ed sftp. Since user can't create child processes, they can't bypass that limited access.

**Comment by NoMoreFood** [comment] 2018-03-13 00:09
@manojampalam Yeah, my general idea here is that one set a global when calling chroot() and then put a check at the beginning of file I/O operations to make sure the real path of the specified path is within that global.  If it's not then return the appropriate error.  If we wanted to avoid the check at the file operation, we could detour NtCreateFile/NtOpenFile when calling chroot(), but that might get messy with Detours licensing (although I imagine you guys could work something out internally).  That would probably work with SFTP since the file operations are controllable.  Short of a complicated kernel-level filter driver, I don't think there's much hope for a reliable chroot() for general terminal access.

**Comment by NoMoreFood** [comment] 2018-03-21 23:57
I was experimenting and managed to implement a decent jail by intercepting NtCreateFile, NtOpenFile, and NtQueryFullAttributesFile and making sure any files were within a specified path.  I did this by modifying the IAT of kernel32.dll (kernelbase.dll) at runtime which is what all the normal file I/O functions flow through one way or another.  So, basically you call a function from the sftp_server_main() and it implements this jail -- pretty simple.  I didn't have to use the Detours library since it was just a simple IAT modification.   For context, it'd be about 250 lines of code.

While I believe this is reliable from a security perspective, the "ugly" part is that normally the chroot() is controlled by the parent process (sshd.exe) and sftp-server.exe is just an executable inherits the new root; no information about the custom root path is actually passed to sftp-server.exe so it really has no idea its running in a jail.  So in order to implement something like within SFTP specifically, we'd probably need to read sshd_config in sftp_server_main() to get the new root information (sftp-server.exe does not appear read sshd_config at all right now), or pass a new command line parameter to sftp-server.exe, or allow some sort of special path prefix the passed provided by -d to indicate that it should implement a jail (e.g. -d C:\MyDir|CHROOT).

The "cleanest" approach would probably be the special command line parameter that we'd #ifdef in for Windows, but I'm not sure that'd be "acceptable" for an upstream merge?  Thoughts?

**Comment by NoMoreFood** [comment] 2018-03-22 00:09
Actually, thinking about it more, another way to pass the information would be to have SSHD embed the root path information in an environment variable and then have the SFTP server key off that environment variable.  That would keep us out of the "main" SFTP files.  Regardless, curious what @manojampalam and @bagajjal are interested in something like this. I suspect it'll be a demanded feature but my proposed solution is somewhat novel.

**Comment by manojampalam** [comment] 2018-03-23 00:20
If its just a matter of providing chroot functionality for sftp (and trusting existing sftp code), we could do it somewhat simpler:
 - as part of chroot() - set an environment variable (as you suggested)
 - write a validation method that tests input string against chroot'ed path (if set). 
 - modify all file IO entry points (we pretty much over load of these APIs in posix compat layer for Unicode differences), run input path(s) against the above validation routine.
 - modify dirent APIs to respect chroot'ed path.

**Comment by manojampalam** [comment] 2018-05-11 21:04
FYI, we have changes in pipeline to support SFTP with chroot
https://github.com/PowerShell/openssh-portable/pull/308

**Closed as completed** 2018-05-30 05:26 UTC
Labels: Issue-Discussion-Deprecated/use GitHub discussions
