### ISSUE TITLE
-J failed with "posix_spawn: No such file or directory"

### ISSUE THREAD

**Issue by zcattacz** [PowerShell/Win32-OpenSSH#1711] opened 2020-12-01 13:52 UTC
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

Add `ProxyJump` $SomeOtherHost  to ~/.ssh/config or pass `-J` switch when calling ssh.exe

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
7.7.2.2 

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
N/A

**Client OperatingSystem**
Win10 x64 Enterprise

**What is failing**

**Expected output**

   user@host~#

**Actual output**

    C:\Users\Administrator\.ssh>ssh router3
    CreateProcessW failed error:2
    posix_spawn: No such file or directory

**Comment by mgkuhn** [comment] 2020-12-03 11:57
Duplicate of #1172 and fixed in [current release 8.1](https://github.com/PowerShell/openssh-portable/releases/tag/v8.1.0.0)?

**Comment by matso42** [comment] 2022-11-25 11:40
@maertendMSFT 
Please close since fixed

**Closed as completed** 2022-11-26 06:27 UTC
