### ISSUE TITLE
Ctrl+C terminate ssh client.

### ISSUE THREAD

**Issue by mfilippov** [PowerShell/Win32-OpenSSH#26] opened 2015-10-24 08:24 UTC
When I press Ctrl+C for terminate command in ssh session ssh client was terminated.

**Comment by yuribank** [comment] 2015-10-24 08:58
I noticed the same thing. It seems the client is intercepting SIGINT in a way that it should not.

**Comment by diogocp** [comment] 2015-10-26 14:21
Duplicate of #20.

**Comment by manojampalam** [comment] 2015-10-27 16:51
See above for duplicate issue link.

**Closed by manojampalam** 2015-10-27 16:51 UTC
