### ISSUE TITLE
ssh -vvv help needed 

### ISSUE THREAD

**Issue by DaburLal** [PowerShell/Win32-OpenSSH#984] opened 2017-12-07 09:24 UTC
As i am trying to secure my VNC session using OpenSSH, i needed some help with ssh -vvv part.

Using the command `ssh -vvv w21821@10.31.128.23 -L 7934:10.31.128.23:5900
` i have been able to establish a tunnel 

> 
  C:\Users\w21821>netstat -aon | find ":7934"
  TCP    127.0.0.1:7934         0.0.0.0:0              ABHÖREN         5488
  TCP    [::1]:7934                     [::]:0                 ABHÖREN         5488

After pinging my vnc Viewer on 127.0.0.1:7934, i get 

> 
C:\Users\w21821>netstat -aon | find ":7934"
  TCP    127.0.0.1:7934              0.0.0.0:0                ABHÖREN         4676
  TCP    127.0.0.1:7934         127.0.0.1:65501         HERGESTELLT    4676
  TCP    127.0.0.1:65501        127.0.0.1:7934          HERGESTELLT    7028
  TCP    [::1]:7934                        [::]:0                      ABHÖREN        4676

This established Connection is not going through the tunnel.

Following is my debug Report

> 
w21821@STGT-8RLG95J C:\Users\w21821>debug1: Connection to port 7934 forwarding t

o 10.31.128.23 port 5900 requested.
debug2: fd 10 setting TCP_NODELAY
debug2: fd 10 setting O_NONBLOCK
debug3: fd 10 is O_NONBLOCK
debug1: channel 3: new [direct-tcpip]
debug3: send packet: type 90
debug3: receive packet: type 91
debug2: channel 3: open confirm rwindow 2097152 rmax 32768
debug1: Connection to port 7934 forwarding to 10.31.128.23 port 5900 requested.
debug2: fd 11 setting TCP_NODELAY
debug2: fd 11 setting O_NONBLOCK
debug3: fd 11 is O_NONBLOCK
debug1: channel 4: new [direct-tcpip]
debug3: send packet: type 90
debug3: receive packet: type 91
debug2: channel 4: open confirm rwindow 2097152 rmax 32768
debug2: channel 4: window 1989208 sent adjust 107944
debug2: channel 4: window 1996620 sent adjust 100532
debug2: channel 4: window 1993138 sent adjust 104014
debug2: channel 4: window 1997202 sent adjust 99950
debug2: channel 4: window 1993618 sent adjust 103534
debug2: channel 4: window 1996986 sent adjust 100166
debug3: recv - from CB ERROR:10054, io:00000000003F28D0
debug2: channel 3: read<=0 rfd 10 len 4294967295
debug2: channel 3: read failed
debug2: channel 3: close_read
debug2: channel 3: input open -> drain
debug2: channel 3: ibuf empty
debug2: channel 3: send eof
debug3: send packet: type 96
debug2: channel 3: input drain -> closed
debug3: receive packet: type 96
debug2: channel 3: rcvd eof
debug2: channel 3: output open -> drain
debug2: channel 3: obuf empty
debug2: channel 3: close_write
debug2: channel 3: output drain -> closed
debug3: receive packet: type 97
debug2: channel 3: rcvd close
debug3: channel 3: will not send data after close
debug2: channel 3: send close
debug3: send packet: type 97
debug2: channel 3: is dead
debug2: channel 3: garbage collecting
debug1: channel 3: free: direct-tcpip: listening port 7934 for 10.31.128.23 port

 5900, connect from 127.0.0.1 port 49224 to 127.0.0.1 port 7934, nchannels 5
debug3: channel 3: status: The following connections are open:
  #2 client-session (t4 r0 i0/0 o0/0 fd 7/8 cc -1)
  #3 direct-tcpip: listening port 7934 for 10.31.128.23 port 5900, connect from

127.0.0.1 port 49224 to 127.0.0.1 port 7934 (t4 r1 i3/0 o3/0 fd 10/10 cc -1)
  #4 direct-tcpip: listening port 7934 for 10.31.128.23 port 5900, connect from

127.0.0.1 port 49225 to 127.0.0.1 port 7934 (t4 r2 i0/0 o0/0 fd 11/11 cc -1)

Can someone guide me is there anything wrong found in this debug or what else can i do to proceed?

Thanks!!

**Comment by maertendMSFT** [comment] 2020-04-07 21:27
Duplicate of: https://github.com/PowerShell/Win32-OpenSSH/issues/979

**Closed as completed by maertendMSFT** 2020-04-07 21:27 UTC
Labels: Resolution - Duplicate, Issue-Question
