### ISSUE TITLE
resizing ssh.exe not working

### ISSUE THREAD

**Issue by elijahgagne** [PowerShell/Win32-OpenSSH#1039] opened 2018-01-27 19:38 UTC
**"OpenSSH for Windows" version**
1.0.0.0

**Server OperatingSystem**
Not relevant, any Linux server

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
Resizing the ssh.exe window does not work. I believe this is causing issues when trying to use ssh.exe with ConEmu and using "[screen](https://www.gnu.org/software/screen/manual/screen.html)" on the Linux target server. 

**Expected output**
The window should work normally. Here's what it looks like when I keep the window small.
![ssh exe2](https://user-images.githubusercontent.com/2213005/35475582-214f4b6a-036f-11e8-8f35-0af5968e634b.gif)

**Actual output**
![ssh exe1](https://user-images.githubusercontent.com/2213005/35475428-511e8ff2-036c-11e8-9310-8ac914f75807.gif)

I believe this might be related to the fact that ssh.exe does not handle being resized.
![ssh exe3](https://user-images.githubusercontent.com/2213005/35475587-32ac8288-036f-11e8-93ac-10ce1f8b92d9.gif)

We have issues on re-sizing when running from cmd.exe as well
![ssh exe4](https://user-images.githubusercontent.com/2213005/35475593-4707c42c-036f-11e8-9410-0efec04d262f.gif)

**Comment by bagajjal** [comment] 2018-01-29 21:49
@elijahgagne - This is expected behavior because of a bug in conhost.exe.

ssh client uses conhost.exe (provided by windows OS) to interpret the ANSI sequences. When we resize ssh client windows, the conhost.exe writes the data to a different location as the viewport changes. To mitigate this, we restore the window back so restore will get lost.

I have also raised a bug against conhost team.

Also updated known issues in https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH.

**Comment by elijahgagne** [comment] 2018-01-29 23:56
Thanks for all that! If there's a way I can get notified when the conhost bug gets fixed, I'd love to sign up for that. But I understand if that's not possible.

**Comment by bagajjal** [comment] 2018-01-30 01:17
Unfortunately it's  not possible as conhost bugs are internal to Microsoft. We will update our [wiki page ](https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH) periodically.

**Comment by idvorkin** [comment] 2018-08-26 12:47
I'm still experiencing this bug, so I'm assuming it's still open.  Any reason not to keep this bug open so users can track the issue being resolved?  Also, how can users provide input to the conhost team?

**Comment by Gonkers** [comment] 2018-10-14 06:01
I second what @idvorkin says. I'm having the issue on my work laptop as well as my home PC. I'd love to submit diagnostic data if it will help resolve the issue faster.

**Comment by elijahgagne** [comment] 2018-10-14 14:50
@bagajjal would you consider re-opening this until the bug is fixed?

**Comment by ClusterM** [comment] 2019-07-22 08:38
@bagajjal But it can detect current window size somehow. It can't handle resize event only. So maybe just check current size periodically?

**Comment by BinaryVixen899** [comment] 2019-08-30 00:11
@bagajjal  Yeah this is a really glaring and annoying bug, would also appreciate it being fixed. Understand that since it's internal it is really hard and also not the OpenSSH team's issue since it is conhost but, yeah. Thank you for keeping this open! :)

**Comment by maertendMSFT** [comment] 2020-04-07 21:59
This should be fixed in the latest Win10, if you still see this issue, please reopen.
This is not supported down-level

**Closed as completed by maertendMSFT** 2020-04-07 21:59 UTC
Labels: Resolution - Fixed
