### ISSUE TITLE
scp command not using -P option

### ISSUE THREAD

**Issue by marchrock** [PowerShell/Win32-OpenSSH#111] opened 2016-02-14 13:42 UTC
```
scp -P xxxxx localfile username@yyy.yyy.yyy.yyy:
```

will start trying to connect port 22 not xxxxx that designated by -P option and fails.

**Comment by jemiller0** [comment] 2016-06-01 16:25
I just downloaded OpenSSH-Win64.zip yesterday and there's no scp.exe in it. Any ideas why?

**Comment by richmondwang** [comment] 2016-06-16 02:42
@jemiller0 see my [comment](https://github.com/PowerShell/Win32-OpenSSH/issues/237#issuecomment-226370976) maybe it will help

**Comment by JayPearlman** [comment] 2016-06-16 04:16
From https://github.com/PowerShell/Win32-OpenSSH/releases/tag/3_19_2016

"SCP is taken offline as it needs significant changes to get it on board the new transpor and I'm still working on it."

**Comment by darkblaze69** [comment] 2016-10-21 13:10
since scp is now generally working with v0.0.1.0, it is still not accepting port parameter - tries to connect via default 22 :

C:\Users\user>scp -v -P 57002 -S ssh .ssh\id_rsa.pub root@machine1:
Executing: host machine1, user root, command scp -v -t .
OpenSSH_7.1p1 Microsoft_Win32_port_with_VS, OpenSSL 1.0.2d 9 Jul 2015
debug1: Connecting to machine1 [192.168.1.253] port 22.
debug1: socket:440, io:00000000004D6A60, fd:3

**Comment by arif-pragmasys** [comment] 2016-12-27 21:43
@marchrock and @darkblaze69, -P option worked for me in the latest build. Can you please check if you can reproduce it?

**Comment by ghost** [comment] 2016-12-28 15:20
Thank you!
In the latest build, -P option worked fine for me too.
For me, it's ok to close this issue.

**Comment by bingbing8** [comment] 2017-01-04 18:18
close per marchrock's comments.

**Closed** 2017-01-05 21:26 UTC
Labels: Area-SCP, Issue-Bug
