### ISSUE TITLE
AzureAD only domain sshd: fatal: ga_init, unable to resolve user azuread\\foo

### ISSUE THREAD

**Issue by zippy1981** [PowerShell/Win32-OpenSSH#1756] opened 2021-03-20 22:00 UTC
I'm hoping this is a special case of #1053

**Troubleshooting steps**

I did a fresh install of windows 10 and joined it to the domain zippysoft.us. This domain only exists as an AzureAD tenant it lacks:

* domain controllers
* AD connect
* Azure Domain Services

I tried `ssh localhost` and got `sshd: fatal: ga_init, unable to resolve user azuread\\justindearing` in the opsnssh admin logs.

I tried `ssh -l jdearing@zippysoft.us localhost` and got `sshd: Failed password for invalid user jdearing@zippysoft.us from ::1 port 50634 ssh2` in the operationj logs

Creating a user with `nety user /add` allowed me to ssh just fine as a locak user

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
7.7.2.3
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 pro

**Client OperatingSystem**
Windows 10 pro

**What is failing**
I can't ssh in az an azureAd user

**Expected output**
A ssh session

**Actual output**
Not an ssh session

**Comment by bagajjal** [comment] 2021-03-22 17:03
SSH using AzureAD credentials is not supported. This requires changes in the windows OS.

**Comment by bagajjal** [comment] 2021-03-22 17:03
Duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1543

**Closed as completed by bagajjal** 2021-03-22 17:03 UTC
Labels: Resolution - Answered
