### ISSUE TITLE
Wrong CR/LF behavior in ssh.exe

### ISSUE THREAD

**Issue by DmitryDonetsky** [PowerShell/Win32-OpenSSH#1256] opened 2018-09-25 13:46 UTC
**"OpenSSH for Windows" version**
7.7.2.0

**Server OperatingSystem**
FreeBSD 10.4-RELEASE amd64
TERM=cons25r

**Client OperatingSystem**
Windows 7 x64 russian
TERM=cons25r

**What is failing**
CR worked as CR+LF, LF are ignored. This leads to multiple output issues in my case.

Background:
The server assumes the historical behavior of the terminal, in which it works as mechanical teletype or typewriter.
One or more of CR should cause the mechanical carriage will be move to the position of the first character of the same line, without scrolling the paper.
Each LF should cause the paper to scroll to the next line, without moving the carriage to anywhere.

**Expected output**
Server sends `0x0d 0x0d 0x0a` and prompt, each time you press Return:
![sc1](https://user-images.githubusercontent.com/43574636/46017239-b1524900-c0df-11e8-90fd-116bda3bb848.jpg)

On exit from Midnight Commander, server sends `0x1b 0x5b 0x4b 0x0a` 20+ times, for line by line screen cleaning and move cursor to last line:
![sc3](https://user-images.githubusercontent.com/43574636/46017247-badbb100-c0df-11e8-8093-e8b3fb5df8b3.jpg)

**Actual output**
Unwanted blank lines:
![sc2](https://user-images.githubusercontent.com/43574636/46017258-c038fb80-c0df-11e8-9c08-755922ffe3f5.jpg)

The screen is not cleared, prompt is in the second line from upper end:
![sc4](https://user-images.githubusercontent.com/43574636/46017272-c4fdaf80-c0df-11e8-84fe-3a058feddd56.jpg)

**Comment by dpsenner** [comment] 2019-02-08 15:15
I'm observing an issue that appears to be related to this one when connecting to a linux machine from windows in a powershell console. I.e. after starting the powershell.exe I observe "user@some-host" to be duplicated on the same line:

```shell
PS D:\Workspace> ssh some-host
user@some-host:~$ clear
user@some-host:~$ user@some-host:~$ echo "hello"
hello
user@some-host:~$ clear
user@some-host:~$ user@some-host:~$ <enter>
user@some-host:~$ <enter>
user@some-host:~$ lsb_release -r
Release:        18.04
user@some-host:~$ man clear
(hit <q>)
user@some-host:~$ user@some-host:~$ 
```

It appears that the way how `clear` and `man` attempt to clear the screen does not work out well when done from an ssh shell started in a powershell.

Noteworthy, too, is that with the `user@some-host:~$ user@some-host:~$ ` printed it is enough to resize the powershell window to restore it such that it displays `user@some-host:~$ `, i.e. by grabbing it with the mouse and increasing or decreasing the width by one column. Decreasing the powershell windows' height does not help, though.

**Comment by vsalvino** [comment] 2019-03-02 22:47
I am also seeing the exact issue that dpsenner reported above. Issue is the same regardless of using any combination of CMD, PowerShell 5.1, or PowerShell 6.1 with Win32-OpenSSH client 7.7 or 7.9.

Also interesting, but probably unrelated, is that ssh.exe seems to always change the cursor size to "small" even it if it set as "large" in PowerShell.

**Comment by maertendMSFT** [comment] 2020-07-16 18:49
@DHowett-MSFT , this appears to be a console issue, can you take a look?

**Comment by DHowett** [comment] 2020-08-24 17:21
This probably has the same root cause as the login/motd duplication issue that was fixed in https://github.com/PowerShell/openssh-portable/pull/426.

**Comment by DHowett** [comment] 2020-08-24 17:24
Sorry, I was reading the comments https://github.com/PowerShell/Win32-OpenSSH/issues/1256#issuecomment-461835397 and https://github.com/PowerShell/Win32-OpenSSH/issues/1256#issuecomment-468967880 which are off-topic for this issue. 😬 

This `cons25r` is not something that I have ever seen, and I do not expect that it has the right terminfo/termcap behavior for the Windows Console.

At the same time, when Win32-OpenSSH is running _on windows 7_, it does a significant amount of preprocessing before sending output to the console. I'd start debugging there :smile:

**Comment by bagajjal** [comment] 2021-03-30 21:08
For Windows 7, we support only VT100. 
From windows10, we have full xterm support from the windows console team.

We are not investing to fix bugs in VT100.

**Closed as completed by bagajjal** 2021-03-30 21:08 UTC
Labels: Issue-Bug, 0 - Backlog, Resolution - Won't Fix, Area-Terminal
