### ISSUE TITLE
Console output mangled upon reaching scroll

### ISSUE THREAD

**Issue by erichiller** [PowerShell/Win32-OpenSSH#938] opened 2017-11-02 16:37 UTC
I'm using Powershell inside ConEmu client side, but I've tried the same set of attempts in vanilla `cmd.exe`

I ran through [TTY-PTY-support-in-Windows-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH) and made sure I:
- tried both cmd.exe and ConEmu
- set `$env:term="xterm"` // `set term=xterm` respectively and ensured it was set on the connected to server session as well with `%term%` and ensuring I receive `xterm` back
- set `$env:SSH_TERM_CONHOST_PARSER=0` // `set SSH_TERM_CONHOST_PARSER=0`

**Server Side**
```
OpenSSH_7.6p1, LibreSSL 2.5.3
```
```
# Script module or binary module file associated with this manifest
ModuleToProcess = 'OpenSSHUtils.psm1'

# Version number of this module.
ModuleVersion = '1.0.0.1'
 ```

**Server OperatingSystem**: Windows 10 Pro, 15063.674 (Build 1703)

**Client OperatingSystem**: Windows 10 Pro, 14393.1770 (Build 1607)

**What is failing**: Terminal output is extremely mangled _once the screen edge is reached and scroll has occurred_. I actually didn't even realize that it took this to occur until writing this report. Of course my first thought is something with the scrollback buffer, but my settings are in accordance with the wiki:
![image](https://user-images.githubusercontent.com/5379325/32338030-d95e51d6-bfb0-11e7-998c-839c5db462a7.png)

_and when using conemu side_
![image](https://user-images.githubusercontent.com/5379325/32338066-f4950a44-bfb0-11e7-8842-9120c47061e1.png)
![image](https://user-images.githubusercontent.com/5379325/32338206-539cd788-bfb1-11e7-94da-82edb754fe3e.png)

**Expected output**:
![image](https://user-images.githubusercontent.com/5379325/32337901-78be36a2-bfb0-11e7-9b76-cea7e93dc96c.png)

**Actual output**
![image](https://user-images.githubusercontent.com/5379325/32337953-9d96d632-bfb0-11e7-9fb4-5d20b17c5cbc.png)

**Comment by JonathanHolvey** [comment] 2018-02-08 10:31
I've also experiencing this problem with extra lines in the output, as well as extra whitespace being printed between input characters, when connecting to a OpenSSH-Win32 server on Windows 7:

![screenshot_20180208-071339](https://user-images.githubusercontent.com/10114731/35965563-0ad661a6-0d07-11e8-8880-da4a025257de.png)

These clients I've had success with:

- OpenSSH-Win32 in `cmd.exe` or ConEmu on Windows
- GNU OpenSSH in Terminal on Ubuntu

These clients have problems:

- GNU OpenSSH in `cmd.exe` or ConEmu on Windows
- JuiceSSH on Android

**Comment by bagajjal** [comment] 2018-02-09 20:11
@JonathanHolvey - Did you check your "Screen Buffer width and Window Size" > 90.
please go through https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH.

What win32-openssh version are you using? Is it repro all the time?

**Comment by JonathanHolvey** [comment] 2018-02-10 09:28
Yeah, I did read through that wiki page before posting. Everything seems to be in order, however the issue persisted. I was running Win32-OpenSSH version 1.0.0.2018.02.02.

In the end I removed Win32-OpenSSH (after forcibly removing the sshd service), and installed [MSYS2](http://www.msys2.org/), configuring the sshd server using [this script](https://gist.github.com/samhocevar/00eec26d9e9988d080ac) instead. This works well for me since I work with Linux a lot and use Bash as my shell on Windows.

**Comment by dwatley** [comment] 2018-02-17 01:21
@bagajjal Just want to add I can reproduce this as well.

Server: OpenSSH-Win64 v1.0.0.0
Client: Windows 10 1709, ssh.exe included with git from [Git SCM](https://git-scm.com/): OpenSSH_7.6p1, OpenSSL 1.0.2l  25 May 2017

Did the xterm, buffer settings and SSH_TERM_CONHOST_PARSER bits. Can easily reproduce it every single session. Not an issue in PuTTY or [Chrome SSH App](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo?hl=en). Happy to help debug. Should also note that this doesn't affect the ssh.exe included with OpenSSH-Win64.

Output:

![console_issue](https://user-images.githubusercontent.com/2055181/36336474-ecf2e4d4-133c-11e8-983d-02679546997b.png)

**Comment by bagajjal** [comment] 2018-02-23 02:07
@dwatley - ssh.exe included with git doesn't run.

![image](https://user-images.githubusercontent.com/23668037/36574569-258b7384-17fb-11e8-98d7-9ac333392d9d.png)

This might be a git ssh.exe problem as it's not seen on putty, Chrome SSH App and OpenSSH-Win64.

**Comment by dwatley** [comment] 2018-02-23 02:25
@bagajjal Works for me...

```
C:\Program Files\Git\usr\bin>.\ssh.exe -V
OpenSSH_7.3p1, OpenSSL 1.0.2j  26 Sep 2016
```

Multiple people have reported the issue, I think it may be cygwin based ssh builds potentially?

**Comment by JonathanHolvey** [comment] 2018-02-23 07:49
JuiceSSH has the same issue when connecting to a Win32-OpenSSH server, so it's not just cygwin.

**Comment by dwatley** [comment] 2018-04-05 15:22
@bagajjal - Are you still having trouble reproducing this?

**Comment by dwatley** [comment] 2018-10-05 00:02
@bingbing8 @bagajjal - Ping again. Is this in line for next release or is it not yet reproducible for you?

**Comment by bagajjal** [comment] 2018-10-05 00:12
@dwatley - Starting from [windows 10 October 2018 update](https://support.microsoft.com/en-us/help/4028685/windows-10-get-the-update), we are going to use conpty supported provided by the Microsoft console team at server side. A bunch of serverside console rendering issues will be resolved including this.

Having said that, we still need to investigate this for down level OS. Fix for downlevel OS is not aimed for next release.

**Comment by bagajjal** [comment] 2019-12-18 07:54
This should be fixed by now in windows 10.
For windows 10 below, we provide only basic support.

**Closed as completed by bagajjal** 2019-12-18 07:54 UTC
Labels: Issue-Bug, Area-Terminal
