### ISSUE TITLE
ssh does not respect -f or -n to go to the background, hangs on ^C

### ISSUE THREAD

**Issue by DHowett-MSFT** [PowerShell/Win32-OpenSSH#1241] opened 2018-08-31 17:57 UTC
Please answer the following

**"OpenSSH for Windows" version**
`7.6.0.0` -  `7.7.2.1`
 
**Server OperatingSystem**
Doesn't matter.

**Client OperatingSystem**
RS3 - RS5; doesn't seem to matter.

**What is failing**
`ssh -fNn username@server`

Invoked like this, ssh _should_:
* go into the background

**Expected output**

```
(dhowett-dev) C:\WINDOWS\system32\WindowsPowerShell\v1.0 % ssh -fNn dustin@xxxxxx
(dhowett-dev) C:\WINDOWS\system32\WindowsPowerShell\v1.0 %
^ prompt returns because ssh is backgrounded
```

**Actual output**

ssh keeps running and takes over the console session. It can't be killed with `^C`.
If port forwards were enabled, they _still work_ -- ssh is operating properly, it just won't enter the background.

**Comment by manojampalam** [comment] 2018-09-06 19:24
Thanks. ssh background support is not in yet. 
It should bail out right away with an error message instead.

**Comment by maertendMSFT** [comment] 2020-07-16 18:45
Closing as a dupe of: https://github.com/PowerShell/Win32-OpenSSH/issues/999

Both require a background implementation

**Closed as completed by maertendMSFT** 2020-07-16 18:45 UTC
Labels: Issue-Bug, Resolution - Duplicate, 0 - Backlog, Area-ssh
