### ISSUE TITLE
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)

### ISSUE THREAD

**Issue by waleedhammam** [PowerShell/Win32-OpenSSH#1585] opened 2020-04-14 10:08 UTC
**"OpenSSH for Windows" version**
 `7.7.2.2`
 
**Client OperatingSystem**
Windows 10 Pro v1909. Build 18363.720

**What is failing**
Can't connect to ssh machines

**Expected output**
Connection works ok with my current key and directs me to the machine

**Actual output**
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)

**Comment by bagajjal** [comment] 2020-04-14 17:19
Duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1263

**Closed as completed** 2020-04-14 17:18 UTC
