### ISSUE TITLE
Weird behavior under certain programs

### ISSUE THREAD

**Issue by Mayhem93** [PowerShell/Win32-OpenSSH#848] opened 2017-08-18 14:08 UTC
Please answer the following

**If it is a terminal issue then please go through wiki
It is a terminal issue, but not entirely related to that TTY/xterm/etc issue (I was aware of that for a few months now).

**"OpenSSH for Windows" version**
 0.0.18.0
 
**Server OperatingSystem**
```
$cat /proc/version
Linux version 4.4.0-53-generic (buildd@lcy01-28) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
```

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
Entering a new line (and possible other escape characters) in a certain program (redis-cli in my example) produces weird output.

**Expected output**
Should just print the new line character and send it. Not sure if it actually sends it, or maybe just the terminal is stuck, or another weird combination of things.

**Actual output**
It sends multiple lines, and anything you send afterward results in more newlines.
```
ubuntu@ip-10-0-0-62:~$ redis-cli
127.0.0.1:6379>
127.0.0.1:6379>

127.0.0.1:6379>


127.0.0.1:6379>



127.0.0.1:6379>




127.0.0.1:6379>





127.0.0.1:6379>






127.0.0.1:6379>







127.0.0.1:6379>








127.0.0.1:6379>









127.0.0.1:6379>
```

## The story

Ok, so I want to start off by saying that it's broken with **version 18** (anything under it, works fine, tested it untill version 15). This weird behavior happens in **redis-cli** not sure if it happens anywhere else (htop looks fine).
I'm using **ConEmu** with **Powershell 5** with the **Terminal Mode** of ConEmu set to **XTerm** .

Soooo. something must have broken this in version 18, because it was working fine before it.

**Also** another peculiar thing happens: the terminal is not cleared anymore when I ssh to another machine (it used to be the case with previous versions).

I'm not sure if it's redis-cli's fault, but thought I might drop this here as well.

**Comment by bagajjal** [comment] 2017-08-18 17:46
@Mayhem93 - There are many terminal fixes went in version 18 so I am hoping this is a regression issue...

I yet need to repro this issue... I will update this thread soon....

regarding the terminal not getting cleared while doing ssh, this is a bug and its fixed... so the current behavior is correct. However if you connect to windows ssh server, the terminal gets cleared (this is required due to the pty implementation in windows)...

**Comment by Mayhem93** [comment] 2017-08-18 18:08
@bagajjal It's very easy to reproduce, just use redis-cli on a linux machine, or were you not able to reproduce it like I said ?

**Comment by bagajjal** [comment] 2017-08-18 21:54
@Mayhem93 - I haven't tried.. busy in fixing other issues.. 
Will try this early next week..

**Comment by Mayhem93** [comment] 2017-08-28 13:38
I can still replicate this in **0.0.19**

**Comment by bagajjal** [comment] 2017-09-06 18:56
@Mayhem93 - Can you try the latest release 0.0.20.0.
fyi, it works for me..

![redis-cli norepro](https://user-images.githubusercontent.com/23668037/30129336-6b44ff98-92fa-11e7-88d4-cb0fcd09ebec.gif)

**Comment by Mayhem93** [comment] 2017-09-06 19:49
@bagajjal I will, but I'm gonna wait for the release to appear on chocolatey.

**Comment by bagajjal** [comment] 2017-09-12 18:15
@Mayhem93 - Any update on this?

**Comment by Mayhem93** [comment] 2017-09-12 18:47
@bagajjal Upgraded to v0.0.20 and I can't replicate the original issue.

**Comment by bagajjal** [comment] 2017-09-12 19:21
@Mayhem93 - When you ssh to unix ssh server, clear screen shouldn't happen.
I can't repro this (ssh to unix ssh server). Here it is,

![ssh-cls](https://user-images.githubusercontent.com/23668037/30344516-6e6f0fc2-97b6-11e7-99fd-8e85221fff02.gif)


But when you ssh to windows ssh server, clear screen will happen. This is expected because of the pty implementation on windows.

**Comment by Mayhem93** [comment] 2017-09-12 19:55
Yes, that's correct, sorry. I meant to say otherwise

**Comment by bagajjal** [comment] 2017-09-12 19:57
Ok thanks, closing the issue.

**Closed as completed** 2017-09-12 19:56 UTC
Labels: Issue-Bug, Area-Terminal
