### ISSUE TITLE
client doesn't load private key file

### ISSUE THREAD

**Issue by jochemd** [PowerShell/Win32-OpenSSH#817] opened 2017-07-19 19:54 UTC
**"OpenSSH for Windows" version**
0.0.17.0
 
**Server OperatingSystem**
Ubuntu 16.04.2 LTS

**Client OperatingSystem**
Windows 10

**What is failing**
Private key file is not loaded and logon to the server fails

**Expected output**
Succesful logon

**Actual output**
See attached output generated using -vvv: [console-output.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1160233/console-output.txt)

Running **ssh -vvv -i c:\Users\MY_USER_NAME\.ssh\id_rsa MY_USER_NAME@192.168.10.151** fails to login with the attached console output. The file id_rsa exists (no passphrase), and I have set the proper permissions on it using **cacls .\id_rsa /g MY_USER_NAME:c**. I have explicitly removed the config file in my .ssh folder and stopped ssh-agent so there should be nothing but the command I entered.

I would not rule out that there is something weird with my environment variables because I had to set some additional variables to make other programs work (including a different home variable), so I attached them as well: [environment.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1160265/environment.txt)

What I don't understand is how the lines 2, 11, 12, 112, 132 and 142 should be interpreted. They appear to alternate between saying the private key file is there, and the private key file is not there.:
```
Warning: Identity file c:\Users\MY_USER_NAME\.ssh\id_rsa not accessible: No such file or directory.
..
debug3: Failed to open file:C:\\Users\\MY_USER_NAME/.ssh/id_rsa error:2
debug1: identity file C:\\Users\\MY_USER_NAME/.ssh/id_rsa type 0
..
debug2: key: C:\\Users\\MY_USER_NAME/.ssh/id_rsa (0000017DD9B34260)
..
debug1: Offering public key: RSA SHA256:HB8vl+MS9mbS7btPH6cD*********************** C:\\Users\\MY_USER_NAME/.ssh/id_rsa
..
debug3: no such identity: C:\\Users\\MY_USER_NAME/.ssh/id_rsa: No such file or directory```

If I rename the key file to something else, it works just fine.

**Comment by bagajjal** [comment] 2017-07-19 20:15
Please provide the output of this powershell command
get-acl -path c:\Users\MY_USER_NAME.ssh\id_rsa | select *

**Comment by jochemd** [comment] 2017-07-19 20:20
```
PS C:\Users\MY_USER_NAME\.ssh> get-acl -path c:\Users\MY_USER_NAME\.ssh\id_rsa | select *


PSPath                  : Microsoft.PowerShell.Core\FileSystem::C:\Users\MY_USER_NAME\.ssh\id_rsa
PSParentPath            : Microsoft.PowerShell.Core\FileSystem::C:\Users\MY_USER_NAME\.ssh
PSChildName             : id_rsa
PSDrive                 : C
PSProvider              : Microsoft.PowerShell.Core\FileSystem
CentralAccessPolicyId   :
CentralAccessPolicyName :
Path                    : Microsoft.PowerShell.Core\FileSystem::C:\Users\MY_USER_NAME\.ssh\id_rsa
Owner                   : MY_DOMAIN\MY_USER_NAME
Group                   :
Access                  : {System.Security.AccessControl.FileSystemAccessRule}
Sddl                    : O:S-1-5-21-1029124614-2511140237-2146021798-1251G:DUD:P(A;;0x1301bf;;;S-1-5-21-1029124614-251
                          1140237-2146021798-1251)
AccessToString          : MY_DOMAIN\MY_USER_NAME Allow  Modify, Synchronize
AuditToString           :
AccessRightType         : System.Security.AccessControl.FileSystemRights
AccessRuleType          : System.Security.AccessControl.FileSystemAccessRule
AuditRuleType           : System.Security.AccessControl.FileSystemAuditRule
AreAccessRulesProtected : True
AreAuditRulesProtected  : False
AreAccessRulesCanonical : True
AreAuditRulesCanonical  : True
```

**Comment by manojampalam** [comment] 2017-07-21 20:07
Just tried it on my end and it worked without any issues. Otherwise, from code inspection, I'm unable to think of why you would be seeing the above behavior, sorry. Please investigate further and let us know what you find.

**Comment by bagajjal** [comment] 2017-08-02 19:02
Closing this issue as we can't reproduce.

**Closed as completed** 2017-08-02 19:03 UTC
