### ISSUE TITLE
Launching powershell pauses forever and does not start powershell

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/Win32-OpenSSH#59] opened 2015-12-26 14:10 UTC
From iTerm on OSX, TERM=xterm per default:

    ssh mike@192.168.1.104
    mike@192.168.1.104's password:
    Microsoft Windows [Version 10.0.10240]
    (c) 2015 Microsoft Corporation. All rights reserved.

    Windows PowerShell sers\Mike>powershell
    Copyright (C) 2015 Microsoft Corporation. All rights reserved.

(this is all - there's no prompt)

**Comment by quamrulmina** [comment] 2015-12-27 08:01
You have to invoke powershell with "-File -" arguments as shown below.
powershell -File -
look at closed issue #16 for full description.

**Comment by mikemaccana** [comment] 2015-12-27 21:56
FYI #16 includes a workaround, but has been closed without fixing the issue.

**Comment by manojampalam** [comment] 2016-02-01 20:48
closing as dupe of #90

**Closed by manojampalam** 2016-02-01 20:48 UTC
Labels: feature request
