### ISSUE TITLE
100 Mbps bandwidth limit ?

### ISSUE THREAD

**Issue by Nico83500** [PowerShell/Win32-OpenSSH#697] opened 2017-04-28 20:28 UTC
"OpenSSH for Windows" version 0.0.12.0
Windows 7 Professional SP1 x64`
FileZilla 3.25.1

Hi,
Is there a bandwidth limit with SFTP on OpenSSH for Windows ? I have a PC A with a 250 Mbps upload bandwidth and a PC B with a 400 Mbps download. My upload max from A (or download to B) is around 100 Mbps. If I try Speedtest, I can get the real value (upload 247 Mbps).

Is there a 100 Mbps limit with SFTP ?

Thank you.

**Comment by bagajjal** [comment] 2017-04-28 21:06
As far as I have gone through the code, there is no limit on the bandwidth...

Here is the snapshot on my local machine goes more than 32 MBps,
![image](https://cloud.githubusercontent.com/assets/23668037/25547366/a703604c-2c1b-11e7-8b9f-6ebbec6ea71f.png)

**Comment by Nico83500** [comment] 2017-04-28 21:50
Thank you, you're right. I've tried on my Gigabit LAN and I can upload at 39 MBps. But 39 MBps (so 320 Mbps) on a Gigabit LAN is a low value, I don't understand why.

**Comment by bagajjal** [comment] 2017-04-28 22:02
Data is sent in multiple packets.. each packet is encrypted by source, decrypted by the destination.
The processing limit is also limited by the hardware restrictions on both the machines.. 

I am closing this issue as we its not a bug.

**Closed as completed by bagajjal** 2017-04-28 22:02 UTC
