### ISSUE TITLE
Bad output in Putty, Bitvise, TeraTerm and other SSH-clients when console window use scrolling.

### ISSUE THREAD

**Issue by remittor** [PowerShell/Win32-OpenSSH#724] opened 2017-05-18 08:10 UTC
**"OpenSSH for Windows" version**
0.0.13.0
 
**Server OperatingSystem**
Windows 2012 R2 x64

**Client OperatingSystem**
Windows 7 SP1 x64

**What is failing**
Bad output in **Putty**, **Bitvise**, **TeraTerm** and other SSH-clients when console window use scrolling.

**Actual output**
- Putty: https://cloud.githubusercontent.com/assets/9350115/26192267/ad847bce-3bb9-11e7-9ec1-770d6b9ddb99.gif
- Bitvise: https://cloud.githubusercontent.com/assets/9350115/26192452/627bb9de-3bba-11e7-8056-08389a7b8589.gif
- TeraTerm: https://cloud.githubusercontent.com/assets/9350115/26192464/734f2b7e-3bba-11e7-9465-86b14da8785e.gif
- OpenSSH (Ubuntu 14.04): https://cloud.githubusercontent.com/assets/9350115/26193971/81ba5972-3bbf-11e7-8f75-cc911ec45b80.gif

**Expected output**
Execute **ipconfig** in **Bitvise** client after merging https://github.com/PowerShell/openssh-portable/pull/137:
https://cloud.githubusercontent.com/assets/9350115/26045432/dd95444c-3952-11e7-859f-181912ea015c.gif

**Comment by remittor** [comment] 2017-05-18 08:22
The reason for this behavior: the incorrect interpretation of the **CUP** command `ESC[<y>;<x>H`

MSDN: https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx
> Cursor moves to \<x>; \<y> coordinate within the **viewport**, where \<x> is the column of the \<y> line.
> \<x> and \<y> parameters have the same limitations as \<n> above. If \<x> and \<y> are omitted, they will be set to 1;1.

Term **viewport** indicate to using relative cursor coordinates! But OpenSSH-Win32 using absolute cursor coordinates (ssh.exe and ssh-shellhost.exe).

**Comment by remittor** [comment] 2017-05-18 15:25
Also this code block:
https://github.com/PowerShell/openssh-portable/blob/b4a38796b980f139dab7b46b942670f8a1b54937/contrib/win32/win32compat/console.c#L1169-L1172
need transfer to server side (`shell-host.c`).

**Comment by manojampalam** [comment] 2017-05-18 17:35
@remittor thank you for looking into this. @bagajjal will follow up on the proposed changes.

**Comment by bagajjal** [comment] 2017-05-18 17:48
@remittor - This is the base assumption we have taken. when the pseudo terminal is implemented at the server side, ssh server will send the clearscreen to the client at the start of ssh session so that both server and client will be in sync from then on..

ssh standard doesn't mention about sharing the ssh client current location to the ssh server..

**Comment by bagajjal** [comment] 2017-05-18 17:54
@remittor with your recent fix, this problem is fixed? If yes, then this is duplicate of #712 issue? 
Are there any issues that need to be fixed apart from your PR?

**Comment by remittor** [comment] 2017-05-18 19:24
My latest PR fixed several bugs. I show their tomorrow.

**Comment by remittor** [comment] 2017-05-19 07:44
@bagajjal
> your recent fix, this problem is fixed? If yes, then this is duplicate of #712 issue?

My latest PR is fixed several bugs.

> Are there any issues that need to be fixed apart from your PR?

History navigate bugs:
- Putty: https://cloud.githubusercontent.com/assets/9350115/26238010/f642a734-3c7f-11e7-9122-e1acd392eb49.gif
- OpenSSH-Win32: https://cloud.githubusercontent.com/assets/9350115/26238028/09ed9e9c-3c80-11e7-8b10-ceeb2f8be795.gif

**Comment by bagajjal** [comment] 2018-02-09 20:45
This works well with latest version v1.0.0.0

**Closed as completed by bagajjal** 2018-02-09 20:45 UTC
Labels: Issue-Bug, Area-Terminal
