### ISSUE TITLE
AllowGroups in sshd_config does not authorize from nested groups

### ISSUE THREAD

**Issue by t8bloom** [PowerShell/Win32-OpenSSH#921] opened 2017-10-20 20:42 UTC
For sshd.exe version 0.0.21.0

The AllowGroups feature it will only find group members nested one group down.  In my test case I created a local group called SSHUsers and added the line AllowGroups SSHUsers into sshd_config.  I then add a domain group to the local SSHUsers group, and all direct members of that group can access the SSH server.  However users nested within the domain group in another domain group will not be granted access.  This generates two error messages in the security event log:

1: Event ID 4776
The computer attempted to validate the credentials for an account.

Authentication Package:	MICROSOFT_AUTHENTICATION_PACKAGE_V1_0
Logon Account:	NOUSER
Source Workstation:	TEST4
Error Code:	0xc0000064

2: Event ID 4625
An account failed to log on.

Subject:
	Security ID:		NT SERVICE\sshd
	Account Name:		SSHD
	Account Domain:		NT SERVICE
	Logon ID:		0x335117

Logon Type:			8

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		NOUSER
	Account Domain:		

Failure Information:
	Failure Reason:		Unknown user name or bad password.
	Status:			0xc000006d
	Sub Status:		0xc0000064

Process Information:
	Caller Process ID:	0xa74
	Caller Process Name:	C:\Program Files\OpenSSH\sshd.exe

Network Information:
	Workstation Name:	TEST4
	Source Network Address:	-
	Source Port:		-

Detailed Authentication Information:
	Logon Process:		Advapi  
	Authentication Package:	MICROSOFT_AUTHENTICATION_PACKAGE_V1_0
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

**Comment by bagajjal** [comment] 2017-10-20 20:53
I think the issue is because of the cross domain users.

Can you try the same scenario with nested domain group within the same domain.

**Comment by t8bloom** [comment] 2017-10-20 20:54
Yes, this is all from within a single domain.

**Comment by bagajjal** [comment] 2017-10-20 21:09
The sshd.log (with DEBUG3 enabled) will show the groups for the failed user. Could you please verify if the sshd.log has the group configured in the sshd_config.

**Comment by t8bloom** [comment] 2017-10-20 21:28
Thanks for your help on this.  As part of the logon process I can see it enumerate all of my domain groups.  The error returned is 2584 14:19:55:856 User testX@XXXXX.com from XXX.XXX.XXX.XXX not allowed because none of user's groups are listed in AllowGroups.  Explicitly, this is true.  However one of the domain groups I am a member of is nested into the allowed domain group.  It looks like it is enumerating the groups the user is a direct member of from the domain controller, then comparing this to the group listed one layer down in the local group.  My best guess is it is not doing this same interrogation down into the allowed domain groups to check for further nested groups.

**Comment by christian-korneck** [comment] 2017-11-28 08:34
I have the same issue and did some testing. It appears to me that group nesting currently (`0.0.23.0`):
- **only** works if the group that is authorized for access (the one configured in `sshd_config`) is a **domain-local** group.
- Such a domain local group can have a global group as member.
- However, nesting more levels of global groups into a domain local group fails as well.
- And local groups nested in local groups aren't recognized at all.
- computer-local groups seem to behave the same way as domain-local groups in this context (one level of global group nesting is possible, nothing else)

Global groups nested in global groups do *not* appear in the `DEBUG3` output. Global groups nested in local groups however *do* appear in the log.

### working: global in local (exactly single-level nesting)
- nesting: domain\domain-local-group -> domain\globalgroup -> domain\user
- `sshd_config`:  `AllowGroups domain-local-group?domain`
- resulting group list: globalgroup, domain-local-group

### not working (global in global / single-level nesting and above):
- nesting: domain\global-group1 -> domain\global-group2 -> domain\user
- `sshd_config`:  `AllowGroups global-group1?domain`
- resulting group list: global-group2

### also not working: global in local / multi-level nesting):
- nesting: domain\domain-local-group -> domain\globalgroup1 -> domain\globalgroup2 -> domain\user
- `sshd_config`:  `AllowGroups domain-local-group?domain`
- resulting group list: globalgroup2

### also not working: local in local (single-level nesting and above):
- nesting: domain\domain-local-group1 -> domain\domain-local-group2 -> domain\user
- `sshd_config`:  `AllowGroups domain-local-group1?domain`
- resulting group list: domain-local-group2

It might also be worth to note that the group list is entirely empty when trying to authenticate as a user from a foreign domain (domain2\user) to which the computer that runs `sshd` has a domain trust. Login without `AllowGroups` restrictions works though.

From my understanding all of the above mentioned use cases are valid Active Directory usecases.
- Authorizing a global group for access and then nesting multiple levels of global groups into it, is common in single-domain scenarios.
- Authorizing a local group for access and then nesting multiple levels of global groups into it, is common with cross-forest domain trusts
- local groups nested in local groups is probably not so common (but as it's possible some people might use it)

**Comment by NoMoreFood** [comment] 2018-03-04 14:41
@manojampalam, @bagajjal   Has any work on this been done?  This might be something I could look into.

**Comment by manojampalam** [comment] 2018-03-05 17:36
@NoMoreFood nothing beyond what's already on this thread. Sure, contributions are always welcome.

**Comment by NoMoreFood** [comment] 2018-03-06 13:11
@manojampalam Alright, I think I have the issue addressed. You should see a pull request tonight.  In order to deal with nesting, it really looks like we need to generate an s4u token and pull the group out of it.

**Comment by NoMoreFood** [comment] 2018-03-07 04:28
@manojampalam  See https://github.com/PowerShell/openssh-portable/pull/281, specifically https://github.com/PowerShell/openssh-portable/pull/281/commits/8fa938d6722249957417c907fe10d8572feb57cc.    I tried to keep the naming scheme for output as close as possible to the original function.  Below are some tests.


```
User Argument: DomainUser@DOMAIN

-- Old Group Lookup Algorithm:
|---- direct membership - domain group in nested local group@domain
|---- direct membership - domain local group@domain
|---- direct membership - global group@domain
|---- direct membership - local group
|---- direct membership - universal group@domain
|---- domain users@domain
|---- local test group 1
|---- nested membership - local group containing domain group
|---- users
|---- users@domain

-- New Group Lookup Algorithm:
|---- direct membership - domain local group@domain
|---- direct membership - global group@domain
|---- direct membership - local group
|---- direct membership - universal group@domain
|---- domain users@domain
|---- local test group 1
|---- nested domain group in local group@domain
|---- nested group - domain local@domain
|---- nested group - global group@domain
|---- nested group - universal group@domain
|---- nested membership - local group containing domain group
|---- users@builtin


User Argument: DomainUser@domain.bryanberns.com

-- Old Group Lookup Algorithm:
|---- direct membership - domain group in nested local group@domain
|---- direct membership - domain local group@domain
|---- direct membership - global group@domain
|---- direct membership - local group
|---- direct membership - universal group@domain
|---- domain users@domain
|---- local test group 1
|---- nested membership - local group containing domain group
|---- users
|---- users@domain

-- New Group Lookup Algorithm:
|---- direct membership - domain local group@domain
|---- direct membership - global group@domain
|---- direct membership - local group
|---- direct membership - universal group@domain
|---- domain users@domain
|---- local test group 1
|---- nested domain group in local group@domain
|---- nested group - domain local@domain
|---- nested group - global group@domain
|---- nested group - universal group@domain
|---- nested membership - local group containing domain group
|---- users@builtin


User Argument: DOMAIN\DomainUser

-- Old Group Lookup Algorithm:
|---- direct membership - local group
|---- local test group 1
|---- nested membership - local group containing domain group
|---- users

-- New Group Lookup Algorithm:
|---- direct membership - domain local group@domain
|---- direct membership - global group@domain
|---- direct membership - local group
|---- direct membership - universal group@domain
|---- domain users@domain
|---- local test group 1
|---- nested domain group in local group@domain
|---- nested group - domain local@domain
|---- nested group - global group@domain
|---- nested group - universal group@domain
|---- nested membership - local group containing domain group
|---- users@builtin


User Argument: DomainUser

-- Old Group Lookup Algorithm:

-- New Group Lookup Algorithm:
|---- direct membership - domain local group@domain
|---- direct membership - global group@domain
|---- direct membership - local group
|---- direct membership - universal group@domain
|---- domain users@domain
|---- local test group 1
|---- nested domain group in local group@domain
|---- nested group - domain local@domain
|---- nested group - global group@domain
|---- nested group - universal group@domain
|---- nested membership - local group containing domain group
|---- users@builtin


User Argument: LocalUser

-- Old Group Lookup Algorithm:
|---- local test group 2
|---- users

-- New Group Lookup Algorithm:
|---- local test group 2
|---- users
```

**Comment by maertendMSFT** [comment] 2020-04-07 21:12
This should be fixed in the latest version

**Closed as completed by maertendMSFT** 2020-04-07 21:12 UTC
Labels: Issue-Bug, Resolution - Fixed
