### ISSUE TITLE
ssh-copy-id server error: 'exec' is not recognized as an internal or external command/'cat' is not recognized as an internal or external command/(Windows_8.1p1)

### ISSUE THREAD

**Issue by davidgarciaMontreal** [PowerShell/Win32-OpenSSH#1716] opened 2020-12-14 21:56 UTC
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
```
C:\Program Files\OpenSSH>.\sshd.exe --version
unknown option -- -
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
usage: sshd [-46DdeiqTt] [-C connection_spec] [-c host_cert_file]
            [-E log_file] [-f config_file] [-g login_grace_time]
            [-h host_key_file] [-o option] [-p port] [-u len]

C:\Program Files\OpenSSH>```


**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

```Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\191806> ((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductN
ame)
Windows 7 Enterprise
PS C:\Users\191806>```


**Client OperatingSystem**

```
$ uname -a
MINGW64_NT-10.0 C365733 2.10.0(0.325/5/3) 2018-02-12 08:49 x86_64 Msys
```

**What is failing**
ssh copy id is failing. The errors however are on the Server side due to a possible bug on OpenSSH,  see attached logs
**Expected output**
be able to copy the ssh keys from client to server

**Actual output**

*** Client Side ***

```
$ ssh-copy-id my_user@hostxxxx
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/c/Users/myser/.                                                                                ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter                                                                                 out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompt                                                                                ed now it is to install the new keys
mysuer@hostname's password:
'exec' is not recognized as an internal or external command,
operable program or batch file.
'cat' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
```

*** Server side

```
from sshd log on the server side:
435028 2020-12-14 21:21:52.129 debug3: shell: "c:\\windows\\system32\\cmd.exe"
435028 2020-12-14 21:21:52.129 debug3: shell_option: /c
435028 2020-12-14 21:21:52.129 debug3: exec_command: exec sh -c 'cd ; umask 077 ; mkdir -p .ssh && { [ -z `tail -1c .ssh/authorized_keys 2>/dev/null` ] || echo >> .ssh/authorized_keys ; } && cat >> .ssh/authorized_keys || exit 1 ; if type restorecon >/dev/null 2>&1 ; then restorecon -F .ssh .ssh/authorized_keys ; fi'
435028 2020-12-14 21:21:52.129 debug3: arg escape option: TRUE
435028 2020-12-14 21:21:52.129 debug3: spawn_argv[0]: "c:\\windows\\system32\\cmd.exe" /c "exec sh -c 'cd ; umask 077 ; mkdir -p .ssh && { [ -z `tail -1c .ssh/authorized_keys 2>/dev/null` ] || echo >> .ssh/authorized_keys ; } && cat >> .ssh/authorized_keys || exit 1 ; if type restorecon >/dev/null 2>&1 ; then restorecon -F .ssh .ssh/authorized_keys ; fi'"
435028 2020-12-14 21:21:52.129 debug3: spawning "c:\\windows\\system32\\cmd.exe" /c "exec sh -c 'cd ; umask 077 ; mkdir -p .ssh && { [ -z `tail -1c .ssh/authorized_keys 2>/dev/null` ] || echo >> .ssh/authorized_keys ; } && cat >> .ssh/authorized_keys || exit 1 ; if type restorecon >/dev/null 2>&1 ; then restorecon -F .ssh .ssh/authorized_keys ; fi'"
435028 2020-12-14 21:21:52.141 debug2: fd 4 setting TCP_NODELAY
```

**Comment by davidgarciaMontreal** [comment] 2020-12-14 22:03
Server log: [sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/5691839/sshd.log)

**Comment by bagajjal** [comment] 2020-12-14 22:40
ssh-copy-id is not currently supported with win32-openssh.
Duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1467.

**Closed as completed by bagajjal** 2020-12-14 22:40 UTC
Labels: Resolution - Duplicate

**Comment by davidgarciaMontreal** [comment] 2020-12-14 23:43
@bagajjal the other ticket you are referencing is not the same. #1467 is about having a copy of ssh-copy-id as part of openssh distribution. This ticket is for openssh to support it from the client side. At the very least, it would be a good idea to add that ssh-copy-id is not supported in the readme file so that other users dont waste time troubleshooting.

**Comment by martin-braun** [comment] 2024-01-31 14:23
@bagajjal Please re-open this issue, it is not the same, @davidgarciaMontreal is right. I try to install my key via `ssh-copy-id windev` onto a windows machine from MacOS and I get this error. Ultimately, `ssh-copy-id` will have to work with any target OS from any source OS.

The issue you referenced is about `ssh-copy-id` being not available on Windows, this issue is about `ssh-copy-id` not supporting Windows as target os.

**Comment by martin-braun** [comment] 2024-01-31 15:27
I came here, because I got this error when trying to install my public key onto a Windows machine. @bagajjal @davidgarciaMontreal is right, it's not the same issue, but it's not an issue with `win32-openssh` either, so this is the wrong place to report this issue.

The issue is with `openssh` for unix based systems that seems to be incapable to handle Windows destinations when using `ssh-copy-id`.

To solve this, I simply run `ssh windev MKDIR "%USERPROFILE%\.ssh" && ECHO "$(cat "$HOME/.ssh/id_rsa.pub")" \>\> "%USERPROFILE%\.ssh\authorized_keys"` and `ssh windev MKDIR "%PROGRAMDATA%\ssh" && ECHO "$(cat "$HOME/.ssh/id_rsa.pub")" \>\> "%PROGRAMDATA%\ssh\administrators_authorized_keys"` (where `windev` is my destination) instead to get the same result. See https://superuser.com/questions/1445976/windows-ssh-server-refuses-key-based-authentication-from-client to understand why we need to put our key to the `administrators_authorized_keys`, too.

Please note: OpenSSH server needs to be restarted on the remote machine before the changes will be applied.

**Comment by martin-braun** [comment] 2024-01-31 15:27
I came here, because I got this error when trying to install my public key onto a Windows machine. @bagajjal @davidgarciaMontreal is right, it's not the same issue, but it's not an issue with `win32-openssh` either, so this is the wrong place to report this issue.

The issue is with `openssh` for unix based systems that seems to be incapable to handle Windows destinations when using `ssh-copy-id`.

To solve this, I simply run:
- `ssh windev 'MKDIR "%USERPROFILE%\.ssh" 2>NUL & ECHO '"$(cat "$HOME/.ssh/id_rsa.pub")"' >> "%USERPROFILE%\.ssh\authorized_keys"'`, and
- `ssh windev 'MKDIR "%PROGRAMDATA%\ssh" 2>NUL & ECHO '"$(cat "$HOME/.ssh/id_rsa.pub")"' >> "%PROGRAMDATA%\ssh\administrators_authorized_keys"'`

... (where `windev` is my destination) instead to get the same result. See https://superuser.com/questions/1445976/windows-ssh-server-refuses-key-based-authentication-from-client to understand why we need to put our key to the `administrators_authorized_keys`, too.
