### ISSUE TITLE
Match group administrators comment missing a '#' in front of line

### ISSUE THREAD

**Issue by LeaDevelop** [PowerShell/Win32-OpenSSH#2260] opened 2024-08-01 08:51 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Issue spotted when installed ssh server, the default config comes with comment that is missing '#'

### Expected behavior
sshd_config
```console
#Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

### Actual behavior
```
Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

### Error details

```console
connection via password or public key does not estalish
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.20348.2582
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.2582
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

**Comment by poisonbl** [comment] 2024-08-01 14:14
I love the subtle simplicity of this, but... bit of a landmine. See #1324 for a very good discussion of why a lot of folks would agree with your proposed fix, and why it will likely be declined.

**Comment by LeaDevelop** [comment] 2024-08-02 13:47
Thank you, will have a look

**Comment by maertendMSFT** [comment] 2024-08-05 17:57
Closing this as a duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1324.

**Closed as completed by maertendMSFT** 2024-08-05 17:57 UTC
Labels: Resolution - Duplicate
