### ISSUE TITLE
TERM is not defined for remote ssh session

### ISSUE THREAD

**Issue by nigurr** [PowerShell/Win32-OpenSSH#252] opened 2016-06-28 10:26 UTC
Hi,

I initiated ssh from `powershell` to `linux` machine.
After pasting something in command prompt, I can't click on backspace and when I do Ctrl+R, the reverse search UI shows empty. 

Number of UI issues. Is it known issue?

**Comment by welnanick** [comment] 2016-06-30 16:04
Not a Developer of the project, but yes they know there are UI issues. The UI seems has been put on the back burner until they solidify the functionality and stability though. Obviously you should still report all UI issues you come across (that haven't already been reported) so that they have a record of what needs to be fixed.

**Comment by dragon788** [comment] 2016-07-13 18:15
This is a duplicate of #122 .

**Comment by yurashek** [comment] 2016-09-18 21:16
Both bugs (this and #122) has the similar root cause but each one works in different direction.

Root cause of this is:
PowerShell.exe window do not have the TERM (terminfo ...or obsoleted termcap) entry defined.

as a relief (very weak) I am using:
export TERM=ansi
...in bash (running on Solaris) but there is still many issues:
i.e. instead of "Arrow Up" (history) I should use ^p
instead of "arrows" I should use "hjkl" in vi
....and so on and so on.................   :-(

...it is strange there is no one in M$ Corp. who still can remember their "U*X" experience and simply document how the PowerShell.exe window behave (which cursor addressing sequences are used).

**Comment by SteveL-MSFT** [comment] 2017-05-03 21:28
This issue is impacting using powershell within ssh session (from Windows to Linux).  TERM is not defined.  At least on Win10, we should define TERM=xterm.

**Comment by DarwinJS** [comment] 2017-05-03 21:52
@SteveL-MSFT - this is an environment variable that could be set during install?  Setting during install would also allow user override.

**Comment by SteveL-MSFT** [comment] 2017-05-03 21:57
@DarwinJS yes, if it's defined as a user or system env var on Windows, it does get propagated correctly to the remote ssh session side, however, the env var isn't used by Windows itself.  Having it as part of OpenSSH setup would address this and allows end user to change (although they can always set it explicitly within the ssh session or through a startup script)

**Comment by DarwinJS** [comment] 2017-05-03 22:08
@SteveL-MSFT - ok does this sound about right:
- OpenSSH install sets Machine environment variable %TERM% to "xterm"
- OpenSSH install exposes a switch to allow this default to be changed during setup
- If overrides are needed for specific users, those users would simply create an environment variable of the same name to override.

FYI - I believe the environment variable won't be available in SSHD until one reboot because Service Control Manager only reads System environment during Windows startup (because it starts so early)?  If you want it available without reboot you might have to re-read the environment variables from the registry upon service startup.

**Comment by SteveL-MSFT** [comment] 2017-05-03 22:13
Seems reasonable to me.  cc @joeyaiello

**Comment by DarwinJS** [comment] 2017-05-05 11:35
@SteveL-MSFT - Do we know if a reboot is needed for sshd to hand out this environment variable (or updates to it) - i.e. does it rely on inheriting Service Control Manager's environment variables?

If a reboot is needed I was thinking of adding a log note saying one is needed for the value to be used by SSHD.

**Comment by SteveL-MSFT** [comment] 2017-05-05 16:07
@DarwinJS not sure, @manojampalam would know, but I suspect it's not registered to listen for env var changes

**Comment by DarwinJS** [comment] 2017-05-05 16:34
@SteveL-MSFT and @manojampalam - to avoid one more reboot scenario, you wouldn't actually have to listen for environment updates constantly - just read them from the registry upon startup.

Such an implementation would also be helpful for updating this value - they could just restart the service rather than the machine.

It does not look like TERM is settable in SSHD_CONF?

I will assume that it will require a reboot unless I hear otherwise.

**Comment by bagajjal** [comment] 2017-05-05 19:17
@DarwinJS - ssh client will send the TERM to the sshd server as part of session establishment.
Not sure why sshd is linked with the TERM setting here.

**Comment by DarwinJS** [comment] 2017-05-05 20:44
@bagajjal - it is due to my lack of understanding which side was sending to which!  Now that I understand I will set it in both the Machine context and the Process context so that it is immediately available in the console where the install occured.

**Comment by bagajjal** [comment] 2017-05-05 20:50
Could you please explain machine context, process context and how they are related to the ssh, sshd processes.

As you might already know, ssh runs as the user process and sshd runs as the NT Service low privileged process.

![image](https://cloud.githubusercontent.com/assets/23668037/25764287/f1a26a64-319b-11e7-9785-92e2bcd55cae.png)

**Comment by DarwinJS** [comment] 2017-05-05 22:33
Setting it in machine context will default the value for anyone who logs on and uses ssh.exe.  This also sets it for all process types whether they are associated with interactive use or not.

If any given user wants to override the machine value for just themselves, they can manually set the the same variable in their user environment variables.

Setting it at the process level (non-persistent) just prevents having to start a new process to re-read the machine environment.  This is a common challenge when installing automation prerequisites that you usually want to use in the same process.

**Comment by bagajjal** [comment] 2017-07-19 18:16
I have made a code change to set the TERM to "xterm" if the TERM environment variable is not set in the SSH client machine. This change is available in the july-mid release (V0.0.18.0).

**Closed as completed by bagajjal** 2017-07-19 18:16 UTC
Labels: Issue-Bug, Area-Terminal

**Comment by fpqc** [comment] 2017-07-23 08:38
Hey, by the way, this should be xterm-256color since a while ago on Windows 10.  256color support was added and fully stable in Win10CU.

https://github.com/Microsoft/BashOnWindows/issues/1446

This is in the case of the Windows client.
