### ISSUE TITLE
SSH_AUTH_SOCK environment value breaks the ssh client

### ISSUE THREAD

**Issue by Oeffner** [PowerShell/Win32-OpenSSH#72] opened 2016-01-13 01:12 UTC
Setting the environment variable SSH_AUTH_SOCK to anything breaks the ssh client. It is not possible to login to other ssh serves as long as this environment variable is set.
Example:
--------------------------------------------------
C:\Busers\oeffner>ssh rdo20@ketch-linux
Enter passphrase for key 'C:\Users\oeffner\.ssh/id_rsa':
(Ctrl-break)
C:\Busers\oeffner>set SSH_AUTH_SOCK=234

C:\Busers\oeffner>ssh rdo20@ketch-linux

C:\Busers\oeffner>

--------------------------------------------------

Detailed story:
--------------------------------------------------
Further to the wish list item #35 of having a GUI for ssh-agent that mediates public keys similar to Putty's pageant I have been playing around a bit with the current ssh-agent and ssh-add as to do the same from the command line as is done on unix. 
As far as I know the idea is to first call ssh-agent which returns specific values for the environment variables, SSH_AUTH_SOCK  and  SSH_AGENT_PID to be set. 
Once these have been set by the user (or a commandline script) ssh-add should then be called which will prompt the user for the password for his private key that should be located in the .ssh directory.
After that ssh sessions to ssh servers where the corresponding public key has been placed should work without prompting for password.

On my Windows 7 PC I have done the following:

--------------------------------------------------------

C:\Busers\oeffner>ssh-agent
set SSH_AUTH_SOCK=C:\Busers\oeffner/.ssh/agent-28082.7748
set SSH_AGENT_PID=6544
echo Agent pid 6544;
C:\Busers\oeffner>setx SSH_AUTH_SOCK C:/Busers/oeffner/.ssh/agent-28082.7748
SUCCESS: Specified value was saved.
C:\Busers\oeffner>setx SSH_AGENT_PID 6544
SUCCESS: Specified value was saved.
C:\Busers\oeffner>ssh-add

--------------------------------------------------------

I use setx rather than using the set command since setx applies globally for all future cmd shells.
The last ssh-add command prompts me for the password of my private key. From a new cmd shell SSH_AUTH_SOCK  and  SSH_AGENT_PID now have the values set in the previous cmd shell. But attempting to login via ssh to any ssh server now no longer works. There's no error message:

--------------------------------------------------------

C:\Busers\oeffner>ssh rdo20@ketch-linux

C:\Busers\oeffner>ssh rdo20@ketch-linux -v
OpenSSH_7.1p1 Microsoft_Win32_port_with_VS, OpenSSL 1.0.2d 9 Jul 2015
debug1: Connecting to ketch-linux [131.111.187.230] port 22.
debug1: allocating new sfd, sfd [3] fd [3] handle [524] type [2]
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: allocating new sfd, sfd [4] fd [4] handle [532] type [1]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\oeffner\.ssh/id_rsa type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\oeffner\.ssh/id_rsa-cert type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\oeffner\.ssh/id_dsa type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\oeffner\.ssh/id_dsa-cert type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\oeffner\.ssh/id_ecdsa type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\oeffner\.ssh/id_ecdsa-cert type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\oeffner\.ssh/id_ed25519 type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\oeffner\.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.1p1 Microsoft_Win32_port_with_VS Dec 22 2015
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3 pat OpenSSH_6.6.1* compat 0x04000000
debug1: Authenticating to ketch-linux:22 as 'rdo20'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:x9k/RQODnm4JdZYrBcZ2/BGUO0VcQs4Dcbr/KhH0KJI
debug1: Host 'ketch-linux' is known and matches the ECDSA host key.
debug1: Found key in C:\Users\oeffner\.ssh\known_hosts:3
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: allocating new sfd, sfd [4] fd [4] handle [544] type [2]

C:\Busers\oeffner>

--------------------------------------------------------

The problem remains as long as the variable SSH_AUTH_SOCK is set to something. I tried changing the value from C:\Busers\oeffner/.ssh/agent-28082.7748 to C:\\\\Busers\\\\oeffner\\\\.ssh\\\\agent-28082.7748 but to no avail. If I un-set the SSH_AUTH_SOCK variable the ssh client works again but then no longer picks up the private key.

**Comment by quamrulmina** [comment] 2016-01-19 22:51
ssh-agent.exe and ssh-add.exe now works in Windows in the new code update. setting SSH_AUTH_SOCK environment variable will not break ssh client rather ssh client uses it to communicate it with the ssh-agent.

**Comment by Oeffner** [comment] 2016-01-20 00:17
Excellent news. I guess I will need to download and compile the sources myself until a new prerelease is available for download.

**Comment by quamrulmina** [comment] 2016-01-23 00:19
Closing the issue since the problem is fixed. Please reopen it if the problem arises in your tests.

**Closed by quamrulmina** 2016-01-23 00:19 UTC
