### ISSUE TITLE
Why all of the reverts?

### ISSUE THREAD

**Issue by tsd64** [PowerShell/Win32-OpenSSH#1050] opened 2018-01-31 20:02 UTC
Please answer the following

**"OpenSSH for Windows" version**
v1.0.0.0-Beta
 
**Server OperatingSystem**
Windows10

**Client OperatingSystem**
rhel6.9

**What is failing**
It looks like the newest version has reverted to pre-Windows changes, and relying on a Cygwin install to handle the configuration.  I am seeing 

C:\ssh\bin>sshd.exe -D
sshd re-exec requires execution with an absolute path

and 

C:\ssh\bin>c:\ssh\bin\sshd.exe -D
__PROGRAMDATA__\ssh/sshd_config: No such file or directory

This didn't happen in 0.0.22.0

**Comment by manojampalam** [comment] 2018-01-31 20:16
This behavior is what you'd see on Unix too. You are seeing it now because of the work done to get most of sshd logic common between Unix and Windows.

**Comment by tsd64** [comment] 2018-01-31 20:20
This is incorrect behavior.  The server is being started from a Windows DOS prompt, and has nothing to do with the client.

**Comment by manojampalam** [comment] 2018-01-31 20:24
Its not. sshd re-execution will respawn "sshd" and if the original commandline is not absolute, you may end up launching a rogue sshd from your PATH. This is by design and its in OpenSSH core (not Windows specific)

**Comment by tsd64** [comment] 2018-01-31 20:27
There is only the one sshd.exe, and the 0.0.22.0 version worked like a Windows application, not a Unix one.  If this is the desired behavior, then the product isn't going to work for a Windows implementation.

**Comment by bagajjal** [comment] 2018-02-12 20:23
duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1045.

**Comment by manojampalam** [comment] 2018-02-12 20:25
@bagajjal  this is not the same issue as #1045.

**Comment by parejadan** [comment] 2018-07-23 19:15
any update on this?

**Comment by bagajjal** [comment] 2018-07-23 19:21
This is an expected behavior and is inline with UNIX.

**Closed as completed by bagajjal** 2018-07-23 19:21 UTC
Labels: Issue-Question

**Comment by parejadan** [comment] 2018-07-23 19:31
Right, so really I'm trying to just setup the openssh server using this guide https://poweruser.blog/enabling-the-hidden-openssh-server-in-windows-10-fall-creators-update-1709-and-why-its-great-51c9d06db8df

I'm running this command from windows side, NOT unix. Doens't really make sense to execute an exe on the unix side.
![capture](https://user-images.githubusercontent.com/11270882/43098447-37598a84-8e8d-11e8-8919-4b529081e6c2.JPG)

I've tried modifying the `sshd_config_default` (can't seem to get passed the write restriction), also tried to create a `sshd_config`, and specifying the path to my rsa_key. Is there any reliable guide out there for utilizing the openssh server for windows?

**Comment by bagajjal** [comment] 2018-07-23 19:38
Looks like you "%programdata%\ssh" is not created.

Follow steps mentioned in our official blog, 
https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/

**Comment by parejadan** [comment] 2018-07-23 22:17
**Notes for anyone trying to setup wsl as an external ubuntu server**
- Follow official guide https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/
- If anything fails with `__PROGRAMDATA__`, add `%PROGRAMDATA%` to environment variable path, reboot
- If any of the guide steps fail after installing something, reboot
- default location the `ssh_host_ed25519_key` is `C:\ProgramData\ssh` (different from what's specified in official guide)

**Proof - remote into windows laptop via macbook pro**
![photo_2018-07-23_18-17-30](https://user-images.githubusercontent.com/11270882/43105925-ac75bb50-8ea4-11e8-9b06-784b05c5a8d4.jpg)

**Comment by nixit28** [comment] 2020-01-08 23:38
> Looks like you "%programdata%\ssh" is not created.
> 
> Follow steps mentioned in our official blog,
> https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/
I couldn't find OpenSSH in that list, do I need to install some packages.

Thanks,
Nixit
![temp](https://user-images.githubusercontent.com/1281853/72025451-0fbd1f80-3270-11ea-85c2-de2d55eba683.PNG)

**Comment by bagajjal** [comment] 2020-01-09 18:16
@nixit28 - What is the window 10 build are you using? Is it x86 / x64 /ARM / ARM64?
Just to make sure, you are checking in the optional features?
![image](https://user-images.githubusercontent.com/23668037/72093402-2479d180-32c9-11ea-8bbe-1bbfd65b2de0.png)

**Comment by nixit28** [comment] 2020-01-09 18:34
Os is windows server 2016 x64.
yes I am checking under Optional Feature. but the only feature that I am seeing are related to language support and typing.

**Comment by bagajjal** [comment] 2020-01-09 18:48
We don't support on windows server 2016 as optional feature.
You need to use either windows 10 or windows server 2019.

If you are interested then you can install github version on windows 2016. Follow the [installation steps](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH)
