### ISSUE TITLE
Windows Server 2016 Nano

### ISSUE THREAD

**Issue by michael-basil** [PowerShell/Win32-OpenSSH#168] opened 2016-03-26 15:34 UTC
Should this work on Nano?

When I tried it the EXEs do nothing.

mb

**Comment by michaeltlombardi** [comment] 2016-04-27 22:32
This is a duplicate of #114, I think.

**Comment by jdub** [comment] 2016-04-30 04:37
The current release of Win32-OpenSSH + Nano Server Tech Preview 5 work together very well.

```
$ uname -a
Darwin slender.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

$ ssh gunpowder
Microsoft Windows [Version 10.0.14300]
(c) 2016 Microsoft Corporation. All rights reserved.

jdub@GUNPOWDER C:\windows>
```

**Closed as completed** 2016-05-16 06:08 UTC

**Comment by jdub** [comment] 2016-05-18 05:20
Looks like this has regressed as of the May 15 release, at least for installation and configuration:

`ntrights.exe` doesn't work on Nano Server, so the required privileges can't be given to to `NT SERVICE\SSHD` in the install script. There doesn't appear to be a native way to modify those privileges by PowerShell / command line, but cmdlets in the third-party PSCX module may work.

Plus, `psexec.exe` doesn't work on Nano Server, so we can't register the host keys as `SYSTEM` using that method.

**Comment by michael-basil** [comment] 2016-05-18 11:30
Which release or commit works?

**Comment by DarwinJS** [comment] 2016-05-18 12:05
Carbon does rights: http://get-carbon.org/Grant-Privilege.html - and I know from past experience you can just use the assemblies of carbon directly rather than install all of it.

FYI - In the choco package I tried using the task scheduler to register the keys in System context so I could eliminate the dependency on psexec.exe - but ended up punting to psexec.

**Comment by DarwinJS** [comment] 2016-05-18 13:25
I was able to eliminate ntrights.exe in the chocolatey package and use pure powershell.

Will give a shot at removing psexec.exe at a later time.

**Comment by jdub** [comment] 2016-05-18 13:44
The [April 5 release](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/4_5_2016) installed and ran well on Nano Server TP 5.

**Comment by michael-basil** [comment] 2016-05-18 13:50
Thanks

On Wed, May 18, 2016 at 8:44 AM, Jeff Waugh notifications@github.com
wrote:

> The April 5 release
> https://github.com/PowerShell/Win32-OpenSSH/releases/tag/4_5_2016
> installed and ran well on Nano Server TP 5.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/PowerShell/Win32-OpenSSH/issues/168#issuecomment-220029993

## 

_Michael Basil_
LinkedIn https://www.linkedin.com/in/michaelrbasil
NoOps Chicago http://noopschicago.com/
