### ISSUE TITLE
Terminal size set in CONSOLE_SCREEN_BUFFER_INFO and actual console size differ

### ISSUE THREAD

**Issue by nkrepo** [PowerShell/Win32-OpenSSH#707] opened 2017-05-04 11:24 UTC
"OpenSSH for Windows" version
0.0.12.0

OS details
Microsoft Windows 10 Pro 64-bit 10.0.15063 (Creators Update)

What is failing
Terminal size set in CONSOLE_SCREEN_BUFFER_INFO and actual console size differ

Expected output
Terminal size set in CONSOLE_SCREEN_BUFFER_INFO and actual console size should be the same

Tested via powershell's Get-Host cmdlet
```
$h = Get-Host
echo $h.UI.RawUI.WindowSize
```
and directly via win32 api with the following code snippet

```
#include <stdio.h>
#include <windows.h>

int main(int argc, char *argv[])
{
    CONSOLE_SCREEN_BUFFER_INFO csbi;
    int columns, rows;

    GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &csbi);
    columns = csbi.srWindow.Right - csbi.srWindow.Left + 1;
    rows = csbi.srWindow.Bottom - csbi.srWindow.Top + 1;

    printf("columns: %d\n", columns);
    printf("rows: %d\n", rows);
    return 0;
}
```
![localconsole](https://cloud.githubusercontent.com/assets/8989693/25701365/c4b4c4f6-30d4-11e7-9bce-a0479527a8de.png)

Actual output
Started powershell's terminal connected to localhost via sshd and started powershell at the command prompt.

![localopenssh-win32](https://cloud.githubusercontent.com/assets/8989693/25701407/eec48c5e-30d4-11e7-9ecb-e056aa8ecf2e.png)

**Comment by bagajjal** [comment] 2017-05-05 18:46
This is a known issue.. Duplicate of #590

**Closed as completed by bagajjal** 2017-05-05 18:46 UTC
Labels: Issue-Bug, Resolution - Duplicate, Area-Terminal
