### ISSUE TITLE
Using ssh.exe from WSL does not work properly

### ISSUE THREAD

**Issue by StefanScherer** [PowerShell/Win32-OpenSSH#990] opened 2017-12-14 15:24 UTC
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 0.0.24.0

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows 10 Enterprise

**Client OperatingSystem**

**What is failing**
I stripped it down to SSHing into a Ubuntu machine with the `ssh.exe` binary from my WSL shell, but I don't see all texts during login. Also the bash prompt is not shown, but fortunately the output of eg. an `ls` command.

**Expected output**
Expected output should be the same as from a PowerShell terminal:

<img width="953" alt="bildschirmfoto 2017-12-14 um 16 20 46" src="https://user-images.githubusercontent.com/207759/33999442-c8bfbb84-e0ea-11e7-8eb5-3a7afce1d3eb.png">

**Actual output**

<img width="1037" alt="bildschirmfoto 2017-12-14 um 16 13 27" src="https://user-images.githubusercontent.com/207759/33999375-97df718a-e0ea-11e7-82a3-f5effa31c070.png">

My use-case for `ssh.exe` in WSL is running it in a `vagrant ssh` session from WSL. I have to install Vagrant on the Windows side as `vagrant.exe` to interact with VMware Workstation 14 on the host.

Vagrant comes with an embedded msys/cygwin OpenSSH client and I hoped that the native implementation does a better job on the Windows side as a `vagrant ssh` looks the same and looks "stuck" until you type commands.

<img width="1440" alt="bildschirmfoto 2017-12-14 um 16 09 45" src="https://user-images.githubusercontent.com/207759/33999609-30228b6c-e0eb-11e7-8a58-363a4fa42c03.png">

**Comment by bagajjal** [comment] 2017-12-14 19:45
This is an expected behavior.
vagrant terminal is not a standard console terminal so your ssh session is treated as "No pty session".

please see the highlighted (in red color) text.
![inked33999375-97df718a-e0ea-11e7-82a3-f5effa31c070_li](https://user-images.githubusercontent.com/23668037/34011317-7ffb439e-e0c4-11e7-8b15-b6d2fe43d815.jpg)


fyi, we call GetFileType() and expect it to return FILE_TYPE_CHAR (for console terminals).

**Comment by StefanScherer** [comment] 2017-12-14 20:19
Thanks @bagajjal. Right after pasting my screenshot I also saw this message and looked through the sources, even tried `-t` flag, but no difference.
My screenshot that you have marked shows a direct WSL -> ssh.exe call without Vagrant. So it seems WSL does not forwards that it's a terminal, or at least in a another form as ssh.exe expects it?

**Comment by bagajjal** [comment] 2017-12-14 20:23
"-t" will be ignored because its not a standard terminal.

Include the ssh.exe in the path and try the same from powershell/cmd.exe, that should solve your problem.

**Comment by StefanScherer** [comment] 2017-12-14 20:46
OK. Yes, I know that it works from a PowerShell terminal. Also vagrant ssh works from there. But I would like to switch to WSL and use only this the whole day. Not switching back and forward between this command in WSL and that command in PowerShell.
How can we make WSL + ssh work better together?

**Comment by bagajjal** [comment] 2017-12-14 20:52
Have you tried the ssh that comes with the WSL?

**Comment by StefanScherer** [comment] 2017-12-14 20:58
Yes, of course. That works fine, thanks.
It's only the combination of my everyday tools like Vagrant.
I could try to install Linux Vagrant in WSL, but then I'm not able to run VMware Workstation.
That's why I try Windows version of Vagrant + "alias vagrant vagrant.exe" in WSL. But then the ssh command will be called on the Windows side and here I'm stuck.
It would be much easier if the barrier between WSL and Windows would be lower so everything "just works". I know Microsoft is working on that :-) 
I'm figuring out a way for me and my colleages with a set of new company laptops where we have VMware Workstation preinstalled for policy reasons.

**Comment by bagajjal** [comment] 2017-12-14 21:55
From vagrant console, you are invoking "windows vagrant.exe" from WSL which requires "windows ssh client"?
Is it possible from powershell, get into WSL and from there you can invoke "windows vagrant.exe"?
If yes then you don't see this problem. 
If not then try other ssh clients (like putty/Cygwin).. 

From windows openssh side we can't support this scenario because we internally use the windows conhost.. BTW, you can still do all the stuff with "no pty ssh session as well" except that some keystrokes don't work like up/down/left/right, tab, etc.

**Comment by StefanScherer** [comment] 2017-12-14 22:09
Ok, I tried powershell.exe -> ubuntu WSL -> windows vagrant ssh

<img width="963" alt="bildschirmfoto 2017-12-14 um 23 00 43" src="https://user-images.githubusercontent.com/207759/34016581-bd3ae1f2-e122-11e7-8934-809e2f38c815.png">

Now I have to press ENTER multiple times to (eg. ls + 5x ENTER).

Windows Vagrant comes with a embedded Cygwin ssh, same problem there.


I tried the other way around: ubuntu WSL -> powershell.exe > vagrant ssh 

<img width="1040" alt="bildschirmfoto 2017-12-14 um 23 05 56" src="https://user-images.githubusercontent.com/207759/34016774-7172b276-e123-11e7-8c4c-dbccfbd8c13e.png">

Some problem. It really seems to me a problem with ssh.exe

**Comment by bagajjal** [comment] 2017-12-14 22:15
can you try using windows openssh client instead of vagrant ssh and try the same steps
powershell -> Ubuntu WSL -> vagrant using windows openssh client (not embedded Cygwin ssh client).

**Comment by StefanScherer** [comment] 2017-12-14 22:37
OK, I've tried serveral things now without Vagrant, just to keep it simpler and third party tools out of the way. Here are five scenarios:

**Ubuntu WSL -> Ubuntu ssh**
works as expected, as everything keeps in the WSL world

<img width="775" alt="wsl-ssh-fine" src="https://user-images.githubusercontent.com/207759/34017705-1c37e318-e127-11e7-9ff2-a8a510f1209a.png">

**Ubuntu WSL -> windows openssh client**
not everything visible

<img width="819" alt="wsl-ssh exe-not-ok" src="https://user-images.githubusercontent.com/207759/34017715-2b1c2920-e127-11e7-9750-e8a10545562b.png">

**Ubuntu WSL -> powershell.exe -> windows openssh client**
not everything visible, powershell.exe itself as a shell also looks good, so it's able to use the conhost/terminal from the WSL

<img width="819" alt="wsl-powershell-ssh exe-not-ok" src="https://user-images.githubusercontent.com/207759/34017728-3c35bd5c-e127-11e7-910a-1aa3f6e97025.png">

**PowerShell -> windows openssh client**
works as expected, as everything keeps in the Windows world

<img width="880" alt="powershell-ssh exe-fine" src="https://user-images.githubusercontent.com/207759/34017806-80300de6-e127-11e7-864d-c2caf8396843.png">

**PowerShell -> Ubuntu WSL -> windows openssh client**
not everything visible

<img width="882" alt="powershell-wsl-ssh exe-not-ok" src="https://user-images.githubusercontent.com/207759/34017812-8658427e-e127-11e7-8808-3b0805f89a10.png">

**Comment by bagajjal** [comment] 2017-12-15 01:18
Thanks for trying different configurations.

I debugged further. It's not possible to have ssh pty session when launched from WSL (Windows subsystem for Linux) no matter you logged into WSL from powershell/cmd/from other console terminal.

Here is the detailed explanation,
windows ssh.exe allocates a pty session only if ssh.exe has access to the console terminal. 
sshd will instruct the ssh.exe client to move the cursor position, set the console properties, etc.
If we launch the ssh.exe client from WSL (Windows subsystem for Linux), the ssh.exe will be launched as a windows process whose STDIN/OUT will be pipes to WSL, so ssh.exe client can't control the console terminal.

**Comment by StefanScherer** [comment] 2017-12-15 08:14
Thanks @bagajjal for looking into it and asking in WSL project. I've subscribed these issues.
Well it seems this is a hard problem for the tech industry:
Look at https://hashicorp.com and scroll down to the bottom. There, in dark gray letters :-) It's a running gag at HashiCorp.

**Comment by bagajjal** [comment] 2017-12-15 19:56
Closing this issue as it's related to WSL.
Please track the issue on https://github.com/Microsoft/WSL/issues/2406

**Closed as completed by bagajjal** 2017-12-15 19:56 UTC
