### ISSUE TITLE
PermitRootLogin

### ISSUE THREAD

**Issue by SKyLiNe1980** [PowerShell/Win32-OpenSSH#141] opened 2016-02-29 12:34 UTC
Setting PermitRootLogin to NO in the config file is ignored by the sshd.
I assume "root" has been remapped properly to "Administrator". 
After setting PermitRootLogin no, one can still login to the sshd with administrator account.

**Comment by maertendMSFT** [comment] 2020-03-10 21:34
This is by design, closing issue

**Closed by maertendMSFT** 2020-03-10 21:34 UTC
Labels: Resolution - By Design
