### ISSUE TITLE
Text mode application Far manager garbled output

### ISSUE THREAD

**Issue by nkrepo** [PowerShell/Win32-OpenSSH#689] opened 2017-04-27 07:35 UTC
"OpenSSH for Windows" version
0.0.12.0

OS details
Microsoft Windows 10 Pro 64-bit 10.0.15063 (Creators Update)

What is failing
Text mode application Far manager garbled output.
Started cmd.exe and connected via ssh to localhost
```
C:\Users\testuser>ssh localhost
C:\Users\testuser>"c:\Program Files\Far Manager\Far.exe"
```

![image](https://cloud.githubusercontent.com/assets/8989693/25472543/5945d0d4-2b34-11e7-8cd5-845a30a29f5b.png)

Expected output
Started cmd.exe and run far manager locally 
`C:\Users\testuser>"c:\Program Files\Far Manager\Far.exe"`

![image](https://cloud.githubusercontent.com/assets/8989693/25471740/1afe024a-2b31-11e7-82e9-fc5ba8358402.png)

Far can be found in chocolatey and it can be installed with choco.
`choco install far `

**Comment by nkrepo** [comment] 2017-07-20 18:13
Hi manojampalam, tested with v0.0.18.0 , the behaviour is the same. Have you got any time to look into that issue?

**Comment by nkrepo** [comment] 2017-07-21 06:55
Have you been able to reproduce ? Is it related to wrong client window size information defined  in pty/tty session #590 ?

**Comment by bagajjal** [comment] 2017-07-21 18:50
No, this is unrelated to #590. This is a bug in ssh-shellhost.exe  which requires further investigation.

FYI, Issue #590 is not reproducible if we run the sshd in the debug mode (sshd.exe -ddd).

**Comment by bagajjal** [comment] 2018-10-15 17:50
Please try the new windows 10 fall update (https://support.microsoft.com/en-us/help/4464619)

**Comment by bagajjal** [comment] 2018-10-15 17:56
fyi, Just realized the windows 10 fall update is paused because of some known issues.
Please note that bunch of console rendering issues were resolved in the latest windows 10 fall updates.

**Comment by nkrepo** [comment] 2018-10-16 06:20
@bagajjal, I tested locally with Microsoft Windows 10 Pro 64-bit  1809 build  17763 (Fall Update), unfortunately it has the same behavior.

**Comment by bagajjal** [comment] 2018-10-16 18:12
@nkrepo - I verified (Version 10.0.17763.1), it's working on my end.
Can you check the sshd binary version. It should be (7.7.2.1).
FYI, GitHub release doesn't have these changes yet. 

![image](https://user-images.githubusercontent.com/23668037/47037387-a6fdfa80-d133-11e8-8fdb-4f42aabe3c26.png)

**Comment by nkrepo** [comment] 2018-10-24 08:44
@bagajjal , unfortunately I am having hard time to enable the openssh server shipped with Windows 17763.55 (1809) to test it. I tried to install via powershell with the command
`Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0`
It installs the package but it does not create the ssh-agent and sshd services.

Is there any ETA when the GitHub release will include those changes ?

**Comment by bagajjal** [comment] 2018-10-24 17:46
@nkrepo - OpenSSH sshd server uses conpty support provided by Microsoft console team. Unless you upgrade the OS version, you will not get this functionality.

In sshd server, we will check if console provides the conpty support then we are going to use it otherwise we fallback on to ssh-shellhost.exe (current implementation). This check will be added in the next openssh release.

**Comment by nkrepo** [comment] 2018-10-24 17:55
@bagajjal I have upgraded to version 17763.55 (1809 October update) and if I am not mistaken it supports conpty. I successfully build and run the [EchoCon](https://github.com/Microsoft/console/tree/master/samples/ConPTY/EchoCon) example.

Unfortunately I am having hard time installing the sshd server package included in build 17763.55 shipped via windows capabilities, so I cannot test it.

**Comment by bagajjal** [comment] 2018-10-24 18:15
@nkrepo - You can try this private sshd binary. 
1) Get the openssh latest release from github (https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.2.0p1-Beta)

2) replace my [private sshd](https://github.com/PowerShell/Win32-OpenSSH/files/2511757/sshd_conpty.zip)

**Comment by bagajjal** [comment] 2018-10-24 18:23
For the optional feature installation failure check error messages in these files,

CBS.Log=    "C:\windows\logs\CBS\CBS.log"
DISM.log=   "C:\windows\logs\DISM\dism.log"
 
 
More information about these components:
 
https://blogs.technet.microsoft.com/askperf/2008/04/23/understanding-component-based-servicing 
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deployment-troubleshooting-and-log-files 
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/what-is-dism

**Comment by bagajjal** [comment] 2018-10-24 18:30
If this doesn't help then please submit a feedback request in feedback hub

https://microsoft.sharepoint.com/sites/itweb/Software/Windows/windows10/Pages/Submitting-Feedback-on-Windows-10-Feedback-Hub-.aspx

**Comment by nkrepo** [comment] 2018-10-25 07:57
@bagajjal I tested with the private sshd and FAR is displayed correctly when connecting  with the ssh client shipped with WSL's Ubuntu 18.04. 
With the ssh client shipped with v7.7.2.0p1-Beta it still has rendering issues , probably the ssh client should be replaced too to work correctly.

I am looking forward when the changes will land in the Github release.

**Comment by bagajjal** [comment] 2018-10-26 17:43
@nkrepo - I didn't see any issue with ssh client.. 
Can you try my [private ssh binary](https://github.com/PowerShell/Win32-OpenSSH/files/2520233/ssh.zip).
Please let me know if you see any issues.

**Comment by bagajjal** [comment] 2019-12-18 07:53
This should be fixed by now in windows 10.
for Windows 10 below, we provide only basic shell.

**Closed as completed by bagajjal** 2019-12-18 07:53 UTC
Labels: Issue-Bug, Area-Terminal

**Comment by ghost** [comment] 2019-12-29 18:50
> now in windows 10

No, thanks!

Guys use Bitvise SSH Server (for not commercial usage it is free).

**Comment by AndrewSav** [comment] 2019-12-29 21:08
@hardhub Just tried the latest Windows 10 and it works perfectly.

**Comment by ghost** [comment] 2019-12-29 21:50
@AndrewSav I mean "no please, no... do not suggest to use this ShitOS 10"
