### ISSUE TITLE
SSHD stops sending at 2,147,483,648 bytes.

### ISSUE THREAD

**Issue by jakesays** [PowerShell/Win32-OpenSSH#145] opened 2016-03-03 22:35 UTC
SSHD Server: windows 10 64bit
SSH Client: windows 10 64bit.

using pscp -scp <src> <dest>

with a file larger than 2GB causes sshd to stop sending.

**Comment by charleswg** [comment] 2016-03-03 22:58
Confirmed same issue with WinSCP client/Filezilla.  It only takes  2,151,677,952 bytes.

**Comment by imontero** [comment] 2016-03-16 11:48
Same issue, sftp copy stops at 2.147.483.648 exactly.

Origin: SunOS 5.11 11.3 sun4v sparc
Remote: Microsoft Windows [Version 6.1.7601](64 bits)
Openssh remote:  SSH-2.0-OpenSSH_7.1p1 Microsoft_Win32_port_with_VS
Original size of TheFile: 2.551.410.981
Final size on remote: 2.147.483.648

Trace error (on windows side):

  4596 22:32:46 473 debug1: request 65685: write "C:/ThePath/TheFile" (handle 0) off 2148139008 len 32768
  4596 22:32:46 473 error: process_write: seek failed
  4596 22:32:46 473 debug3: request 65685: sent status 5
  4596 22:32:46 473 sent status Bad message
  4596 22:32:46 503 debug1: request 65686: write "C:/ThePath/TheFile" (handle 0) off 2148171776 len 32768
  4596 22:32:46 503 error: process_write: seek failed
  4596 22:32:46 503 debug3: request 65686: sent status 5
  4596 22:32:46 503 sent status Bad message
  4596 22:32:46 504 error: write: The specified network name is no longer available.

If I make the same copy with scp, there's no problem.

May be due 32 bits version of ssh on win?
Any idea?

**Comment by manojampalam** [comment] 2016-03-20 17:26
Try out the latest release. I believe this is due to using 32-bit stat before.

**Comment by bagajjal** [comment] 2017-01-06 00:52
I was able to transfer 7 GB file using SFTP.. please check scp and close it.

**Comment by bagajjal** [comment] 2017-01-06 00:53
removed the SFTP tag as it is working fine.

**Closed** 2017-02-01 04:07 UTC
Labels: Area-SCP, Issue-Bug
