### ISSUE TITLE
DoS vector: ssh-shellhost.exe maxes out a CPU when Fabric connects

### ISSUE THREAD

**Issue by idodeclare** [PowerShell/Win32-OpenSSH#892] opened 2017-09-25 14:30 UTC
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
0.0.20.0
(N.b. the suggest syntax, `((Get-Item (Get-Command .\sshd.exe).Source).VersionInfo.FileVersion)`, fails with: `Get-Item : Cannot bind argument to parameter 'Path' because it is null.`)

**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`
Windows Server 2012 R2 Standard

**Client OperatingSystem**
Centos

**What is failing**
Ad-hoc ssh succeeds to connect the Windows server; but running an SSH command via Fabric does not properly connect, and ssh-shellhost.exe on the server maxes out a CPU. Ctrl-C from the Fabric command does not terminate ssh-shellhost.exe. Running again maxes out another CPU. This can be repeated until the server is unresponsive (straight-forward DoS).

Fabric is using pty=True by default. "TTY PTY support in Windows OpenSSH" does not describe this as a known issue.

The Fabric script, dir.py, is:
```
from fabric.api import *

def dir():
	run("dir ..")
``` 

The command is:
`$ fab -f dir.py -H me@wserver dir`

**Expected output**
Console output akin to:
```
[me@wserver] Executing task 'dir'
[me@wserver] run: dir ..
[me@wserver] out: Microsoft Windows [Version 6.3.9600]
[me@wserver] out: (c) 2013 Microsoft Corporation. All rights reserved.
[me@wserver] out:
[me@wserver] out: me@WSERVER C:\Users\me>dir ..
[me@wserver] out:  Volume in drive C has no label.
[me@wserver] out:  Volume Serial Number is 8AE5-3C58
[me@wserver] out:
[me@wserver] out:  Directory of C:\Users
[me@wserver] out:
[me@wserver] out: 09/25/2017  07:58 AM    <DIR>          .
[me@wserver] out: 09/25/2017  07:58 AM    <DIR>          ..
[me@wserver] out: 12/27/2016  05:24 PM    <DIR>          Administrator
[me@wserver] out: 02/01/2017  11:01 PM    <DIR>          me
[me@wserver] out: 08/22/2013  10:39 AM    <DIR>          Public
[me@wserver] out: 09/25/2017  07:58 AM    <DIR>          SSHD
[me@wserver] out:                0 File(s)              0 bytes
[me@wserver] out:                6 Dir(s)  28,995,772,416 bytes free
```

**Actual output**
Just whitespace in the Fabric output

**Comment by manojampalam** [comment] 2017-09-29 18:08
Possible to collect WPA/XPerf traces that can help us understand what's taking up the CPU?

**Comment by idodeclare** [comment] 2017-09-29 20:09
No — sorry, those tools are unknown to me. I was hoping the details above would help a Win32-OpenSSH developer to reproduce.

**Comment by DominikWiesend** [comment] 2017-11-17 15:06
same here

**Comment by bagajjal** [comment] 2017-11-20 19:52
could you please provide the steps to repro this issue.

Can this script be run in an azure windows VM?

from fabric.api import *
def dir():
	run("dir ..")

**Comment by DominikWiesend** [comment] 2017-11-21 19:22
I'll try to give you all infos you need, currently we are using "OpenSSH for Windows" Version [0.0.23.0]
The problem is in this direction [Linux] -> [Windows (SSH-Server)]
-> Windows Server 2012 R2

When you logon to the [Linux] Host and send an SSH-Command to the [Windows (SSH-Server)] you can run any command without any problems.

But when an program (any pice of software triggers) a command (TTY/PTY) [makes the difrence] the ssh-shellhost.exe isn't closing and is taking more resources till it collected all of them (CPU at 100%).
-> We are currently using an >> ; << at the end of  the SSH-Command, because we think this resolves the issue the most of the time (not sure about it, right now)

I'll provid anything you need, just tell me what it is.

**Comment by pcgeek86** [comment] 2018-01-19 00:06
I'm having the same problem. I configured PowerShell as my default shell.

**Comment by pcgeek86** [comment] 2018-01-19 00:08
I changed my default shell to `c:\Windows\System32\cmd.exe` and I was able to make a successful connection.

**Comment by bagajjal** [comment] 2018-02-14 02:36
@DominikWiesend - I used v1.0.0.0. I couldn't reproduce this issue by doing "Ubuntu -> [Windows (SSH-Server)] -> windows".

Have a look at this,
![ssh-shellhost-cpu-issue](https://user-images.githubusercontent.com/23668037/36185197-b63ecf5e-10ec-11e8-853b-df8e0c7a280b.gif)


@pcgeek86 - Do you have the same scenario  "Ubuntu -> [Windows (SSH-Server)] -> windows" ? Ideally setting default shell to cmd/powershell shouldn't have any issue.

**Comment by pcgeek86** [comment] 2018-02-14 06:10
@bagajjal I haven't reproduced this issue recently. If I reproduce it again, I'll post back with more information.

**Comment by idodeclare** [comment] 2018-02-18 00:03
@manojampalam ,

I still find this issue with v1.0.0.0-Beta. To reproduce:

* On Windows 10, [Install the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Install [openSUSE Leap 42](https://www.microsoft.com/en-us/store/p/opensuse-leap-42/9njvjts82tjx?SilentAuth=1&wa=wsignin1.0&rtc=1)
* Install Fabric:
```
# sudo zypper install python-pip
# sudo pip install fabric
```
* Create the `dir.py` script as documented above in this issue's description:
```
from fabric.api import *

def dir():
	run("dir ..")
```
* Execute `dir.py`:
```
$ fab -f dir.py -H me@wserver dir
```

The resut: "_ssh-shellhost.exe maxes out a CPU when Fabric connects._"

**Comment by bagajjal** [comment] 2018-03-16 22:37
@idodeclare - I followed your instructions. When I execute " fab -f dir.py -H me@wserver dir" command the output is different from the original post.

**Comment by bagajjal** [comment] 2018-03-17 01:11
@idodeclare - I am able to reproduce the issue.

When fab runs the command, sshd will receive **/bin/bash -l -c "dir .."**, requesting for a pty session.

1) I don't know why /bin/bash is sent along with command. When ssh-shellhost.exe executes this command, it will certainly fail.

2) why it's requesting pty session?

**Comment by idodeclare** [comment] 2018-03-17 17:05
Hi, @bagajjal ,

> I don't know why /bin/bash is sent along with command

That is the default shell for Fabric. When hopefully this issue #892 is fixed, upon seeing an error if `/bin/bash` is unavailable, I will override Fabric's `env.shell` or revise the Windows Server OpenSSH configuration to use e.g. Cygwin or WSL.

> why it's requesting pty session?

The following is Fabric's remark (http://docs.fabfile.org/en/1.14/usage/interactivity.html) regarding a pty:

> In the interests of security and meeting the principle of least surprise (insofar as users are typically expecting things to behave as they would when run in a terminal emulator), Fabric 1.0 and greater force a pty by default. With a pty enabled, Fabric simply allows the remote end to handle echoing or hiding of stdin and does not echo anything itself.

**Comment by bagajjal** [comment] 2018-03-19 22:43
@idodeclare - I have fixed. Please try the attached [private ssh-shellhost.exe](https://github.com/PowerShell/Win32-OpenSSH/files/1827222/ssh-shellhost-infinite-loop-fix.zip).

**Comment by idodeclare** [comment] 2018-03-20 02:21
@bagajjal ,

Thank you kindly. That works for me, and I can run the following with `-s` to override `env.shell`:

    $ fab -f dir.py -H me@wserver -s '%SYSTEMROOT%\system32\cmd.exe /C' dir

**Closed as completed** 2018-03-31 06:39 UTC
Labels: Issue-Bug
