### ISSUE TITLE
SFTP fails to connect (OpenSSH.Beta 8.9.1.0 winget install)

### ISSUE THREAD

**Issue by suttonr3** [PowerShell/Win32-OpenSSH#2010] opened 2022-12-09 15:22 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

OpenSSH is installed via winget to C:\Program Files\OpenSSH.  Binary sftp-server.exe lives here.  Winget install of Microsoft.OpenSSH.Beta does not add 'C:\Program Files\OpenSSH' to system path.  SFTP connection fails, SSH connections work as expected.  

### Expected behavior

```console
successful SFTP connection using credentials that work with SSH connection.
```

### Actual behavior

```console
SFTP can not authenticate
```

### Error details

```console
SFTP error #103: Connection closed by lower level protocol (Win10 MobaXterm)

Cannot initialize SFTP protocol. Is the host running an SFTP server? (win10 WinSCP)

Connection failed please verify details (Ubuntu22 Caja/gvfs)

Connection failed.  (Rocky9 Nautilus)
```

### Environment data

```PowerShell
Adding C:\Program Files\OpenSSH to system %PATH% corrects issue.

cmd:  setx /m PATH "C:\Program Files\OpenSSH;%PATH%"
```

### Version

Microsoft.OpenSSH.Beta                   8.9.1.0                        winget

**Comment by suttonr3** [comment] 2022-12-09 15:26
This likely a duplicate of #2007.  I was focused on Win10, not Server.  RS

**Comment by maertendMSFT** [comment] 2022-12-12 17:33
Closing as a duplicate of: https://github.com/PowerShell/Win32-OpenSSH/issues/2006

**Closed as completed** 2022-12-12 17:39 UTC
Labels: Resolution - Duplicate
