### ISSUE TITLE
ssh-add -t does not work

### ISSUE THREAD

**Issue by dcow** [PowerShell/Win32-OpenSSH#1510] opened 2019-11-26 08:04 UTC
**"OpenSSH for Windows" version**
`7.7.2.1`

**Client OperatingSystem**
Win10 19030

**What is failing**
When I try to add an identity to the ssh agent with a bounded lifetime, the operation fails. I have enabled and started the ssh-agent service. Adding and removing identities without a lifetime works:

```
PS> ssh-add
Enter passphrase for <~>/.ssh/id_ed25519:
Identity added: <~>/.ssh/id_ed25519 (dcow@shire) 
PS> ssh-add -l
256 SHA256:+Lo4sy0njfQmmHLX7k0Ws6aUHnfdVquGvRk0zkEP3TY dcow@shire (ED25519)
PS> ssh-add -d
Identity removed: <~>/.ssh/id_ed25519 (dcow@shire) 
```

**Expected output**
```
PS> ssh-add -t30s <~>\.ssh\id_ed25519'
Enter passphrase for <~>/.ssh/id_ed25519:
Identity added: <~>/.ssh/id_ed25519 (dcow@shire)
Lifetime set to 30 seconds
```

**Actual output**
```
PS> ssh-add -t30s <~>\.ssh\id_ed25519'
Enter passphrase for <~>/.ssh/id_ed25519:
Could not add identity "<~>\.ssh\id_ed25519": communication with agent failed
```

**Comment by anthonyvdotbe** [comment] 2019-12-04 11:56
@dcow this is a duplicate of #1056

**Closed as completed** 2020-07-17 17:09 UTC
Labels: Resolution - Duplicate
