### ISSUE TITLE
SSHD doesn't work on Server 2008 R2 

### ISSUE THREAD

**Issue by harpsingh** [PowerShell/Win32-OpenSSH#244] opened 2016-06-17 07:40 UTC
I installed Win32 OpenSSH 5_30_2016 on a Windows Server 2008 R2 box. sshd.exe consumes a lot of CPU and keeps writing the following to sshd.log files, the log file fills up to 10MB in 10 seconds.

`3656 09:30:07 875 error: accept: Unknown error
3656 09:30:07 875 error: accept: Unknown error
3656 09:30:07 876 error: accept: Unknown error
3656 09:30:07 876 error: accept: Unknown error
3656 09:30:07 876 error: accept: Unknown error
3656 09:30:07 876 error: accept: Unknown error
3656 09:30:07 876 error: accept: Unknown error
3656 09:30:07 876 error: accept: Unknown error
3656 09:30:07 876 error: accept: Unknown error
3656 09:30:07 876 error: accept: Unknown error`

When I launch sshd.exe -d it shows the following and ERROR:22 goes on forever:

`C:\Program Files (x86)\OpenSSH-Win32>sshd.exe -d
debug1: sshd version OpenSSH_7.1, OpenSSL 1.0.2d 9 Jul 2015
[Build May 30 2016 09:56:31]
debug1: open - handle:000000F0, io:00869B28, fd:3
debug1: ReadFileEx() ERROR:38, io:00869B28
debug1: read - no more data, io:00869B28
debug1: ReadFileEx() ERROR:38, io:00869B28
debug1: read - no more data, io:00869B28
debug1: close - io:00869B28, type:2, fd:3, table_index:3
debug1: open - handle:000000F0, io:00869B28, fd:3
debug1: close - io:00869B28, type:2, fd:3, table_index:3
debug1: private host key #0: ssh-rsa SHA256:/ebx4IGqGd1aBRgwcvlU9keH/y99w44G5Ly2
lrUXxyE
debug1: open - handle:000000F0, io:00869BA8, fd:3
debug1: ReadFileEx() ERROR:38, io:00869BA8
debug1: read - no more data, io:00869BA8
debug1: ReadFileEx() ERROR:38, io:00869BA8
debug1: read - no more data, io:00869BA8
debug1: close - io:00869BA8, type:2, fd:3, table_index:3
debug1: open - handle:000000F0, io:00869BA8, fd:3
debug1: close - io:00869BA8, type:2, fd:3, table_index:3
debug1: private host key #1: ssh-dss SHA256:jM6wnTs+3LJNjl4tQz65o6C9Sqzf3QcHuVSY
5W/CrYY
debug1: open - handle:000000F0, io:00869BA8, fd:3
debug1: ReadFileEx() ERROR:38, io:00869BA8
debug1: read - no more data, io:00869BA8
debug1: ReadFileEx() ERROR:38, io:00869BA8
debug1: read - no more data, io:00869BA8
debug1: close - io:00869BA8, type:2, fd:3, table_index:3
debug1: open - handle:000000F0, io:00869BA8, fd:3
debug1: close - io:00869BA8, type:2, fd:3, table_index:3
debug1: private host key #2: ecdsa-sha2-nistp256 SHA256:o96pH0EL6dA1stfmLfZbyhup
ElXvShS97NdOOAiTW4k
debug1: open - handle:000000F0, io:00869BA8, fd:3
debug1: ReadFileEx() ERROR:38, io:00869BA8
debug1: read - no more data, io:00869BA8
debug1: ReadFileEx() ERROR:38, io:00869BA8
debug1: read - no more data, io:00869BA8
debug1: close - io:00869BA8, type:2, fd:3, table_index:3
debug1: open - handle:000000F0, io:00869BA8, fd:3
debug1: close - io:00869BA8, type:2, fd:3, table_index:3
debug1: private host key #3: ssh-ed25519 SHA256:e4rah++gXi8c++G9AMnEbcCa84u1Bnuv
sf0KHjMiy0Q
debug1: socket:240, io:00869BA8, fd:3
debug1: Bind to port 8022 on ::.
Server listening on :: port 8022.
debug1: socket:256, io:00869C28, fd:4
debug1: Bind to port 8022 on 0.0.0.0.
Server listening on 0.0.0.0 port 8022.
debug1: acceptEx - AcceptEx() ERROR:22, io:00869BA8
debug1: accept - ERROR: async io completed with error: -9978, io:00869BA8
accept: Unknown error
debug1: acceptEx - AcceptEx() ERROR:22, io:00869BA8
debug1: accept - ERROR: async io completed with error: -9978, io:00869BA8
accept: Unknown error
debug1: acceptEx - AcceptEx() ERROR:22, io:00869BA8
debug1: accept - ERROR: async io completed with error: -9978, io:00869BA8
accept: Unknown error
debug1: acceptEx - AcceptEx() ERROR:22, io:00869BA8
debug1: accept - ERROR: async io completed with error: -9978, io:00869BA8
accept: Unknown error
debug1: acceptEx - AcceptEx() ERROR:22, io:00869BA8
debug1: accept - ERROR: async io completed with error: -9978, io:00869BA8
accept: Unknown error
debug1: acceptEx - AcceptEx() ERROR:22, io:00869BA8
debug1: accept - ERROR: async io completed with error: -9978, io:00869BA8
accept: Unknown error
debug1: acceptEx - AcceptEx() ERROR:22, io:00869BA8
debug1: accept - ERROR: async io completed with error: -9978, io:00869BA8
accept: Unknown error
debug1: acceptEx - AcceptEx() ERROR:22, io:00869BA8
debug1: accept - ERROR: async io completed with error: -9978, io:00869BA8
accept: Unknown error
debug1: acceptEx - AcceptEx() ERROR:22, io:00869BA8
debug1: accept - ERROR: async io completed with error: -9978, io:00869BA8
`

I've tried both 32-bit and 64-bit versions, have tried to uninstall it completely and re-install it. When I try to ssh to the affected host, it tries to connect but stays there, doesn't show any error. It works fine on a different server though.

I've also tried ntrights.exe -u +r SeAssignPrimaryTokenPrivilege and restarted sshd service.

Any help will be appreciated.

**Comment by harpsingh** [comment] 2016-06-21 07:07
Any help here?

**Comment by dud225** [comment] 2016-06-22 16:24
Hello @harpsingh 
I have the same issue. Muting sshd seems to be the sole workaround for now.
See : https://github.com/PowerShell/Win32-OpenSSH/issues/138 for more details.
dud

**Comment by manojampalam** [comment] 2016-07-01 18:05
@dud225 are you also using Server 2008 R2 ? can you guys check if you have any other program taking up TCP 22 port ? 
netstat -anop TCP

**Comment by dud225** [comment] 2016-07-04 08:16
@manojampalam 
I'm using 2012 R2. I can confirm that port 22 is available prior to the start of OpenSSH.

**Comment by dveter** [comment] 2016-07-05 09:16
Same problem. 32-bit Server 2008 R2, port 22 looks opened using netstat.

**Comment by Aetylus** [comment] 2016-08-01 18:42
I'm also having the same issue, but on rather clean install of Windows Server 2012 R2.

**Comment by richard-browne** [comment] 2016-08-11 01:09
I have the same problem. But I'm on Windows 7.

**Comment by richard-browne** [comment] 2016-08-11 04:27
Ok, for others having this issue. I've debugged sshd in Visual Studio and I believe it's an issue with IPv6 (AF_INET6). Can you please try putting this line in your sshd_config file and tell me if it fixes the problem:

AddressFamily inet

**Comment by harpsingh** [comment] 2016-08-11 12:17
I just tried to add "AddressFamily inet" to my sshd_config, restarted sshd but the log continues to grow like before.

**Comment by Aetylus** [comment] 2016-08-11 14:04
@richard-browne Thanks, that seems to have fixed the issue on Server 2012 R2!

**Comment by richard-browne** [comment] 2016-08-12 00:24
Alrighty I have a fix. The socketio_acceptEx() function in socketio.c needs to specify the right AF_INET/AF_INET6 family in the socket() call that creates the accept socket. At the moment it's passing AF_UNSPEC which works for AF_INET sockets but fails for AF_INET6. (The AcceptEx call returns WSAEINVAL).

Could one of the devs kindly incorprate the attached patch please..

[sockio.c.txt](https://github.com/PowerShell/Win32-OpenSSH/files/414456/sockio.c.txt)

**Comment by kassyuz** [comment] 2016-09-05 10:22
@richard-browne Thanks, after I added "AddressFamily inet" ran on Server 2008 R2 Std!

**Comment by Cris70** [comment] 2016-10-28 07:53
Adding "AddressFamily inet" fixed the problem here on Windows Server 2008 R2 Std SP1.

**Comment by Leproide** [comment] 2017-03-24 22:16
Same problem.
W7 Pro

https://github.com/PowerShell/Win32-OpenSSH/issues/606

**Comment by manojampalam** [comment] 2018-01-25 01:19
This issue should be fixed by now. Please reopen if you still see it

**Closed as completed by manojampalam** 2018-01-25 01:19 UTC
Labels: Issue-Bug

**Comment by shashwat001** [comment] 2021-05-27 03:47
AddressFamily inet fixed for port forwarding but now reverse ssh tunnel has started giving the error `kex_exchange_identification: Connection closed by remote host`

Following are logs from host starting reverse ssh tunnel
```
debug3: receive packet: type 81
debug1: remote forward success for: listen 6500, connect localhost:22
debug1: All remote forwarding requests processed
debug3: receive packet: type 90
debug1: client_input_channel_open: ctype forwarded-tcpip rchan 2 win 2097152 max 32768
debug1: client_request_forwarded_tcpip: listen localhost port 6500, originator ::1 port 53058
debug2: fd 4 setting O_NONBLOCK
debug3: socketio_getsockopt - ERROR:10022
debug1: getsockopt TCP_NODELAY: Invalid argument
debug1: connect_next: host localhost ([::1]:22) in progress, fd=4
debug3: fd 4 is O_NONBLOCK
debug3: fd 4 is O_NONBLOCK
debug1: channel 0: new [::1]
debug1: confirm forwarded-tcpip
debug3: channel 0: waiting for connection
debug3: finish_connect - ERROR: async io completed with error: 10061, io:0312BF20
debug1: channel 0: connected to localhost port 22
debug3: send packet: type 91
debug3: recv - from CB ERROR:10061, io:0312BF20
debug2: channel 0: read<=0 rfd 4 len -1
debug2: channel 0: read failed
debug2: channel 0: chan_shutdown_read (i0 o0 sock 4 wfd 4 efd -1 [closed])
```
