### ISSUE TITLE
SSHD needs to do network logon while authenticating user (It currently tried Interactive first that results in non-elevated tokens)

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PowerShell/Win32-OpenSSH#84] opened 2016-01-22 14:42 UTC
Hi all!

Playing around with SSHD, noticed that connections don't appear to be elevated (getting SID S-1-16-8192 rather than S-1-16-12288).

While this is a sensible default, is there functionality in place to allow elevation?

Thanks!

**Comment by manojampalam** [comment] 2016-02-01 20:21
If you are taking about local admin accounts, try adding (or flipping) this UAC reg key and see if it works - https://support.microsoft.com/en-us/kb/942817

All other admin accounts (in build Administrator and domain users) should be elevated (reactive if see otherwise)

**Comment by RamblingCookieMonster** [comment] 2016-02-02 14:53
Hi!

This doesn't seem to be the case. I'm using a high privileged, domain account.

Running the following all as that same domain account:

* On the local box, running Windows PowerShell with elevated credentials, I have elevated access (groups include S-1-16-12288).
* Connecting over WinRM from another Windows system, I do get elevated access.
* Connecting over SSH, I don't get elevated access, I get S-1-16-8192.
* Connecting over SSH, after setting that value (prefer to avoid that...) and rebooting, I don't get elevated access.

Is this something that was added after the initial release? I'm not building from source - hoping to see a deployment pipeline for those of us that would like to test this with the latest though : )

Thanks!

**Comment by manojampalam** [comment] 2016-02-03 18:37
Yes, I see the issue in code. Interactive logon is tried first that will always result in stripped token. Try turning off UAC altogether to unblock for now (disable the group policy setting).

**Comment by dobsa** [comment] 2016-02-28 21:39
Hi, please take a note that new RFC with extension for token elevation called "elevation" in SSH server is on the way. The point is that it should be user (via client) who decides what kind of token he/she wants to receive on the server side. Here is current draft: [Section 3.4](https://datatracker.ietf.org/doc/draft-ssh-ext-info/?include_text=1).

**Comment by jhudsoncedaron** [comment] 2016-03-01 18:39
Workaround: Turn off UAC -- but turning off UAC causes horrendous things to happen to the Windows 10 explorer. Bad workaround. Very bad.

The thing about what happens to explorer when UAC is off is classified as by design by Microsoft, but as a bug by anybody else encountering it. Shrug.

**Comment by manojampalam** [comment] 2016-03-01 20:40
Point taken. Will fix this soon.

**Comment by manojampalam** [comment] 2016-03-20 17:34
Fixed in latest release. Admin sessions will have admin privileges. This bit may need flipping though.
https://support.microsoft.com/en-us/kb/942817

**Closed by manojampalam** 2016-03-20 17:34 UTC
Labels: bug
